### ISSUE TITLE
Date of last online status

### ISSUE THREAD

**Issue by Fohroer** [kontalk/androidclient#1000]
### Expected behavior
Correct date of last online status.

### Actual behavior
Not correct calculation and non every-minute update of calculation.

### Steps to reproduce
Just view contact which isn't online and wait 5 minutes with screen on and Kontalk opened on this contact.

### Environment

Kontalk version: latest from F-droid.

Android version: 6.0

Device model: Vernee thor

![see this](https://cloud.githubusercontent.com/assets/6697344/26034255/b05f7582-38c2-11e7-8928-4815420e8da2.png)

**Comment by daniele-athome** [comment]
Duplicate of #378.

**Comment by Fohroer** [comment]
It's not duplicate. It's also a mention of incorrect date. Problem is active even after going to menu and then to contact again. As I remember.

**Comment by daniele-athome** [comment]
The time indicated there is not precise, it's an approximation. I mean when it says "1 hour" it means "approximately 1 hour". Is that what you're referring to?

**Comment by Fohroer** [comment]
Approximately? Hm, that's a kind of sound. So you can add parameter 'more than 1 hour'. That would be more correct.

**Comment by daniele-athome** [comment]
I've been using this to create that string: https://developer.android.com/reference/android/text/format/DateUtils.html#getRelativeDateTimeString(android.content.Context,%20long,%20long,%20long,%20int)

It seems it's not precise enough... I'll investigate some other methods.
