### ISSUE TITLE
[Request] Add WhatsApp and other IM integration

### ISSUE THREAD

**Issue by Megver83** [kontalk/androidclient#1003]
Hi, as we know, Kontalk's protocol is based on XMPP and it is compatible with it. In fact, [there is a way to connect XMPP with WhatsApp](https://conocimientoslibres.tuxfamily.org/conectar-xmpp-con-whatsapp-usando-yowsup-y-transwhat/), and you can chat with WA users, be on their groups, etc. This is possible with [yowsup](https://github.com/tgalal/yowsup) and [transWhat](https://github.com/stv0g/transwhat)

You can make an integration that, if enabled, the user automatically gets the account (that's what yowsup does) and immediately starts chatting with WA users (that's transWhat's job, and in that case you'd have to add the support in the servers).

There are also other ways to do sth. similar with Telegram, Skype, etc. I know that anyone could say "But if you want compatibility with such services, then use XMPP and leave Kontalk in peace", but I think that the more integrations Kontalk has, the easier is for users to switch from those services (Like Diaspora*'s social network integration). For you to know, the server jabjab.de has many of these transports, so if you want to make experiments :open_mouth:

**Comment by OffifialMITX** [comment]
For me this idea sounds like when (a year ago? A half?) there was this project where Microsoft wanted to implement apt-get into Win10 (No idea if they succeeded).
I mean, Kontalk's aims are mostly the opposite of what WA is, so why should it start working with it? It's not a rethorical question.

**Comment by Megver83** [comment]
>For me this idea sounds like when (a year ago? A half?) there was this project where Microsoft wanted to implement apt-get into Win10 (No idea if they succeeded).

What they did was to make Ubuntu run on top of Win10, so in that way you could literally run all Ubuntu's commands.

>I mean, Kontalk's aims are mostly the opposite of what WA is, so why should it start working with it? It's not a rethorical question.

I understand what you mean, and I support that idea. But think, how many ppl **would** use Kontalk instead of WhatsApp, but they can't because they need to have contact with ppl who don't and won't use Kontalk? That's why, in my opinion, it'd be a better way to bring more ppl to Kontalk..

**Comment by daniele-athome** [comment]
I shall not start with an endless list of reasons :-) but... ethical and project aim talks aside for a moment, I believe Facebook will ban user accounts they are detected to be coming from non-official clients if I recall correctly, right?
