### ISSUE TITLE
not possible to add attachments

### ISSUE THREAD

**Issue by freddii** [kontalk/androidclient#1006]
I am not able to add pictures or sounds to a conversation.  
I am getting an error for fileupload.
It says: "Fehler beim hochladen des Anhangs."

I am using kontalk version 4.03 on android 5.1.1

**Comment by freddii** [comment]
It worked perfect for 4.03 until yesterday.
Maybe a change on the code of the server ?

**Comment by daniele-athome** [comment]
It should be working now. Can you try again?

**Comment by freddii** [comment]
Works now. Thanks a lot.
