### ISSUE TITLE
message is lost

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#1008]
### Expected behavior
All messages should received

### Actual behavior

Messages will received from server (one checkmark) but never delivered to the receiver

### Steps to reproduce

Both phones are in the same stable wifi network.
Sending the same message again 10 or 20 seconds later works.

We sit together side by side with the same phone model ;-)

### Environment

Kontalk version: 4.0.3 Google Play

Android version: 7.0

Device model: Huawei nova CAN-L11

### Logs

No logs. Sorry

**Comment by webratte** [comment]
I forgot:

The receivers phone was unlocked and Kontalk open and online with the senders chat.

**Comment by OffifialMITX** [comment]
I've experiended a similar problem on my V22.

**Comment by daniele-athome** [comment]
It happened to me too but like once 6 months ago. I'm still investigating because that's a Tigase problem and it's not easy to fix - it's a very very rare condition.

**Comment by daniele-athome** [comment]
I'm going to close this after having closed #1094 because they might be very well related. Feel free to open it again in the next version if the issue occurs again.
