### ISSUE TITLE
Showcases

### ISSUE THREAD

**Issue by Fohroer** [kontalk/androidclient#1014]
### Expected behavior
Graphical helper which shows what program can do and how with explanations.

**Comment by daniele-athome** [comment]
Do you mean something like this?
https://github.com/amlcurran/ShowcaseView

**Comment by OffifialMITX** [comment]
This is what I've been talking about a while ago.

**Comment by Fohroer** [comment]
@daniele-athome yes. Send me text strings before the release so I'll make Russian translation.

**Comment by daniele-athome** [comment]
@Fohroer we'll put them in our [translation portal](https://translate.kontalk.org/) as usual :-)

**Comment by daniele-athome** [comment]
I'm thinking on working on this, do you have ideas about what to explain? I kind am biased for this task eheh, I was thinking about explaining:

* the red warning bar at the bottom ("key not verified")
* attachment icon in a conversation
* in a conversation, if you click the toolbar you get contact details
* floating action button in the main screen (it seems very obvious to me, still...)

What else?
