### ISSUE TITLE
Notification for groupchat especially

### ISSUE THREAD

**Issue by Fohroer** [kontalk/androidclient#1033]
### Expected behavior
If contact writes me a message via group chat show that message has been written via groupchat.

### Actual behavior
Just message from exact contact in notifications

### Steps to reproduce
1. Join groupchat
2. Receive a message from it

### Environment

Kontalk version: any 4.x
Android version: any
Device model: any

**Comment by daniele-athome** [comment]
Thanks for reporting. I don't think I understand exactly where the issue is, can you provide a screenshot please? I guess the issue also comes with 4.0.4 right?

**Comment by tetris4** [comment]
I think @Fohroer is referring to some kind of icon or special sign in the notification area that a message was received inside a group chat and not in a standard 1on1 chat.

**Comment by daniele-athome** [comment]
I figured that out too, still I don't understand what exactly.

**Comment by Fohroer** [comment]
@daniele-athome it's what @tetris4 mentioned. Add a special icon in notification if the message received came from groupchat, not from contact directly. Understand?

**Comment by daniele-athome** [comment]
Wait, the notification icon I can't really change. That icon must be the app icon as indicated by Android guidelines. Or at most a variant of it to indicate multiple notifications.
The contact picture is different for groups though (when you expand the notification panel).
