### ISSUE TITLE
Installing the app for the second time

### ISSUE THREAD

**Issue by josta66** [kontalk/androidclient#1038]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment

Kontalk version: (please also specify origin, e.g. F-Droid or Google Play)

Android version: (please also specify custom ROM name if applicable)

Device model:

### Logs

If you have a system log related to the issue please send it via email at
devteam (at) kontalk.org. Please do not attach it or publish it anywhere because
it may contain sensitive information. If you have root access, you can use Catlog
(available on both Google Play and F-Droid) to produce it. Alternatively, if you
have the Android SDK installed on your computer, connect your device and execute:

```
adb logcat -d | grep `adb shell ps | grep org.kontalk | cut -c10-15` >kontalk-log.txt
```

and send us the text file.

### Other

If there is a relevant forum discussion, please link to it here.

**Comment by daniele-athome** [comment]
I'm sorry what was the intended bug report? I believe you just submitted the issue template.
