### ISSUE TITLE
Group chats not showing on different devices

### ISSUE THREAD

**Issue by xilixi** [kontalk/androidclient#1040]
I use kontalk with my tablet and mobile phone.

### Expected behavior
I receive messages from a group chat in both devices (tablet and mobile phone)

### Actual behavior
I only receive replies in the device that I used to create the group.

### Steps to reproduce
1. Create a group chat using any of two devices.
2. Send a message using that devices.
3.(You don't get group chat in the second device.

### Environment

Kontalk 4.0.4 (and previous)

Android version: Mobile phone: 6.0.1. Tablet: 5.1.1

Device model:
Mobile phone: Sony Xperia Z3 Compact
Tablet: Sony Xperia Z

**Comment by daniele-athome** [comment]
Thanks for reporting. This is not a bug, it's a missing feature that will be address in #250.
