### ISSUE TITLE
Verification failed; unable to read any of my messages

### ISSUE THREAD

**Issue by feinstaub** [kontalk/androidclient#1044]
After booting the phone in safe mode and then again in normal mode Kontalk started as if started the first time (my phone not registered). I cannot access any of my messages. The verification process fails with a generic error message.

### Expected behavior
* After entering the phone number the verification process should either complete or tell the user what went wrong.
* Even without verification it should be possible to access already sent and received messages.

### Actual behavior
* The verification process did not complete. A message is shown saying one should try again later. I tried for several weeks but nothing changed. At least two other installations I know of have the same problem.

### Steps to reproduce
1. Try to complete the verification process
2. Try to determine what went wrong (not possible, just a generic message)

### Environment
Kontalk version: 4.0.3, F-Droid

Android version: Replicant Android version 4.2.2

Device model: Samsung S2

### Logs
(problems installing CatLog)

**Comment by feinstaub** [comment]
Thanks for the reply. I was not able to send the debug log. Every method I used did not contain any debug text. I reinstalled Kontalk and then the registration could be completed successfully.

The chat history is gone, though. Are all the past messages deleted? Or "just" encrypted (which would probably be the same as deleted)? Or is there a chance to get them back?

**Comment by daniele-athome** [comment]
> Thanks for the reply. I was not able to send the debug log. Every method I used did not contain any debug text. I reinstalled Kontalk and then the registration could be completed successfully.

Ok so it was probably some inconsistency introduced with safe mode. I'll do some tests.

> The chat history is gone, though. Are all the past messages deleted? Or "just" encrypted (which would probably be the same as deleted)? Or is there a chance to get them back?

Chat history is currently stored on the device only, so it's lost, sorry. Besides, (but that's not your case) account deletion triggers automatic purge of all messages (as a security feature).

**Comment by feinstaub** [comment]
> Chat history is currently stored on the device only, so it's lost, sorry.

I did not switch the device. I still use the same device. Is the chat history lost anyway?

**Comment by OffifialMITX** [comment]
It's stored as in-app data so only Kontalk is allowed to access it (if the device is not rooted) and the data gets deleted when you uninstall the app.

On August 24, 2017 11:50:36 AM GMT+02:00, feinstaub <notifications@github.com> wrote:
>> Chat history is currently stored on the device only, so it's lost,
>sorry.
>
>I did not switch the device. I still use the same device. Is the chat
>history lost anyway?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/1044#issuecomment-324588943

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
