### ISSUE TITLE
Federation problem (may it be in the server?)

### ISSUE THREAD

**Issue by susobaco** [kontalk/androidclient#1061]
In gajim clients on an account on the suchat. org server, a message appears:
"Authentication failed: Peer provider no SASL mechanisms" and the kontalk contacts appear as disconnected. Can it be a server problem?

**Comment by daniele-athome** [comment]
If I understand this correctly, I believe this is a client-to-server issue with suchat.org, not Kontalk. Can you confirm? Can you chat with other suchat.org contacts?

**Comment by susobaco** [comment]
I checked it, seem to be a problem of suchat.org. Sorry.
