### ISSUE TITLE
Kontalk crashes with newest commit 65d71c8

### ISSUE THREAD

**Issue by 115ek** [kontalk/androidclient#1064]
### Expected behavior
Kontalk should start

### Actual behavior
Kontalk crashes immediately

### Steps to reproduce
1. install newest build 
2. try to start 
3. crash

### Environment

Kontalk version: 65d71c8d00ba1ac8be5ccd3193e2ed3b6fbdc37e (f-droid)

Android version: 7.1.2 (Lineage 14.1)

Device model: Samsung S III Mini

### Logs

`09-07 15:15:50.500 32341 32341 D AndroidRuntime: Shutting down VM
09-07 15:15:50.502 32341 32341 E AndroidRuntime: FATAL EXCEPTION: main
09-07 15:15:50.502 32341 32341 E AndroidRuntime: Process: org.kontalk, PID: 32341
09-07 15:15:50.502 32341 32341 E AndroidRuntime: java.lang.RuntimeException: Unable to start service org.kontalk.service.msgcenter.MessageCenterService@e485109 with Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }: java.lang.StringIndexOutOfBoundsException: length=20; regionStart=0; regionLength=23
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3368)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: Caused by: java.lang.StringIndexOutOfBoundsException: length=20; regionStart=0; regionLength=23
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at java.lang.String.substring(String.java:1931)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at org.kontalk.Log.makeTag(Log.java:117)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at org.kontalk.Log.d(Log.java:176)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at org.kontalk.service.msgcenter.MessageCenterService.onStartCommand(MessageCenterService.java:823)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3351)
09-07 15:15:50.502 32341 32341 E AndroidRuntime: 	... 8 more`

**Comment by daniele-athome** [comment]
Sorry, did it in a rush and no time to test it. Should be fixed now, BUT I don't have to test it right :-) sorry

**Comment by daniele-athome** [comment]
By the way, please enclose log output between three backticks instead of one (I fixed your comment above).
