### ISSUE TITLE
Wrong location If I click too fast

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#1072]
### Expected behavior
Correct location should be sendet

### Actual behavior
If I click too fast, a location (sea nearby Roma 😉) will be sendet.

### Steps to reproduce
1. Open a new chat
2. Click paperclip -> position 
3. Imadetliy (as fast as possible) click the blue marker in the left bottom corner (before the text "send current location" is shown) to send the position.

I can reproduce this only with OSM.
Maybe GMaps is faster then me ?!

### Environment

Kontalk version: 4.1.0 beta 2 Google Play version

Android version: 7.0

Device model: Huawei Nova

**Comment by daniele-athome** [comment]
I'm not really sure if this can be seen as a bug. I mean you need time to obtain a location, but you might be content on what it gives you at any moment (e.g. you don't want to wait for the GPS to fix, you are content with an approximate or a previously retrieved location). Am I understanding the issue right?

**Comment by webratte** [comment]
I sendet this location by mistake because I was in hurry.

I think the location nearby Roma is a default location if no current location found.

So I think the button should be deactivated until there is a location found.

I hope you understand what I mean.

**Comment by OffifialMITX** [comment]
Maybe not deactivated but autosent after the location has been obtained?

On September 28, 2017 4:38:21 PM GMT+02:00, webratte <notifications@github.com> wrote:
>I sendet this location by mistake because I was in hurry.
>
>I think the location nearby Roma is a default location if no current
>location found.
>
>So I think the button should be deactivated until there is a location
>found.
>
>I hope you understand what I mean.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/1072#issuecomment-332857153

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
Actually you may send any location, so disabling the button until a location is found isn't really an option (e.g. imagine you're in an uncovered area and no location can be found, even approximate - e.g. no networks of any kind, at all, and you know you're inside a certain building and you want to send that to your contact). Nor sending the location automatically.

**Comment by OffifialMITX** [comment]
But how do you send it if there's no network of any kind?

On October 11, 2017 11:30:47 AM GMT+02:00, Daniele Ricci <notifications@github.com> wrote:
>Actually you may send any location, so disabling the button until a
>location is found isn't really an option (e.g. imagine you're in an
>uncovered area and no location can be found, even approximate - e.g. no
>networks of any kind, at all, and you know you're inside a certain
>building and you want to send that to your contact). Nor sending the
>location automatically.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/1072#issuecomment-335752275

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
You can always queue the message and wait for network to come back. I often do that myself.
