### ISSUE TITLE
Bootloops my phone 

### ISSUE THREAD

**Issue by forkoz** [kontalk/androidclient#1112]
### Expected behavior
App should run like 4.0.4

### Actual behavior
Black screen upon install finished.
Black screen upon bootup.

### Steps to reproduce
1. run AOSP based rom
2. install latest apk
3. cry

### Environment

Kontalk version: 4.0.4 good, latest bad

Android version: 4.4.4 CarbonRom AOSP

Device model: Galaxy S3 CDMA

### Logs

It kills adb too... but there is a bug report on google. This is related to the build tools you are using.

### Other

https://forums.bitfire.at/topic/1603/replicant-lineage-1-9-1-causing-instant-crash-and-bootloops

**Comment by tetris4** [comment]
Unfortunately this is a known issue. Check [here](https://gitlab.com/fdroid/fdroiddata/merge_requests/2618#note_49037179) and the linked [bug report on f-droid](https://gitlab.com/fdroid/fdroiddata/issues/979).

**Comment by forkoz** [comment]
yea, I wish there was an Xposed patch for this because I'm playing russian roulette with these apps.

**Comment by daniele-athome** [comment]
Firmware issue... I'll release a hotfix based on the current master with a workaround. You'll also get [contextual reply](#594) which I was preparing for a next version along with another couple of new features :-)

**Comment by daniele-athome** [comment]
Closed in 3019997144a951f8c2ec0f44be97fc0a2b1a52c7.
