### ISSUE TITLE
Messages are delivered to me only when I open Kontalk

### ISSUE THREAD

**Issue by relan** [kontalk/androidclient#1113]
### Expected behavior
Messages are delivered in background, without the need to open app. They worked this way in 4.0.4.

### Actual behavior
I often get messages (that were sent hours ago) only when I open Kontalk app.

### Steps to reproduce
1. Have someone send me a message.
2. Wait for a couple of hours.

### Environment

Kontalk version: 4.1.1 from F-Droid; I upgraded from 4.0.4, which worked fine.

Android version: AOSP 7.1.2 without Doze support, without Google Apps. Power saving is disabled for Kontalk.

Device model: Nexus 4.

### Logs

I don't have anything like #1107 in logcat, but I get this:

```
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: Connection KontalkConnection[xxx@beta.kontalk.net/xxx] (21) closed with error
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: javax.net.ssl.SSLException: Read error: ssl=0x8848d840: I/O error during system call, Connection reset by peer
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:243)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at java.io.InputStreamReader.read(InputStreamReader.java:184)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at java.io.BufferedReader.read1(BufferedReader.java:221)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at java.io.BufferedReader.read(BufferedReader.java:297)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1516)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:993)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:349)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at org.kontalk.client.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1240)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at org.kontalk.client.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at org.kontalk.client.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
12-06 08:10:24.146 24369 30578 W AbstractXMPPConnection: 	at java.lang.Thread.run(Thread.java:761)
12-06 08:10:24.146 24369 30578 W MessageCenterService: connection closed with error
12-06 08:10:24.146 24369 30578 W MessageCenterService: javax.net.ssl.SSLException: Read error: ssl=0x8848d840: I/O error during system call, Connection reset by peer
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:243)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at java.io.InputStreamReader.read(InputStreamReader.java:184)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at java.io.BufferedReader.read1(BufferedReader.java:221)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at java.io.BufferedReader.read(BufferedReader.java:297)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1516)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:993)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:349)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at org.kontalk.client.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1240)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at org.kontalk.client.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at org.kontalk.client.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
12-06 08:10:24.146 24369 30578 W MessageCenterService: 	at java.lang.Thread.run(Thread.java:761)
12-06 08:10:27.695 24369 23117 E AbstractXMPPConnection: Exception in packet listener
12-06 08:10:27.695 24369 23117 E AbstractXMPPConnection: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.jxmpp.jid.Jid.toString()' on a null object reference
12-06 08:10:27.695 24369 23117 E AbstractXMPPConnection: 	at org.kontalk.service.msgcenter.MessageListener.processStanza(MessageListener.java:189)
12-06 08:10:27.695 24369 23117 E AbstractXMPPConnection: 	at org.jivesoftware.smack.AbstractXMPPConnection$5.run(AbstractXMPPConnection.java:1228)
12-06 08:10:27.695 24369 23117 E AbstractXMPPConnection: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-06 08:10:27.695 24369 23117 E AbstractXMPPConnection: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-06 08:10:27.695 24369 23117 E AbstractXMPPConnection: 	at java.lang.Thread.run(Thread.java:761)
12-06 08:10:27.699 24369 23117 E AbstractXMPPConnection: Exception in packet listener
12-06 08:10:27.699 24369 23117 E AbstractXMPPConnection: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.jxmpp.jid.Jid.toString()' on a null object reference
12-06 08:10:27.699 24369 23117 E AbstractXMPPConnection: 	at org.kontalk.service.msgcenter.MessageListener.processStanza(MessageListener.java:189)
12-06 08:10:27.699 24369 23117 E AbstractXMPPConnection: 	at org.jivesoftware.smack.AbstractXMPPConnection$5.run(AbstractXMPPConnection.java:1228)
12-06 08:10:27.699 24369 23117 E AbstractXMPPConnection: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-06 08:10:27.699 24369 23117 E AbstractXMPPConnection: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-06 08:10:27.699 24369 23117 E AbstractXMPPConnection: 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by duff-y** [comment]
I do experience the same issue. 

Lineage OS 14.1
Android 7.1.2, no Google apps, power saving disabled
Kontalk 4.1.1 via f-droid
Device GT-I9195

Any help is appreciated!

**Comment by duff-y** [comment]
(I don't know how to edit my previous comment.)

Quick addendum: I also experienced this issue with the Kontalk version before (4.1.0?)

**Comment by daniele-athome** [comment]
```
I don't have anything like #1107 in logcat, but I get this:
```

I don't think that is related to this issue, but it could very well be another one (from what I can see, a message without a "from"... I don't know how that can be possible). Can you open another issue and attach (or send to the devteam email) a logcat after activating debug logging please?

About this issue: from what I can understand, at some point Android introduced a more aggressive standby approach, i.e. killing all connections without notifying the app. In a non-Google environment this might be a problem, because the app should keep the CPU awake to remain connected (and this is not acceptable of course because it hugely affects battery usage).
Can you try activating the foreground service? (Kontalk settings > Maintenance > Enable foreground service)

**Comment by tetris4** [comment]
My girlfriend is also affected by this on a phone with Google services. Perhaps it's because she has the habit of clearing memory, that could kill Kontalk? Other messaging applications don't seem to be affected by this though.

**Comment by daniele-athome** [comment]
> Perhaps it's because she has the habit of clearing memory, that could kill Kontalk?

It depends what she's using to do that. Is she using a feature given by the OS or a 3rd party app? What's the device brand and model and Android version?

**Comment by tetris4** [comment]
It's a feature given by the OS. She does it using the 'Delete' icon when she hits the recent apps (running apps?) button. 

This on a Huawei P8 lite 2017, running Android 7.0.

**Comment by daniele-athome** [comment]
Ok, don't do it. I mean it, apps are killed permanently by that button until they are opened again by the user. If other apps work, they are probably whitelisted by the device manufacturer because they are famous.

Also did she whitelisted the app on "protected apps" feature? I remember that Huawei has something called like that.

**Comment by tetris4** [comment]
I will ask her to stop doing it, see if it helps. I will also check for that whitelisting configuration. Sorry if this is unrelated.

**Comment by daniele-athome** [comment]
Yesterday I released 4.1.2 containing some improvements for this issue. I've also configured the server to use a more aggressive approach in detecting stale connections. Let's see how it goes. I'm closing this for now, feel free to reopen it if you still have issues in message delivery. More improvements in the basic version will come in the next release, I don't think this is over.

**Comment by relan** [comment]
> Can you open another issue and attach (or send to the devteam email) a logcat after activating debug logging please?

Since yesterday (after I enabled debug logging) I haven't seen any SSLExceptions. I'll let you know if I notice them again.

> Can you try activating the foreground service?

Looks like it fixed this issue for me.

**Comment by relan** [comment]
> Looks like it fixed this issue for me.

Nope. "Foreground service" does not solve the problem. This morning when I started Kontalk I got a message sent 9 hours ago. I'm still on 4.1.1 though.

**Comment by relan** [comment]
I've been using 4.1.2 for the past 3 weeks and can confirm that issue is fixed. Thank you!

**Comment by daniele-athome** [comment]
Good to know, thank you! 4.1.3 will have other fixes concerning that too (for other users experiencing this issue).

**Comment by relan** [comment]
Looks like after another party upgraded from 4.0.4 to 4.1.2 (from F-Droid too), the problem is back. Today when I opened Kontalk I got a message that was sent 16 hours ago.

**Comment by relan** [comment]
4.1.3 suffers from this issue too. 4.1.3 from F-Droid on both sides.

**Comment by daniele-athome** [comment]
@relan I'll use #1138 to track the issue in the current version.
