### ISSUE TITLE
Wrong sender in contextual reply

### ISSUE THREAD

**Issue by 115ek** [kontalk/androidclient#1118]
### Expected behavior
Alice quotes Bobs text and sends him an answer.
Bobs gets the message where he is mentioned.

### Actual behavior
Bob gets the message, but Alice is quoted/mentioned instead of him.
At Alice's device everything is okay and looks like expected.

### Steps to reproduce
1. quote your chatpartner, send a message
2. look at your chatpartners phone
3. find the error... :smile: 

### Environment

Kontalk version: 4.1.2 basic version, built at home

Android version: 7.1.2 LineageOS

Device model: Xperia Z1 Compact

### other
Am I expecting the wrong thing from contextual reply (#594) ? How should it behave?

**Comment by webratte** [comment]
I think I expect the same thing like you 😀

**Comment by daniele-athome** [comment]
You expected right: it's a bug :-)
Thanks for reporting.
