### ISSUE TITLE
Sharing between Kontalk contacts faild sometimes

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#1123]
### Expected behavior
If I long press a received picture and share it to a Kontalk contact it should be sendet

### Actual behavior
If I try to share a picture (between Kontalk contacts) the receivers chat opens but the picture will not be sendet (sometimes)

### Steps to reproduce
1. Open a chat with a picture inside
2. Long press the thumbnail
3. Choose "share"
4. Choose Kontalk
5. Choose a contact
6. The receivers chat opens and closed immediately  but the picture will not be sendet

If you try it again it works.

This happens not always and so I have not a reliable way to reproduce.
Hopefully the log will help to find out what happens

### Environment

Kontalk version: 4.1.2 Google Play

Android version: 7.0

Device model: Huawei nova

### Logs

I will send the log to your Mail adress

**Comment by daniele-athome** [comment]
Your log shows several image sending. Could you tell me approximately the hour of the failure in the log?
I tried on my device and couldn't reproduce the issue :-(
In the meantime thanks to your log I found another thing to fix (not strictly related to this issue though).

**Comment by webratte** [comment]
I know. I also can't reproduce it every time.
It seems happens by chance. I don't know.

The log is made immediately after the issue happens and the resend works.

The interesting time are the last 3-5 minutes in the log.

**Comment by webratte** [comment]
I have also a log made a few seconds after the "crash" without try to send again.

If you like I can send it to you for better find the time when it was happens.

**Comment by daniele-athome** [comment]
Did you have this issue with recent versions yet? My memories are a bit fuzzy...

**Comment by webratte** [comment]
I can't remember that it was happens again.

Probably you can close this issue.

If it happens again I can reopen it.
And hopefully in this case I will have a log.
