### ISSUE TITLE
Two input fields are displayed on a tablet

### ISSUE THREAD

**Issue by relan** [kontalk/androidclient#1133]
### Expected behavior
Only one field for entering message text.

### Actual behavior
There are two!

### Steps to reproduce
1. Start conversation with somebody.
2. See this:

![screenshot_20180110-221021](https://user-images.githubusercontent.com/8256809/34790997-ab2c4f72-f654-11e7-8138-c72bc1cdea86.png)

### Environment

Kontalk version: 4.1.2 from F-Droid

Android version: AOSP 7.1.2

Device model: HTC Nexus 9

### Other

Not sure whether any logs are needed, the issue should be easily reproducible. Let me know if it's not.

**Comment by daniele-athome** [comment]
Related to #1115. It was fixed a month ago, but a new release hasn't come out yet. Stay tuned, I'm going to release very soon. Sorry for the waiting :-)
