### ISSUE TITLE
Unable to export personal key

### ISSUE THREAD

**Issue by edmundlaugasson** [kontalk/androidclient#1134]
### Expected behavior
Tell us what should happen: kontalk-keys.zip exported containing required keys

### Actual behavior
Cannot save the _kontalk-keys.zip_ nowhere - no phone or smart card inside phone. Even I succeed finally with saving in Google Drive, the file comes with zero size and contains nothing.

### Steps to reproduce
1. install Kontalk in Android
2. choose _Settings -> Maintenance -> Export personal key_
3. try to choose the location to save - after entering password it fails to save either to internal phone storage or sdcard. Finally succeeds in Google Drive but as described before - useless file.

### Environment

Kontalk version: (please also specify origin, e.g. F-Droid or Google Play)
from Google Play, version 4.1.2 (280)

Android version: (please also specify custom ROM name if applicable)

Device model:
Samsung Galaxy S4 using LineageOS 14.1-20180110 (corresponds to Android 7.1.2)

### Logs
Log file has been sent to devteam (at) kontalk.org using the following command:
_adb logcat -d | grep `adb shell ps | grep org.kontalk | cut -c10-15` >kontalk-log.txt_

**Comment by webratte** [comment]
Hi, 
one part (0 kb file) is already fixed.
See also https://github.com/kontalk/androidclient/issues/1111

It waits only for release.

**Comment by edmundlaugasson** [comment]
I see....

**Comment by LinuxArie** [comment]
On my Lenovo Tab 3 Yoga Android 6.0.1 tablet no SD card it’s not possible to export the key.
On my Motorola Moto E 2nd gen Android 6.0 with SD card it’s possible to export the key
Kontalk 4.1.2 (280) Play Store version on both devices
