### ISSUE TITLE
Messages never arrived unless wifi or data connection is changed

### ISSUE THREAD

**Issue by arielenter** [kontalk/androidclient#1138]
### Expected behavior
Message should not take very long to arrive to the destination

### Actual behavior
Messages seem to never arrive unless I change to another wifi network or both ways from wifi to data

### Steps to reproduce
1. Send a message a clock is shown but it's never send
2. Some one send me a message, it never arrives
3. Connecting to a different wifi or from wifi to data or vice versa sends and receives messages

### Environment

Kontalk version: 4.1.2 (280) Both from F-Droid and Google Play

Android version: Both from Replicant 6.0 (Android 6.0.1) and LineogeOS lineage-14.1 (Android 7.1.2)
Device model: i9100 witch is the one that has Replicant and i9300 with LineogeOS

### Long Description

My girlfriend and I are using kontalk from LineogeOS and Replicant respectively, but both phone seem to have the same problem.

For instance, my girlfriend is connected to a wifi network, tries to send a message to me, but the message never seems to get out. A little clock is shown, but even after waiting a couple a minutes the clock is still present. Same wise, when I send her a message she some times never receives it. In the other hand she can send and receive messages from whatsapp while this is happening. I don't seem to find a way to tell weather or not kontalk has a connection or not, the only way I can tell that it has trouble with the connection is that the "last connected" on the contact title you are trying to reach is never display. This happens the same when using data.

The weird part is that I was having similar issues a few days ago but it seem it got better while her got the other way around and got worse. It seems bringing the application up from the background doesn't seem to help. The only way to receive or send messages when they are stuck is to switch from one wifi to another, disable and enable data, or switching from data to wifi and vice versa.

Would a log show what is kontalk doing in this situations where the messages are stuck? should I just use an app like cat log and send the log this display in those moments?

Something I notice is that in my kontalk installation which I installed from f-droid, I can't enable "Push notification" because it says "Push notification support was not included in this version". While hers from google play was enabled by default. I tried disable it on her phone and use the "Reconnect to server" option to the minimum 5 min in both phones hoping it would help but it hasn't.

Thank you for your help. I hope something can be done. For a while I thought that it could be a problem with kontlak's server maybe? I live in Mexico, I'm not sure if distant is an issue. Anyway thanks a lot.

**Comment by arielenter** [comment]
Hello:

By following the instructions here https://github.com/kontalk/androidclient/wiki/How-to-create-a-system-log-(logcat) I made 2 logs. One from when the problem starts before switching networks and another one when I switch networks and the message is finally send then.

I send them to devteam (at) kontalk.org as suggested. Please let me know if there anything else I can do to resolved this problem thank you.

**Comment by arielenter** [comment]
I'm not sure if it's related or not, but sometimes message do get sent, but the receiver takes 10 min to get the message. Please advice me if a new issue should be open for this.

This seem to happen only when the app is running in the background. When I bring it up message arrived, and while both phones have the app on screen, you can exchange conversations without any delays for a while. But then after, when the phone has been idle for while, messages start cumming with a too long delay.

I'm sending a log (to devteam (at) kontalk.org) from both cellphones, where is shown that a message was sent at 8:09 a.m. but the message is not received until 8:20.

This wouldn't be so bad, but sometimes, decisions have to be made fast. I hate to say it but my girlfriend is always comparing it to whatsapp, which really get on my nerves.

I know that kontalk is not trying to be whatsapp, and I shouldn't, but when people think about instant messaging, well, they usually think about 2 min tops.

I just want to understand how is kontalk suppose to work. I have set "Reconnect to server" to 5 min on the settings hoping it will mean that message should take up to 5 minutes tops to arrive, but this doesn't seem to be the case.

I hope you could help me and make me understand what is happening. Thank you.

**Comment by arielenter** [comment]
Kontalk seems to be working fast now. Thank you for all the work done. I'll go make a donation.  Thank you C:

**Comment by webratte** [comment]
Hi, 
if you like to donate what do you think about Liberapay:

https://de.liberapay.com/kontalknet/

This donation will reach Kontalk without deduction.

Goggle and Paypal will deduct a charge.

I did it already 😉

**Comment by arielenter** [comment]
Thanks @webratte I'll check it out C:

**Comment by arielenter** [comment]
Unfortunately, my GF sent me a message yesterday and it took 25 min to arrive on my self phone. From her side the message was sent right away, but my phone didn't get it until then. Also this morning, my GF sent me a message and I didn't receive it until I bring up the kontlak app when she notified me through a text msg 4 min later.

Could this be a problem from the server? could my donations improve the service? thank you.

**Comment by OffifialMITX** [comment]
Maybe settings > network > set "disconnect when idle" to never or at least a lower value would help?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arielenter** [comment]
Thanks for your advice @OffifialMITX . Unfortunately, this setting has been always on "Never", which is the default value. So I don't think that must be it.

I must say that these days, kontalk has been working a lot better, and I've been receiving the messages most of the time right away. Unfortunately, there is still a few times when I don't. I must say that my GF and I don't send each other a lot of messages during the day, when we do is for something important. Now days I'll say that for every 5 messages after idle one of them has a really big delay but the other ones arrive fast.

When I receive the first message after some idle, I can start a conversation without problems. It's after some idle time that the first message has a long delay some times.

Am I the only one experiencing this issue? I'm going to try with the app Conversation, and see if I get the same results.

**Comment by OffifialMITX** [comment]
Hm, have you tried "Settings" > "Maintenance" > "Enable foreground service"? 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
Thanks for reporting! And sorry for the delay. The logs are showing difficulties in connecting to the Kontalk server, and after some attempts the app will give up and wait for the next network change.

I've brought the max number of retries while the app is not in the foreground to 15 and the max number of retries while the screen is off to 10. It should help, but I'd like not to remove this "give-up feature" completely because if you're in a faulty network **it will drain your battery in a very short time**.

I'll close this for now, next release will have this patch included (I have to release soon to address a few other bugs also so expect one soon). Feel free to comment further or open it again.

**Comment by daniele-athome** [comment]
Looking better at some other logs (sorry, processing emails gradually), I can see:

```
Kontalk : suspending network traffic
```

Which is probably just a phone call. The real problem comes later:

```
01-22 08:11:32.093  3319  3319 D MessageCenterService: entering inactive state
01-22 08:11:32.098  3319  8211 D SMACK   : SENT (41): <inactive xmlns='urn:xmpp:csi:0'/><presence id='9ax1B-1092'><show>away</show><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.kontalk.org/' ver='none'/></presence>
```

The phone goes to sleep. A while later:

```
01-22 08:22:10.514  3319  3319 D MessageCenterService: ping message center connection
01-22 08:22:10.524  3319  3319 D MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.PING cmp=org.kontalk/.service.msgcenter.MessageCenterService }
01-22 08:22:10.542  3319  8211 D SMACK   : SENT (41): <iq to='beta.kontalk.net' id='9ax1B-1093' type='get'><ping xmlns='urn:xmpp:ping'/></iq>
01-22 08:22:20.619  3319  8798 V MessageCenterService: ping failed, restarting message center
```

The connection went away because Android terminated all processes during the standby. No matter what I do to prevent this, the only way to keep the connection awake is to keep the CPU awake, and **that will drain a lot of energy**. I'll find a way to handle that without keeping the CPU always awake.

**Comment by arielenter** [comment]
Thank you so much @daniele-athome , very thoughtful thank you.

I feared the log wouldn't show what was going on. I'm glad it did. I'm sending this last log about the matter since yesterday seem to had been the worse and it may reflect better the problem. A message was sent to me yesterday at 10:45 P.M. and it didn't arrived until 12:29 A.M. of today.

@OffifialMITX It seems your suggestion didn't work for me either, but daniele-athome seem to have found the problem already. Thank you.

**Comment by arielenter** [comment]
Thank you so much @daniele-athome . I'll test it right away. Also, I just added a donation liberapay. Thank you C:

**Comment by jhoc2000** [comment]
This is a similar problem with my wife's new Huawei phone.

She has to keep restarting Kontalk 'Settings -> Maintenance -> Restart message center'. Sometimes she'll be able to see new messages and sometimes Kontalk doesn't restart. No matter what, she doesn't get notifications when I send her a Kontalk message.

It may be related to Huawei's "Protected apps" or "auto-launch" settings. We are looking into that now. If it is something like this then this URL may help with the coding:

https://stackoverflow.com/questions/31638986/protected-apps-setting-on-huawei-phones-and-how-to-handle-it

I'll notify this thread if I find something else.

**Comment by webratte** [comment]
Hi,
I also use a Huawei phone.
And I know this problem.

You can fix it (probably) by battery setings. Set Kontalk to "dont close".

And also go phone settings->apps->settings (icon in the bottom)->special access->ignore battery optimazions. There should Kontalk be enabled.

This way it should work.

**Comment by arielenter** [comment]
My wifi and I are now using LineageOS and Replicant respectively. We stop using kontalk but I guess we can give it a shot again. We were using very old devices and their android version got discontinued by the kontlak team.

**Comment by daniele-athome** [comment]
Hey @arielenter how it is going? Did you have the chance to try Kontalk on your new devices?

**Comment by arielenter** [comment]
> Hey @arielenter how it is going? Did you have the chance to try Kontalk on your new devices?

Oh my god @daniele-athome you are such an awesome developer for coming back to me and ask me. Thank you so much.

You know, I'm a little embarrass to say we haven't tried yet, but thanks to your comment I'm very exited  to try once more. We were using conversations until now, but now that my free conversation's account is about to expire, it's the perfect time to give kontalk another go and donate the money I might were going to spend on a conversation's user, to your app instead.

I really like the work you have done with kontalk @daniele-athome and I really hope you the best wishes.

Once we try it I'll let you know how is holding. Thank you.

**Comment by arielenter** [comment]
I'm sorry @daniele-athome , it seems we continue having some issues. Some times message do not show up unless I bring the app up. Other times it works fine.

Any way, we are using version 4.2.0 (410). I'm sending you my device log. Hope it helps.

**Comment by daniele-athome** [comment]
Hey! I've received your log, thank you. But I believe debug mode was not enabled. For some time now a debug log feature has been developed inside the app, without the need for any external tool. You should activate the debug log feature from maintenance preferences; you can then send a log directly from inside the app to the devteam address.

Anyway, all I can see from your log is several connection errors. We can try to diagnose the problem with a debug log, but it might be a connectivity problem of some kind.
Also knowing your current Android version and brand/model would help.

Thanks!

**Comment by daniele-athome** [comment]
Please note that the debug log feature will begin to log *after* it's been activated. So you'll need to use Kontalk for a few hours to collect some data.
