### ISSUE TITLE
Easyer joining to a group if not all members verified yet

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#1140]
### Expected behavior
Easyer joining to a group if not all members verified yet.

### Actual behavior
Currently if members who not have veryified each other get a message "you are not authorised".

I know (just  experienced with a friend) non tech users have problems to understand.

Instead this "error message" this user should redirected to the users which not verified if they already in the contact list.

And if this user is not yet in contact list, maybe there should be a info window which explain this on a "non tech understandable" way.

**Comment by daniele-athome** [comment]
This was eventually merged into #947.
