### ISSUE TITLE
Keyboard overlap the input field if I use contextual reply 

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#1141]
Always the input field is visible.

### Actual behavior
Keyboard overlap the input field if I use contextual reply 

### Steps to reproduce
1. Use contextual reply
2. Write a text longer then 7 lines
3. The keyboard will overlap the last lines

### Environment

Kontalk version: Google play V. 4.1.3

Android version: 7.0

Device model: Huawei nova

**Comment by daniele-athome** [comment]
Thanks for reporting!

**Comment by sabiou** [comment]
Any idea on how to resolve this?

**Comment by daniele-athome** [comment]
I still haven't done any analysis unfortunately. But I'll close it before releasing 4.3.0.

**Comment by sabiou** [comment]
Good @daniele-athome

**Comment by daniele-athome** [comment]
After several hours of analysis and experimentations I couldn't find a proper fix for this, so I used a workaround to counteract this. Sorry, if anyone can find a proper solution is more than welcome.
