### ISSUE TITLE
Crash opening conversation view

### ISSUE THREAD

**Issue by fabrixxm** [kontalk/androidclient#1142]
### Expected behavior
Tapping on a conversation, the conversation view opens 

### Actual behavior
Tapping on a conversation, the app crashes

### Steps to reproduce
1. tap on a conversation

### Environment

Kontalk version: 4.1.3 (290) - F-Droid

Android version: Alien Dalvik on SailfishOS (android 4.1.2 - SDK 16)

Device model: Jolla 1

### Logs

http://www.kirgroup.net/kontalk-4.1.3-crash.log.txt

### Other

The app crash only when opening a conversation with a single contact. Group chat conversation works.

**Comment by fabrixxm** [comment]
Crash only with "iPhone" conversation theme

**Comment by webratte** [comment]
I can confirm that with my 
Huawei nova, 
Android 7 
and Kontalk play store Version 4.1.3

**Comment by fabrixxm** [comment]
No, It's crashing with every theme implemented by "org.kontalk.ui.view.SimpleMessageTheme":
classic, old classic, iphone

**Comment by 115ek** [comment]
I can confirm that on LineageOS 14.1 with basic version 4.1.3 too.
As @fabrixxm already said: crashes with classic, old classic and iphone theme.

**Comment by Spielmops** [comment]
I can confirm that. Chrash happens, if I tap on a conversation. It happend with version 4.1.3 I went back to 4.1.2 and everything was ok. Android 5.1 without Google.

Spielmopd

**Comment by mondstern** [comment]
I can confirm that. Chrash happens, if I tap on a conversation. It happend with version 4.1.3 (290). Android 7.0 with Google.

**Comment by daniele-athome** [comment]
Great report, thanks!
