### ISSUE TITLE
Button-label too long 

### ISSUE THREAD

**Issue by FranBran** [kontalk/androidclient#1150]
I deleted my account and registered again. During the verification-process I got 3 options: transfer account, register another device, and ....

I was unable read the 3. option because the label was too long (even in landscape mode). As these options are placed within a dialog and as button-labels, I am not even able to scroll to read the whole message. I'm using the german translation btw.

**Comment by webratte** [comment]
Hi,
I'm the german translater. Probably it's my fault.
I think it's too late to provide a screenshot!?

I will check if I find a shorter translation.

 Thank you

**Comment by webratte** [comment]
Hi @FranBran
it seems I'm to stupid ;-)

Please can you tell me step by step what you did?
I don't know what I looking for.

Thank you

**Comment by FranBran** [comment]
:) basically i registered an account for a phone-number that was already registered. (although i deleted my account first all.. it seems that my number was still recognized....)

so first step: delete account
second step: register again with same phone-number

then I was given those 3 options (transfer account,...). I'm not sure, whether those 3 options were translated to german by the way!

I hope this info helps!

**Comment by daniele-athome** [comment]
I believe that is my fault: I couldn't find another way to describe that menu item clearly. What do you guys suggest? The item is for transferring an account from another device remotely. It can be also called:

* account copy
* account transfer
* personal key transfer
* whatever you want to call it xD

**Comment by daniele-athome** [comment]
Reading this a second time, I believe I misinterpreted your initial report. If you are talking about a third option in the menu, it's probably outdated because it's been removed in recent versions (it's visible only in debug builds because it can have issues). If I'm mistaken, feel free to reopen the issue.
