### ISSUE TITLE
XEPs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [kontalk/androidclient#1156]
It is possible to have a XEPs support page with version?
https://github.com/kontalk/specs/blob/master/xeps.md

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by webratte** [comment]
Hi,
I could find this:

https://github.com/kontalk/specs/blob/master/xeps.md

It's without versin number. I hope it helps anyway.

**Comment by Neustradamus** [comment]
It is for this that I have created the issue.
With number it is easy to update after, same for RFCs.
I think it is time to check the code for verify if it is the last version, if not, time to update...

**Comment by daniele-athome** [comment]
I've opened kontalk/specs#18. Thanks for reporting.
