### ISSUE TITLE
Bug found on kontalk app

### ISSUE THREAD

**Issue by yhaulez** [kontalk/androidclient#1164]
#### Expected behavior
Kontalk app is an app for messaging which is an open-source project and comes with lots of features like voice recording, attach button for media files and voice calls.     
This app has the attach feature which works well on the audio and video and for the gallery when it is pressed it should take you to your gallery for you to choose the image you want to attach.
#### Actual behavior
But whenever I press the gallery button it keeps taking back to my launcher or back to chats without linking me up with my gallery. 
It keeps misbehaving whenever I press the gallery option to attach an image. 
#### How to reproduce
* Download kontalk app from Google Play Store 
* Register/sign up  on the app
* Try creating a new conversation 
* They try attaching an image 
* It would either crash the app or take you back to the chat page. 
________________
* version of application: 4.1.4
* last updated : March 18 2018
____
* Browser: Google Play Store / kontalk 
* Operating system: Android 7.0

#### Recording Of The Bug
https://youtu.be/c_Ai5DcWurw

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@yhaulez/bug-found-on-kontalk-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by OffifialMITX** [comment]
Have you tried to use the "share via" function from the gallery of your choice? If that works, the problem is most likely with your settings/OS and not Kontalk itself.

On March 29, 2018 12:45:47 PM GMT+02:00, Yhaulez <notifications@github.com> wrote:
>
>#### Expected behavior
>Kontalk app is an app for messaging which is an open-source project and
>comes with lots of features like voice recording, attach button for
>media files and voice calls.     
>This app has the attach feature which works well on the audio and video
>and for the gallery when it is pressed it should take you to your
>gallery for you to choose the image you want to attach.
>#### Actual behavior
>But whenever I press the gallery button it keeps taking back to my
>launcher or back to chats without linking me up with my gallery. 
>It keeps misbehaving whenever I press the gallery option to attach an
>image. 
>#### How to reproduce
>* Download kontalk app from Google Play Store 
>* Register/sign up  on the app
>* Try creating a new conversation 
>* They try attaching an image 
>* It would either crash the app or take you back to the chat page. 
>________________
>* version of application: 4.1.4
>* last updated : March 18 2018
>____
>* Browser: Google Play Store / kontalk 
>* Operating system: Android 7.0
>
>#### Recording Of The Bug
>https://youtu.be/c_Ai5DcWurw
>
><br /><hr/><em>Posted on <a
>href="https://utopian.io/utopian-io/@yhaulez/bug-found-on-kontalk-app">Utopian.io
>-  Rewarding Open Source Contributors</a></em><hr/>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/1164

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
