### ISSUE TITLE
A bug found on kontalk app| app crashes whenever I add an emoji to my status. 

### ISSUE THREAD

**Issue by yhaulez** [kontalk/androidclient#1165]
#### Expected behavior
Kontalk app is a messenger for android phones and it's an open-source project. It has lots of cool features like voice recording, attach button and voice calls.    
As other messenging app you could have your own status (profile status) .

 You can create a new status and on that status you could add emoji and symbols too not just text.

#### Actual behavior
I have been using the project for a while and it's been working smoothly but on this new 
 version of the app whenever I try adding emoji to my status the app keep crashing taking me back to my home screen or back to my profile.  It keeps misbehaving whenever I want to add an emoji to my status by taking me back to my launcher home.
#### How to reproduce
* Download kontalk app from Google Play Store
* Register on the app
* Try creating a new status 
* Try adding an emoji to your status 
* It keeps crashing and fluctuating without adding the emoji to your status. 
___
Version of app: 4.1.4
Last updated: March 18 2018
___
* Browser:  Google Play Store / kontalk 
* Operating system: Android 7.0

#### Recording Of The Bug
https://youtu.be/MHlHEAnJ8Pg

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@yhaulez/a-bug-found-on-kontalk-app-or-app-crashes-whenever-i-add-an-emoji-to-my-status">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by OffifialMITX** [comment]
Wait, "this new version"? Does that mean it was possible before?

On March 29, 2018 10:36:30 PM GMT+02:00, Yhaulez <notifications@github.com> wrote:
>
>#### Expected behavior
>Kontalk app is a messenger for android phones and it's an open-source
>project. It has lots of cool features like voice recording, attach
>button and voice calls.    
>As other messenging app you could have your own status (profile status)
>.
>
>You can create a new status and on that status you could add emoji and
>symbols too not just text.
>
>#### Actual behavior
>I have been using the project for a while and it's been working
>smoothly but on this new 
>version of the app whenever I try adding emoji to my status the app
>keep crashing taking me back to my home screen or back to my profile. 
>It keeps misbehaving whenever I want to add an emoji to my status by
>taking me back to my launcher home.
>#### How to reproduce
>* Download kontalk app from Google Play Store
>* Register on the app
>* Try creating a new status 
>* Try adding an emoji to your status 
>* It keeps crashing and fluctuating without adding the emoji to your
>status. 
>___
>Version of app: 4.1.4
>Last updated: March 18 2018
>___
>* Browser:  Google Play Store / kontalk 
>* Operating system: Android 7.0
>
>#### Recording Of The Bug
>https://youtu.be/MHlHEAnJ8Pg
>
><br /><hr/><em>Posted on <a
>href="https://utopian.io/utopian-io/@yhaulez/a-bug-found-on-kontalk-app-or-app-crashes-whenever-i-add-an-emoji-to-my-status">Utopian.io
>-  Rewarding Open Source Contributors</a></em><hr/>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/1165

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
