### ISSUE TITLE
Notification LED not working properly

### ISSUE THREAD

**Issue by 115ek** [kontalk/androidclient#1227]
### Expected behavior
Notification LED should light up in the desired colour.

### Actual behavior
Notification LED lights up only in one colour or not at all.

### Steps to reproduce
1. Set LED notification colour
2. get test message
3. check colour of LED

### Environment

Kontalk version: F-Droid 4.2.0 (410)

Android version: 8.1.0 and 6.0

Device model: Sony Z1 Compact, Huawei P8 lite

### Logs

couldn't get any useful log until now.

### Other

behavior Z1 Compact: LED blinks green, no matter what setting was chosen. 
behavior P8 lite: Setting Orange and Red results in red blinking LED, Blue, Purple and Green result in no light showing up at all.

**Comment by daniele-athome** [comment]
Thanks for reporting. LED behaviour is highly depending on the device. Could you try another app and/or a diagnostic app to test the actual color?

**Comment by 115ek** [comment]
Checked that with [https://play.google.com/store/apps/details?id=com.rageconsulting.android.lightflowlite](https://play.google.com/store/apps/details?id=com.rageconsulting.android.lightflowlite) and RGB LED on Z1 Compact is working fine in all colours. P8 lite doesn't work with that app. Using [https://play.google.com/store/apps/details?id=com.coolbeans.ledtester](https://play.google.com/store/apps/details?id=com.coolbeans.ledtester) brings to LED to shine in all colours on P8lite.
And before it worked with Kontalk on both devices, too.
Is it a Kontalk problem? Anyone else having issues with that?

**Comment by daniele-athome** [comment]
I've tried to fix it, but I have no device (or emulated way) to try it. I've been publishing some alphas through the Google Play alpha channel, if you're on it, I'll publish one in a couple of days.

**Comment by 115ek** [comment]
Hey. I've tested your latest changes with my Xperia Z1 compact with LineageOS 16 (Pie).
It doesn't change anything, but I've got colours of my choice by using the system settings (see my screenshot therefor). Maybe it's a lineage feature you won't find in standard AOSP - not quite sure about that.
![Screenshot_20190424-135147_LineageOS_Settings](https://user-images.githubusercontent.com/11771774/56658326-a4f49580-669a-11e9-83aa-29c204d04c8a.png)
It seems the Kontalk-intern settings of the LED colour doesn't have an influence.
Apart from that other apps like Signal or Telegram also allow setting the colour of the notification LED.
I couldn't test if changing the colour works for them so far. But maybe you can have a look at their code concerning LED stuff.
I'll keep you up-to-date.

**Comment by 115ek** [comment]
Signal notification LED works fine in desired colours. I had a look at [https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/notifications/AbstractNotificationBuilder.java](url)
`setLed()` Is setting up the colour / blink frequency. I've got an idea and test it. I will create a PR when it's successful.

**Comment by 115ek** [comment]
[setLights](https://developer.android.com/reference/android/app/Notification.Builder.html#setLights(int,%20int,%20int)) is deprecated with API 26. We have to use enableLights and setLightColor during NotificationChannel setup instead.
