### ISSUE TITLE
Audio message normalization

### ISSUE THREAD

**Issue by LLoewe02** [kontalk/androidclient#1245]
### Actual behavior
The volume of audio messages is usually pretty low. Audio messages should be normalized.

**Comment by daniele-athome** [comment]
I don't think that's an audio file problem... more of a mix of vicinity to the mic, environment, microphone (as in hardware)... anyway what's the reference for a "normal" volume?
And remember that trying to turn the volume up to a naturally coming low sound will create distorsions.

**Comment by LLoewe02** [comment]
Hi Daniele,

compared to Signal the Audio volume of Audio messages is always really low. This problem doesn't only appear to my phone. Right now I only hear something if I set the phone to the maximum loudness and I have to hold the phone next to my ear to hear anything. It's not a huge problem, but an option in the settings to rize the gain in the audio files would be nice.

Here a wikipedia description about Audio normalization:
https://en.m.wikipedia.org/wiki/Audio_normalization
