### ISSUE TITLE
No SMS send to Iran (+98) users.

### ISSUE THREAD

**Issue by ali-hardan** [kontalk/androidclient#1246]
I have tried multiple times to receive activation SMS, but It don't send and keep me in waiting screen. I think that because it can't send SMS to Iran (+98)

### Environment

Kontalk version: 4.2.0 F-Droid

Android version: 7.0

Device model: Samsung Galaxy J5 Prime

**Comment by daniele-athome** [comment]
Did you try also the fallback method? There is a button in the verification code input screen where you can try another method that might work (it tries calling you and/or another SMS provider on our part with greater chance of success).
In the meantime, could you send us your phone number to devteam@kontalk.org so we can better analyze your issue.

**Comment by daniele-athome** [comment]
> But when I use a VPN which hosted out of Iran, it works and call to Iran. Now I registered.

Weird... does it mean Kontalk is blocked in Iran? Does it work *after* registering? I mean without a VPN.

**Comment by ali-hardan** [comment]
It doesn't work after registering without VPN.

I do not think that Kontalk has been blocked in Iran, this could be due to sanctions imposed on Iran. Also it may be due to a mistake in blocking websites.

When I try to open https://jmp.ch/ in my browser (without VPN), I encounter with `ERR_CERT_AUTHORITY_INVALID` error and I can't browse it. of course when I use `http` instead `https` I can browse it. Using VPN, no problem.

**Comment by daniele-athome** [comment]
> It doesn't work without VPN after registering.

I'm sorry but I really can't control this... until there are more servers, there is just 1 for now.

> When I try to open https://jmp.ch/ in my browser

What's jmp.ch? You mean https://jmp.chat/ maybe?
Anyway your device doesn't contact it directly, it always passes through a Kontalk server.
