### ISSUE TITLE
Battery power consumed with push notifications disabled

### ISSUE THREAD

**Issue by forkoz** [kontalk/androidclient#1247]
Running android 7.1.2 kontalk is churning up my battery in a matter of hours. The phone won't sleep and ends up using 10% or more an hour even with a giant extended battery.

I tried using autoruns and receiverstop to disable the "on boot" and connectivity changed receivers. I tried stopping the service. Even set the disable run in background permission. Unfortunately every time I open it, kontalk re-enables the recievers and continues to run in the background despite not having root. The only thing I can do is force stop it and then the disabled portions stay until I run it again.

I'm not using push notifications and it is supposed to be checking for messages once every 1/2 hour, not constantly holding a partial wakelock.

**Comment by daniele-athome** [comment]
> I'm not using push notifications and it is supposed to be checking for messages once every 1/2 hour, not constantly holding a partial wakelock.

Thanks for reporting. It shouldn't. I'll investigate.

**Comment by daniele-athome** [comment]
In the meantime, a log would be a great help.

**Comment by forkoz** [comment]
I updated the server list and it stopped draining me. Still doesn't respect being disabled.

**Comment by daniele-athome** [comment]
What settings do you have in Kontalk > Settings > Network? Like Disconnect when idle for example (I know you should have Reconnect to server set to 30 minutes right?)

**Comment by forkoz** [comment]
Yes, I left on defaults.

**Comment by daniele-athome** [comment]
Issue should be fixed in 4.3.0 (to be released in a few days). Feel free to reopen if it happens again.
