### ISSUE TITLE
OpenStreetMap static map no longer works

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#1251]
### Expected behavior
Show preview of the sendet location

### Actual behavior
Shows only a error message

### Steps to reproduce
1. Use OSM as map provider (choose it in settings ->location)
2. Send a location
3. See the errormessage (see also the attached screenshot)

### Environment

Kontalk version: 4.2.0 google play

Android version: 7.0

Device model: Huawei nova

![img_20190210_204323](https://user-images.githubusercontent.com/6864851/52538689-d89b7100-2d75-11e9-9dc7-1027b6cebc1b.png)

**Comment by daniele-athome** [comment]
Holy cow OSM has broken :D
Sorry for the delay.

**Comment by daniele-athome** [comment]
I can see also dynamic map is broken as well.

**Comment by daniele-athome** [comment]
I fixed it by upgrading AnyMaps here and there and by setting a custom user agent for tile requests. The fork is living here: https://github.com/kontalk/AnyMaps

Closed by 0201755add2f1b39064ced5e7bdd14b25c23fa33
