### ISSUE TITLE
Weblate registration is not working

### ISSUE THREAD

**Issue by welaq** [kontalk/androidclient#1252]
### Expected behavior
I should get registration link.

### Actual behavior
I don't get no email.

### Steps to reproduce
1. Go to translate.kontalk.org
2. Try to register as a new user
3. Wait for the email with link

### Other
When I try to contact via Weblate form this is what I get.
![paveikslas](https://user-images.githubusercontent.com/28876465/52644723-06a0c280-2ee8-11e9-9d6c-0b0b969f1815.png)

**Comment by daniele-athome** [comment]
Thanks for reporting and sorry for the delay! It should be fixed now.
