### ISSUE TITLE
Emoji keybord don't work

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#1267]
### Expected behavior
Tap on the emoji icon next to the input field should open the emoji table

### Actual behavior
The emoji table don't open.

### Environment

Kontalk version: 4.3.0 Google Play

### Other

Sorry, I can't say what Device not even what Android version is used.
The user which has this problem is not that young boy (if you know what I mean 😉).
And he lives 600 km from me, so I can't take a look on his phone.

Maybe some other will have the same issue.

You worked on the input field. Maybe there is something wrong?

Sorry for this less informations.

**Comment by daniele-athome** [comment]
That's a bit vague :-)
I did work a little on the composer bar, yes, but it was a minor fix and I've also upgraded the Emoji library to the latest version.
I don't have a way to reproduce it, is there a way to obtain at least device model and Android version?

**Comment by webratte** [comment]
Yes I know 😉

I will do my best to find out as much as possible. 
This will become really hard work...

**Comment by webratte** [comment]
I could find out a little bit.

The phone is a ALCATEL ONE Touch 60300

And the Android Version is (probably) 4.1

But I'm absolutely not sure.
Sorry.

**Comment by phirz** [comment]
I know of two other users experiencing the same problem:
Tapping on the emoji symbol next to the input field changes it to the keyboard symbol but has no other effects. The keyboard remains as it is and no emojis are shown. Tapping again changes back to emoji symbol.

**Environments:**
Android 4.4.2 on GT-I9301I with Kontalk 4.3.1 installed from F-Droid
Android 4.4.4 on SM-J100H with Kontalk 4.3.1 installed from Google Play
