### ISSUE TITLE
Permission check returns false even if permission was granted

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1277]
Happening on a Moto Z Play with Android 8.0. All permissions were granted, however when the app runs `Permissions.canRecordAudio`, it returns false. Check which one of the 3 permissions is making it to return false.

**Comment by daniele-athome** [comment]
User had granted (how?) only read but not write:

```
2019-10-01 20:48:20 D/PERMISSIONS: hasPermission(RECORD_AUDIO)=true
2019-10-01 20:48:20 D/PERMISSIONS: hasPermission(READ_EXTERNAL_STORAGE)=true
2019-10-01 20:48:20 D/PERMISSIONS: hasPermission(WRITE_EXTERNAL_STORAGE)=false
```

**Comment by wowhhh** [comment]
I think If just request READ_EXTERNAL_STORAGE  permission in the code , Maybe the reason about this bug is Android 8 Behavior Changes:
> Permissions
> Prior to Android 8.0 (API level 26), if an app requested a permission at runtime and the permission was granted, the system also incorrectly granted the app the rest of the permissions that belonged to the same permission group, and that were registered in the manifest.
> 
> For apps targeting Android 8.0, this behavior has been corrected. The app is granted only the permissions it has explicitly requested. However, once the user grants a permission to the app, all subsequent requests for permissions in that permission group are automatically granted.
> 
> For example, suppose an app lists both READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE in its manifest. The app requests READ_EXTERNAL_STORAGE and the user grants it. If the app targets API level 25 or lower, the system also grants WRITE_EXTERNAL_STORAGE at the same time, because it belongs to the same STORAGE permission group and is also registered in the manifest. If the app targets Android 8.0 (API level 26), the system grants only READ_EXTERNAL_STORAGE at that time; however, if the app later requests WRITE_EXTERNAL_STORAGE, the system immediately grants that privilege without prompting the user.

https://developer.android.com/about/versions/oreo/android-8.0-changes#rmp
