### ISSUE TITLE
Not able to register

### ISSUE THREAD

**Issue by romjean** [kontalk/androidclient#1280]
### Actual behavior
After entering the code received by SMS or call, the app is stuck, nothing happens. I receive 1 or 2 calls indicating the code to enter to register, but then nothing happens on the screen. I tried to enable all permissions, but it didn't change anything. It doesn't work even on a WiFi or a data (4G) internet connection.

### Steps to reproduce
1. Open the Kontalk Android App
2. Enter phone number
3. Enter code received by SMS or call

### Environment

Kontalk version: 4.3.1 (latest) from F-Droid

Android version: 7.1.1

Device model: Samsung J 2016 (SM-J510FN)

**Comment by OffifialMITX** [comment]
Same here on my Moto E⁴ Plus with Stock 7.1.1

**Comment by daniele-athome** [comment]
Thanks for reporting. Could you enable debug log in preferences, try again and send the debug log to devteam (at) kontalk.org please? I'll investigate in the server logs in the meantime.

**Comment by romjean** [comment]
Without doing anything now it works...
