### ISSUE TITLE
bad (invalid signature) in group 

### ISSUE THREAD

**Issue by jhoc2000** [kontalk/androidclient#1284]
### Expected behavior
A member of a group changes his or her phone, registers, asks a group owner to re-add them to a group, all's well. 

### Actual behavior
As the owner of a group I received a Kontalk message from a previous member to re-add them to the ground because they changed their phone. I delete the user from the group and then add them to the group. The user can now receive and send messages to the group but their messages indicate "bad (invalid signature)" in the details of his or her messages. 

### Steps to reproduce
1. Add group members to a group. 
2. Test all is well with all members spending and receiving messages. 
3. Have one member change phone and have to reregister with same name. 
4. Member asks to be re-added to the group. 
5. Group owner deletes and adds the member. 
6. Re-added member sends and receives messages but owner sees the messages as "bad (invalid signature). 

### Environment

Kontalk version: (please also specify origin, e.g. F-Droid or Google Play)
F-Droid Kontalk version 4.3.1 (440)
Android version: 10 QKQ1. 190828.002
MIUI Global 11.04
Device model: Xiaomi Pocophone F1 

### Logs

If you have a system log related to the issue please send it via email at
devteam (at) kontalk.org. Please do not attach it or publish it anywhere because
it may contain sensitive information. If you have root access, you can use Catlog
(available on both Google Play and F-Droid) to produce it. Alternatively, if you
have the Android SDK installed on your computer, connect your device and execute:

```
adb logcat -d | grep `adb shell ps | grep org.kontalk | cut -c10-15` >kontalk-log.txt
```

and send us the text file.

### Other

If there is a relevant forum discussion, please link to it here.

**Comment by daniele-athome** [comment]
Thanks for reporting. In the group information screen what verification status do you read for this re-added user? (the icon next to his/her name, the description can be read by clicking on the name, a dialog will appear)

**Comment by jhoc2000** [comment]
I don't know because I have accepted that user a second time after finding a red mark next to that user's name. Previously, after deleting and re-adding that user to the goup, I had accepted him. I don't know why I had to re-accept that user a second time but now his messages are showing "Security: good". Could there be some sort of delay in accepting a user to a group or is it supposed to take two attempts? Anyway, the problem is now fixed.

**Comment by daniele-athome** [comment]
It shouldn't require a second time. It does only if the user changes once more. Glad it's been fixed anyway. If you are willing to try and reproduce the bug feel free to reopen the issue - I've tried myself but couldn't reproduce it.
