### ISSUE TITLE
Not enough room to see composed message 

### ISSUE THREAD

**Issue by jhoc2000** [kontalk/androidclient#1285]
### Expected behavior
As one composes a message one should be able to see the message scroll up to fill the screen. 

### Actual behavior
There's only a small area (four lines) that one can see of one's composition. It's very annoying because one has to scroll up and down to see what one has typed. 

It would be better if one could see the whole composition above the onscreen keyboard and if one wants to see the messages to which one is replying then continue scrolling above the current composition. 

### Steps to reproduce
1. Compose a long message. 
2. One only sees a small component of the message. 
3. Very annoying because one has only a very small area in which to scroll up and down to read one's composition. 

### Environment

Kontalk version: F-Droid 
Kontalk version 4.3.1 (440)
Android 10 QKQ1.190828.002

MIUI Global 11.04

Device model: Xiaomi Pocophone F1

**Comment by jhoc2000** [comment]
This is also happening with:
Android version: 9
Distribution: LineageOS 16.0-20200223-NIGHTLY-Beryllium

**Comment by daniele-athome** [comment]
I have to reject this, sorry. In the past Kontalk used to have a text area that could be enlarged until covering the whole screen, which meant also covering the chat history. We decided to limit the number of displayed lines as a compromise to allow reading the chat history while writing.
Also Kontalk is an instant messaging system designed to write short messages. I know this might be debatable, but really it's not if you think about the definition (and scope and purpose) of IM.
