### ISSUE TITLE
Not usiing Network DNS

### ISSUE THREAD

**Issue by the-rizla** [kontalk/androidclient#1295]
### Expected behavior
Kontalk app should use the default DNS of the network.

### Actual behavior
The Kontalk app does not connect to the server, if DNS lookup except through the server is blocked by router settings. It makes it one DNS lookup in contrast to all other installed apps.

### Steps to reproduce
1. Enable DNS lookup on your networks DNS server
2. Block other DNS connections than through the default DNS server of the network.
3.Try to send a message in Kontalk.
4. Message will not be send and no messaged are received.

### Environment

Kontalk version: F-Droid

Android version: Lineage OS 16, Android 9

Device model: Samsung Galaxy S4 mini, Nokia 4.2

**Comment by daniele-athome** [comment]
Thanks for reporting. This has been fixed by d0b00bf1e015121144f2fa1e88f310e621d76876. Unfortunately it hasn't been released yet on F-Droid. Version 4.4.0 is currently on beta on Google Play and hopefully will see the light of day before the quarantine ends :-)
