### ISSUE TITLE
Tablet UI issues

### ISSUE THREAD

**Issue by geileszeuch** [kontalk/androidclient#149]
On a tablet if you chat with somebody within the app (chat window did not open from notification. Those two are different!!!) then the screen is seperated. On the left side are the contacts/threads and on the right side the chat window. The chat window shows the avatar of the receiver in every message of him on the left side, but this avatar is also visible on every message of the sender (so a message from me) on the right side.

There shouldn't be any avatar on my messages or maybe my own avatar, but not the avatar of the receiver.

If the chat window was not opened by a notification then there is no online status of the oppenents. If the chat window was opened by a notification then we do have this online status, which is more convenient.

**Comment by daniele-athome** [comment]
Reproduced with in emulator using a very long string (ellipsis doesn't seem to work).
