### ISSUE TITLE
Integrate Crashlitycs

### ISSUE THREAD

**Issue by acappelli** [kontalk/androidclient#187]
Integrate Crashlytics into the app.

**Comment by TheLastProject** [comment]
I just learned about [ACRA](http://www.acra.ch/) on [GitHub](https://github.com/ACRA/acra). The GitHub README seems a bit outdated (the site says Google Docs is no longer supported), but it may be worth taking a look at it.

**Comment by TheLastProject** [comment]
The dialog way seems a perfect way to implement this without getting an F-Droid antifeature flag because you ask permission: https://github.com/ACRA/acra/wiki/AdvancedUsage#dialog.

**Comment by daniele-athome** [comment]
Thanks @TheLastProject, I'll keep an eye on that library.

**Comment by TheLastProject** [comment]
Just a small update on this issue, F-Droid has been using ACRA happily themselves for several months now, so it seems to be a usable library.
