### ISSUE TITLE
Credits section

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#199]
Credits fragment with list of contributors (including translators).

* core devteam
* code contributors (are there? Outside of the devteam itself)
* translators (all of them? Or link to Transifex?)
* links (project and network websites, source code, issue tracker, blog)
* ...

Some of the above should be or are already in the About section.

**Comment by TheLastProject** [comment]
I would keep it simple:
```
Kontalk is developed by <list of core devteam> and various contributors.
```

If you want to list other contributors, you could link to https://github.com/kontalk/androidclient/network/members, but that page is not mobile friendly. Another solution would be to run
`git log | grep Author: | sort | uniq | cut -c 9-`, which will give their commit names and e-mail address. You could possibly make this part of your release flow: Add the output of that command to the "contributor" list before each new release. With Weblate, this would also contain translaters, I believe.

Then, you could show some text like:
```
Kontalk is mainly developed by <list of core devteam>.

Our full list of contributers is as follows:
<output of git log command>
```

In this case, you could maybe add a GitHub link too, to make people want to contribute to be in the list.

**Comment by daniele-athome** [comment]
@TheLastProject thanks for the suggestion! Neat trick the one with git :-) I'll take notes.

**Comment by webratte** [comment]
I think if you show every string (name,mailadress) strictly in the middle it looks nicer (not so "very ugly" ;-)
Currently every first letter is in one row.

**Comment by TheLastProject** [comment]
[You also missed a translator ;)](https://translate.kontalk.org/user/sylvielorxu/)

**Comment by daniele-athome** [comment]
Sorry @TheLastProject, you were the last to include a translation so your name didn't got through when I ran `git log`.

**Comment by TheLastProject** [comment]
No need to apologize, I was indeed very late. I kept waiting for the certificate to be accepted in Firefox, but it never changed, so I ended up adding an exception for the translate subdomain. Cool to hear you using the git log trick :)

**Comment by daniele-athome** [comment]
Well I used CACert, did you include their CA certs in Firefox?

**Comment by TheLastProject** [comment]
I haven't, seems they're not included by default in Trisquel. Good to know. I'm leaving the exception now anyway, it just works

On 16 June 2015 22:58:42 CEST, Daniele Ricci <notifications@github.com> wrote:
>Well I used CACert, did you include their CA certs in Firefox?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/199#issuecomment-112568127

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
