### ISSUE TITLE
Audiorecording crash after orientation change

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#238]
Kontalkversion 3.0 beta3 (36)
Androidversion 2.3.6

Steps to reproduce:
-choose Attachment Audio
-start record
-turn phone from portrait to landscape
       -the recordwindow disappears
-choose Attatchment Audio again
       -the recordwindow appears
-start record again
       -errormessage: "Error starting audio recording."

**Comment by webratte** [comment]
Issue seems not completely fixed in Kontalk Kontalkversion 3.0 beta4.

The crash is fixed but after orientation change, while recording, the recordwindow dissapears.
Then I have to start the record again.

**Comment by daniele-athome** [comment]
Thanks for reporting. This is a change introduced in aea5715b8e2dd20c0dd5a6365caee1c87ff0ba3e because the previous fix had some side effects. I've opened #261 for the next fix.
