### ISSUE TITLE
Blocked user should be marked as blocked

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#239]
Blocked user should be marked as blocked in contactlist and maybe in headline of the chat.
Current testet Version 3.0 beta3

**Comment by daniele-athome** [comment]
This is blocked by blocking command not being implemented yet on Tigase.

**Comment by webratte** [comment]
What Do you think about a button "show/hide blocked users"
Maybe in settings.

So you could keep clean your contactlist.

**Comment by daniele-athome** [comment]
@webratte good idea. Please open an issue for that. In general, don't hesitate to request a feature by opening an issue here.
