### ISSUE TITLE
Slow message delivering

### ISSUE THREAD

**Issue by jluttine** [kontalk/androidclient#249]
Is there something wrong with Kontalk client or the network because messages take several minutes to deliver? Not really instant messaging.. Can it be fixed somehow or is it a property of the whole system?

**Comment by daniele-athome** [comment]
That can depend on a very large number of reasons. First of all, what version of Kontalk and Android are you using? Do you have Play Store services installed?

**Comment by jluttine** [comment]
My phone uses Cyanogenmod & F-droid. The other phone uses Android 4.3 & Play Store. Both use Kontalk 3.0 available from F-droid.

**Comment by daniele-athome** [comment]
Which one is the phone receiving late messages?

**Comment by jluttine** [comment]
Actually, it seems that messages go instantly when chatting. But if we haven't been chatting for a while, at least the android phone receives the first message after several minutes (and then receives all messages at the same time if I have sent several messages). Maybe some kind of disconnection and re-connection or something?

**Comment by jluttine** [comment]
Could the phone be connected to a server without push notification support? Maybe I should set it to never disconnect? Would that drain the battery fast?

**Comment by daniele-athome** [comment]
Probably some problems with push notifications. In the Android phone, go to Kontalk settings (ensure you're connected first by sending a test message to someone) and try to uncheck "Push notifications" and re-check it after 10-15 seconds. Then wait a few minutes out of the app and try again.

**Comment by daniele-athome** [comment]
The phone without Play Store should have that issue, you said it's the one with Play Store, which indeed disconnects and waits for a push notification to save energy. You could set it to be always connected but it will cost you energy.

**Comment by jluttine** [comment]
I can't uncheck push notifications because the option is disabled (but checked) - on both phones.

**Comment by jluttine** [comment]
I don't know whether the push notifications work for the other phone, I haven't checked. But at least for the android phone I have experienced this problem. But it could be the same problem for both. Maybe this "never disconnect" solves it..

**Comment by svrnwnsch** [comment]
I am having the same problem when I switch between WLAN and mobile network. Both phones are using the f-droid version.

**Comment by daniele-athome** [comment]
@jluttine ok that's assessed: Kontalk from F-Droid was built without push notifications support (because of F-Droid policy).
So, this behaviour is normal because Kontalk disconnects after some time ("Disconnect when idle" setting) to save energy and network traffic, and it reconnects again after some time ("Reconnect to server" setting), unless push notifications are available (push notifications will trigger Kontalk startup in background to check for new messages). That's why you receive late messages.

You can fix this in two ways:

* by having push notifications working (see above about play store services)
* set disconnect when idle at "Never"

@svrnwnsch by using Kontalk from F-Droid you have the same issue.

**Comment by jluttine** [comment]
Thanks for the information! Do you have any idea how Telegram works? It is available in F-droid, it is a similar application, and I don't have issues with it. I wonder whether it uses some kind of push notifications or is it always connected..

Do you know why push notifications are disabled in f-droid version? What is it in push notifications that is against f-droid policy?

**Comment by daniele-athome** [comment]
I don't know how it works actually. I will look into it.

Push notifications are disabled because it's a non-free service with non-open source code provided by Google.
