### ISSUE TITLE
crash on verification code

### ISSUE THREAD

**Issue by amir-b7** [kontalk/androidclient#251]
When you enter verification code in LG G2 kontalk crashes.

**Comment by daniele-athome** [comment]
Thanks for reporting. It might be related to another known issue, but without some context or (better) a log report it's impossible to asses what happened.
First of all, which version of Kontalk are you using and on what Android version?

**Comment by amir-b7** [comment]
version 3 beta 3 on android 4.4.2

**Comment by daniele-athome** [comment]
Thanks, please send us a logcat via email.

**Comment by amir-b7** [comment]
How can I do that?

**Comment by daniele-athome** [comment]
If you have root access on your device, you can use the send by e-mail feature [Catlog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat).
Otherwise you'll need a USB cable and the Android SDK.

Some reference here: http://forum.xda-developers.com/showthread.php?t=1726238

**Comment by daniele-athome** [comment]
Also, please try beta4 first (released yesterday).

**Comment by amir-b7** [comment]
I tried this(beta 4).don't working.

**Comment by daniele-athome** [comment]
Ok please proceed with the logcat. Note that you need to try and reproduce the crash and **soon after that** send generate the system log.

**Comment by daniele-athome** [comment]
Hey @amir-b7 any news on that logcat?

**Comment by daniele-athome** [comment]
No response from reporter. Closing for now.
