### ISSUE TITLE
Sending does not always work

### ISSUE THREAD

**Issue by svrnwnsch** [kontalk/androidclient#253]
Sometimes messages take very long to get send. Restarting the Messsagecenter helps.
This problem seems to occure when switching from mobile network to wlan. I do have a internet connection but maybe kontalk things the connection failed and does not try to send via wlan.
Kontalk should try more often to send the message then waiting up to 5h. 

I am using kontalk 3b3 from f-droid.

**Comment by daniele-athome** [comment]
By "send" do you mean sending (clock icon) or delivery (double-tick icon)?
The first case is fixed in beta4 hopefully going out later today.
The latter case is more complicated.

**Comment by svrnwnsch** [comment]
I am meaning sending, I will check out beta4 and reopen the ticket if this is still a issue for me.
