### ISSUE TITLE
No public Key were found.

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#257]
Kontalkversion 3.0 beta4 (37)
Androidversion 2.3.6

I test with myself (sender=receiver)

Steps to reproduce:

-Open new conversation
-send text message

This errormessage will shown:
"Unable to find a public key for this user. Try refreshing your contact list or disable encryption from settings to send message anyway."

-try to send picture or audio

This errormessage will shown:
"Attachment upload failed"

-unencrypted messages will be sent.

I have tried with refresh the contactlist and also with a new created keypair.
 Without success.

I will send a logcat via E-mail.

**Comment by daniele-athome** [comment]
Thanks for reporting. This is actually a Tigase issue which doesn't allow self-subscription (so you don't receive the public key and you can't encrypt messages to yourself). We will handle this on the server, so I will close this.
