### ISSUE TITLE
Beta4 not public keys (not even of myself)

### ISSUE THREAD

**Issue by andreasspeck** [kontalk/androidclient#262]
Updated to beta4 via F-Droid, and re-registered. Now my Kontalk does not find the public key, even of myself, so it is not even able to send an encrypted message to itself.
I recreated the keys, but the same - it doesn't find it's own public keys when trying to send a message to my own number (or it least it shows it to me as self-contact - might be my other Kontalk on my other phone, which I also updated to beta4).
Also, on one of my phones, it only shows one contact (myself - it shows it with the number of the same phone, but I have all phone numbers in the same contact in my address book, so possibly it gets confused). This phone runs Cyanogenmod-10.
The other phone runs Android-4.0.1, and it shows me the contact of myself from the first phone, but also says that it can't find the public key.
Sending of unencrypted messages between the two phones also does not work.

In addition, on both phones Kontalk is not able to download the server list. 

Right now, it makes the impression of being completely broken and unusable.

**Comment by andreasspeck** [comment]
I uninstalled and reinstalled Kontalk-beta4 on the Android-4.0.1 phone, and now the two phones can communicate. So possibly something went wrong with the update?

**Comment by daniele-athome** [comment]
Hello, thanks for reporting. This is probably due to something gone wrong with the update (being a beta-to-beta upgrade we didn't make it very bulletproof).

The encrypted-messages-to-yourself is a known problem, we are already working on it (it's a server-side problem actually).

Sending unencrypted messages should work... do you get at least a single tick or it stays with the pending (clock) icon forever?

**Comment by andreasspeck** [comment]
Yes, I can send an unencrypted message to myself. In the case of trying to send encrypted, it will stay unsent (pending clock), as it can't find the public keys of myself. I don't think it is really important - it might even be better to remove the self-contact from the contact list, as it might be confusing.

**Comment by daniele-athome** [comment]
Alright then, since the message-to-yourself feature was fixed, I'm closing this.
