### ISSUE TITLE
Crashes while searching for contacts

### ISSUE THREAD

**Issue by svrnwnsch** [kontalk/androidclient#263]
I updated to new beta via f-droid. Kontalk now crashes when I hit the search button in the choose contact window. 
Also I noticed a new unnown contact string with some long random string as number.

**Comment by daniele-athome** [comment]
Could you send us a logcat via email please?

**Comment by daniele-athome** [comment]
Never mind, I've just fixed it. Please see https://github.com/kontalk/androidclient/issues/264#issuecomment-69465274
