### ISSUE TITLE
Crash on updating contacts

### ISSUE THREAD

**Issue by Anonymooseable** [kontalk/androidclient#264]
What information should I give to help debug this?

**Comment by daniele-athome** [comment]
Hi, thanks for reporting. If you have root access, you can use Catlog from Play Store to send us a complete system log via e-mail. If you don't have root access, your options are pretty much limited.

**Comment by Anonymooseable** [comment]
That just gets the logcat output, doesn't it? I can grab that via adb as well, right?

**Comment by daniele-athome** [comment]
Oh yes of course, I didn't think of asking you that :-)

**Comment by Anonymooseable** [comment]
https://gist.github.com/Anonymooseable/ae34c874561e420d35d5

**Comment by daniele-athome** [comment]
Fixed. It happens when you don't have any contacts to chat with.
To workaround this (I will release beta5 after fixing a few other bugs) you can store your own number in Android contacts: this will match one user and the app will not crash.

**Comment by Anonymooseable** [comment]
Great, thanks!
