### ISSUE TITLE
Beta4 broken or incompatible with Beta3?

### ISSUE THREAD

**Issue by jluttine** [kontalk/androidclient#272]
I upgraded from beta3 to beta4 and suddenly almost nothing works. Constant crashes, incorrect contact list, unable to send encrypted messages to my contact. Are beta4 and beta3 incompatible? Or what could be the reason..

**Comment by jluttine** [comment]
on cyanogenmod 11, installed from f-droid

**Comment by daniele-athome** [comment]
It is compatible, but we are receiving a lot of issues on beta4 installed from beta3. Please try to reinstall from scratch.

**Comment by jluttine** [comment]
Ok, thanks! I reinstalled from scratch and found some workarounds from the issue list, but I couldn't get the other user to appear on my contact list. I added myself to my contacts, so that Kontalk doesn't crash because of no found contacts, but still it doesn't find the beta3 user.

**Comment by daniele-athome** [comment]
I'm sorry when I said "compatible" I meant "upgradable" :-) beta3 and beta4 work on different servers (beta3 is the old XMPP home-made server, beta4 is a Tigase-based server).

**Comment by jluttine** [comment]
Thanks :)
