### ISSUE TITLE
Documentation for non-push enabled environments

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#277]
Write a wiki page describing push notification scenarios and the use of the preferences helping in those scenarios: *Disconnect when idle* and *Reconnect to server*.

Ref. https://github.com/kontalk/androidclient/wiki/Connection-policy

**Comment by h-2** [comment]
attaching to this issue:

I am pretty sure I don't have GCM installed (no gapps), but I still have the checkbox "Push-Messages" checked in the options. AND it is greyed out, so I can't change it. Is this a bug in the android app? Does it mean I do have GCM installed? How can I check?

Thanks for your help!

**Comment by daniele-athome** [comment]
@h2 greyed out push notifications means that there is no support for it on your device (because you don't have gapps), check status doesn't matter. However, for consistency reasons, we should probably uncheck it while it's greyed out. I'll open a ticket, thanks.

**Comment by h-2** [comment]
Thanks for your quick reply and Kontalk in general! Ok, then its just a consistency matter, yes I think greyed out and unchecked would be more intuitive!

Btw, is there some general place for chatter regarding the app? A mailing list, IRC or should I just open issues with questions? Thx!

**Comment by daniele-athome** [comment]
Of course! We have two Google groups:
https://groups.google.com/forum/#!forum/kontalk-devel
https://groups.google.com/forum/#!forum/kontalk-users

Please note that a Google account is not necessary to write in these groups.

IRC on FreeNode, channel #kontalk.

**Comment by h-2** [comment]
I just saw that apparently there is still an old open source client to GCM available:
http://androidosp.blogspot.de/search/label/Google%20Cloud%20Messaging

Could this possibly be shippped with Kontalk?

**Comment by daniele-athome** [comment]
@h-2 no, that's actually a "client library" for Google Play services which hosts the actual connection code to GCM.

**Comment by h-2** [comment]
@daniele-athome Are you sure? 
http://code.google.com/p/gcm/source/browse/gcm-client-deprecated/src/com/google/android/gcm/GCMRegistrar.java
looks like it actually provides a GCM client independent of Play

>  * @deprecated GCM library has been moved to Google Play Services
> * (com.google.android.gms.gcm), and this version is no longer supported.

→ So although its not offically supported, maybe it does still work?

**Comment by daniele-athome** [comment]
I think I am, internalRegister() actually broadcasts an intent to fulfill the registration process:
https://code.google.com/p/gcm/source/browse/gcm-client-deprecated/src/com/google/android/gcm/GCMRegistrar.java#229

**Comment by h-2** [comment]
> I think I am, internalRegister() actually broadcasts an intent to fulfill the registration process:

And this is only available with play? Also I thought it was independent because it actually doesn't do any `package com.google.` imports, as all the other tools to which use gcm...

But then again I am a Java noob...

**Comment by daniele-athome** [comment]
This library took a different approach: it used the old C2DM APIs available in Google Play services through broadcast intents. But the "usable" part that I would need is inside Google Play services apk.

**Comment by h-2** [comment]
Hm, I am still confused by it, since the commit  message 

> New GCM Demo app that uses register/send functionality of Google Play Services
Library. Deprecates old client app code.

somehow implies that the old client code doesn't use it, or not? Anyway, you are the chief :crown:  :smile: just didn't want this to escape your notice, in case it could be helpful. 

PS: Hope to have my new system setup soon with working android-sdk (you don't know how crazy it is to setup on FreeBSD).

**Comment by daniele-athome** [comment]
That commit message can lead to confusion, but I can assure you C2DM protocol functionality is not open source :-)
Thanks for the heads up anyway.

**Comment by h-2** [comment]
Ok, thanks for taking the time to explain!

**Comment by daniele-athome** [comment]
To everyone looking (and to @h-2): https://github.com/kontalk/androidclient/wiki/Connection-policy (first draft)
Please comment :-)

**Comment by TheLastProject** [comment]
It looks good. However, I'm a bit unsure about the following sentence:

> This mode of operation might be preferred if the user can wait a few minutes for incoming messages, however you can always set Disconnect when idle to never to never disconnect from the server.

How much is "a few minutes"? Up to 2? 5? 10? You may want to clarify that as such:
> This mode of operation might be preferred if the user can wait a few minutes (up to 5) for incoming messages, however you can always set Disconnect when idle to never to never disconnect from the server.

**Comment by daniele-athome** [comment]
@TheLastProject it's the time configured in the *Reconnect to server* preference. I removed *a few minutes*, but I think it's implicit in the previous sentence, where it talks about *Reconnect to server* preference.

**Comment by TheLastProject** [comment]
Okay, that makes sense. I feel you may still want to document the default setting, but this does clarify it. I guess it was implicit, but I don't feel being extra-clear could hurt.

**Comment by daniele-athome** [comment]
@TheLastProject of course. I've rephrased it. What about now?

**Comment by TheLastProject** [comment]
Seems fine to me :)
