### ISSUE TITLE
Android 5 compatibility

### ISSUE THREAD

**Issue by ameenross** [kontalk/androidclient#284]
I have lost many contacts yesterday, and it seems that the cause must have been the Kontalk client which I installed the same day. I didn't do anything else out of the ordinary.

Could it be that Kontalk is not compatible with Android 5? Or with my particular setup, as my contacts are all just local and not synced?

**Comment by daniele-athome** [comment]
I found hard to believe that Kontalk deleted your local contacts. Kontalk has indeed the permission to do that (WRITE_CONTACTS), but that part of code has been tested and consolidated for several months now and never changed.
That said, Android 5 surely brought some breaking changes in API contracts, but I don't think up to this point. I can remember a few years ago a combined bug in Whatsapp and Android (I can't find the link to the news right now) led to several lost contacts, so it would not be the first time.

Anyway, let's try to understand what happened here. Some questions:

* What exact version of Android 5 do you have?
* What Kontalk version have you installed?
* Did you upgrade Kontalk or installed it from scratch?
* Are the contacts you lost registered Kontalk users?

**Comment by ameenross** [comment]
- Android version is 5.0.2
- I installed beta4 from f-droid first, then removed it and installed beta5 from direct download. Not sure when it occurred.
- Installed from scratch.
- Contacts I lost were not Kontalk users. However, I kept contact information from Whatsapp. I used that to reconstruct many contacts.

**Comment by daniele-athome** [comment]
Since there is no real debugging method for such a problem, we should try to reproduce it:

* save all your contacts by exporting them to external storage through the People app (you'll import them again later if you'll lose some)
* uninstall and reinstall Kontalk from scratch (please use beta5)

If you still lose some contacts, try to note which ones were lost and their details (did a lost contact had also email or just phone number, or any other details that made it different from the other non-lost ones?)

**Comment by ameenross** [comment]
I can't seem to reproduce it with beta5 now. However, what I do know is that the contacts that were affected had all their data removed except for whatsapp's data (number behind whatsapp icon). Not all contacts were affected. There was nothing different about the contacts that weren't affected however.

There's something else which seems related. Contacts in Kontalk don't show a name:

![screenshot_2015-01-26-12-19-05](https://cloud.githubusercontent.com/assets/859737/5899025/65ef7f94-a556-11e4-8a62-54541ca3e7cc.png)

**Comment by daniele-athome** [comment]
That usually happens when an unknown number is found on your roster. That is probably your number. Try to add your own number to the contacts and refresh Kontalk contacts.

**Comment by ameenross** [comment]
It is my own number. Adding it as a regular contact works. But it doesn't work when it's only shown as "me" in my contacts app.

**Comment by daniele-athome** [comment]
Yes, that's a thing we need to fix. I'll open another issue.

**Comment by h-2** [comment]
Just writing to say that other than the issue with the unkown (self) contact I don't have any problems with android 5.

**Comment by daniele-athome** [comment]
Thanks @h-2, I'm glad to hear that.
