### ISSUE TITLE
kontalk 2.x doesnt speek with kontalk 3.x

### ISSUE THREAD

**Issue by h-2** [kontalk/androidclient#291]
I recently recommended kontalk to someone using play (i use fdroid), but he couldnt See me after installing. I told him to get fdroid and installiert the beta which worked...

So is 2.x incompatible with 3.x, or the play flavor with non-play flavor? Also where's the difference between the two? And Ehen is the ETA for 3.x in play?

Thanks a lot for your work in kontalk!

**Comment by daniele-athome** [comment]
Hi, version 2.x is not compatible with 3.x. They use different protocols and networks. 3.x is based on a modified Tigase XMPP server, 2.x uses a proprietary protocol with a custom-made server.

As of now we hope to release a first "stable beta" by the end of this spring, but don't know for sure.

**Comment by Manizuca** [comment]
If your friend needs it in Google Play, 3.x is in the Google Play beta channel. 
To use the beta channel you need to join the [Kontalk community on G+] (https://plus.google.com/communities/101430597481731178801). I think that also works if you subscribe to the [kontalk-devel] (https://groups.google.com/forum/?fromgroups#!forum/kontalk-devel) or [kontalk-users] (https://groups.google.com/forum/?fromgroups#!forum/kontalk-users) Google Groups.
After that you have to go to https://play.google.com/apps/testing/org.kontalk and click in "become a tester" (wait some minutes if the option isnt there) . Some hours late it will appear as an update in Google Play

**Comment by svrnwnsch** [comment]
maybe you could add kontalk legacy to fdroid or change the fdroid version to stabel releases.

**Comment by daniele-athome** [comment]
@svrnwnsch legacy can't be added to f-droid because it's built with another package name.
F-Droid was choosen to put betas on it because it doesn't have a beta channel like Google Play and we had somehow to push new versions. Betas will be probably pushed to stable Google Play this summer.
