### ISSUE TITLE
Badge indicator for OEMs supporting it

### ISSUE THREAD

**Issue by h-2** [kontalk/androidclient#292]
I don't know if this is some special samsung feature, but on another person's phone she has a little number on the app-icon that signifies new messages; this works on sms, whatsapp and telegram, but not in Kontalk. Would that be easy to add?
##

**Comment by daniele-athome** [comment]
I think it needs an implementation:
https://github.com/shafty023/SamsungBadger

**Comment by daniele-athome** [comment]
https://github.com/leolin310148/ShortcutBadger
