### ISSUE TITLE
"recommend kontalk to friend" feature

### ISSUE THREAD

**Issue by h-2** [kontalk/androidclient#293]
Many other apps provide the ability to "spam" your friends with ad for the program. While I personally don't think this is super important, people theat I introduced Kontalk to have asked for this feature. Telegram has something like it, in case I was bad in explaining.

**Comment by daniele-athome** [comment]
There is something like this, but maybe it's a bit hard to reach.
Open Kontalk and go the contacts selector (new message button). If you press the menu button you can see an "invite users" action which lets you open an app to send an invitation with the link to the Play Store.
