### ISSUE TITLE
Use roster name for unknown contacts

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#305]
Use the roster name for unknown contacts, if available, otherwise keep using "(unknown)" or the JID itself - if it's not in "Kontalk" format (i.e. 40 hex-digits@a-server-in-kontalk-server-list).

**Comment by marc0s** [comment]
When does a user appears as (unknown)?

I've just moved to v3 and added a new contact and it appears as unknown. I was going to fill an issue but saw this one. How may I debug it or provide more information?

**Comment by daniele-athome** [comment]
It depends. If you add a Jabber contact (non-Kontalk) from a desktop client, it shows "unknown" because it can't map it with any contact in Android. If you receive an invitation (or a message) from an unknown phone number, it will show you unknown because of the missing number in Android contacts.

**Comment by marc0s** [comment]
@daniele-athome So, given that it's a kontalk contact and that I have it on my addressbook in Android (sync'd with DAVdroid, I mention it because I saw an issue related to this) it appears to be a bug?

**Comment by daniele-athome** [comment]
Yes, it might be related to #377.

**Comment by Pantek59** [comment]
@daniele-athome I can confirm the same problem marc0s describes, however I doubt that it has exclusively to do with DAVDroid. My wife and I are using the same phone and sync setup and she is having the issue with unknown contacts, while I do not have any problems in that regard.

**Comment by daniele-athome** [comment]
@Pantek59 are you referring to bug #377 right? If that's the case, please let's talk in #377. This issue here is for a different problem.

**Comment by Pantek59** [comment]
@daniele-athome I don't think it's related to #377 in that matter, since both phones are set up the same way with regard to syncing contacts and did not sync since before the update to V3. Nevertheless one phone works fine while the other cannot add new contacts to the list and exiting contacts are now unknown.

It seemed to me that this had relations with the phenomenon described here, so I did not want to open a new bug report for it. Would that have been a better idea you think?

**Comment by daniele-athome** [comment]
@Pantek59 no, this issue is for using the name from the roster (the one you may have set in a XMPP desktop client) in Kontalk if you don't have his/her number to match it.
I guess you've already enabled the DAVDroid workaround in Kontalk, right?

**Comment by Pantek59** [comment]
@daniele-athome I did now and it indeed solved the problem one phone was having! The other phone does seem to work without it, somehow.
Thanks for your help and sorry for messing up this thread, my mistake!
