### ISSUE TITLE
Emoji drawer not reopening on resume

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#309]
There are still some glitches...

**Comment by h-2** [comment]
The built-in emoji drawer is not working at all anymore with beta7. The emoji button in the bottom right does work (if I don't use the Enter button). As previously mentioned I have Android5 / CM12.

BTW: concerning the Emoji rendering I realised a few things:
it doesn't matter if I use the system Emoji button or the other ones, the Emojis rendered in the messaging view always have the system theme. Messages displayed on the lock screen however always have the application theme (apple?). A little strange...

**Comment by daniele-athome** [comment]
> The built-in emoji drawer is not working at all anymore with beta7. The emoji button in the bottom right does work (if I don't use the Enter button). As previously mentioned I have Android5 / CM12.

That's I bug I've fixed recently - sorry happens only on Lollipop.

> it doesn't matter if I use the system Emoji button or the other ones, the Emojis rendered in the messaging view always have the system theme. Messages displayed on the lock screen however always have the application theme (apple?). A little strange...

Sorry I'm not getting it: Kontalk should always display Apple emojis (the one we provide), while the rest of the system (including notifications) should display Android emojis. Isn't it what is happening to you?

**Comment by h-2** [comment]
> That's I bug I've fixed recently - sorry it happens only on Lollipop.

No problem, good to hear its already fixed!

> Isn't it what is happening to you?

Hmm... I thought it was the other way around actually... But maybe I am confusing both of them. I thought the system emojis where "circular" ones (and the the "fat" ones where apple)... Because the circular ones are also used in telegram. I will send a screenshot asap!

**Comment by h-2** [comment]
I think I did confuse them, you are right!

**Comment by daniele-athome** [comment]
By the way @h-2 I just saw your blog post, thanks!!!
