### ISSUE TITLE
Updating contact list takes really long

### ISSUE THREAD

**Issue by schiesbn** [kontalk/androidclient#316]
I'm running kontalk 3.0-beta7 from f-droid but I already discovered the behaviour with beta6 and probably earlier. Kontalk needs really long to update my contact list, it takes up to 1 minute. Not sure if this is a client or a server issue. The client uses a server list from "28.12.2014 14:20". I just tried to update the server list but I get a message telling me that the client can't download the server list and that I should try it later again.

Let me know if you need any additional information or if I should try something.

**Comment by daniele-athome** [comment]
Thanks for reporting. It is related to a recent change that didn't cover all the involved code. I'll fix it in the next beta.
