### ISSUE TITLE
Can't update server list

### ISSUE THREAD

**Issue by aracnus** [kontalk/androidclient#329]
Hi. I'm using Kontalk 3.0-beta7 (from F-Droid) and when I try to update servers list I receive a message that it's not possible download servers list and that I should try later. My last update was on Dec 28, 2014. Is there any problem with servers list?

**Comment by daniele-athome** [comment]
Thanks for reporting. This is because support for server list retrieval still needs to be implemented on Tigase. I've opened an issue for this: #330 and kontalk/tigase-extension#10 for server-side.
