### ISSUE TITLE
inform user if an existing contact installs Kontalk

### ISSUE THREAD

**Issue by h-2** [kontalk/androidclient#332]
I have convinced quite a few of people to use Kontalk, but sometimes, people from your addressbook start using it without you knowing. It would great that if you are both in each other's addressbook, Kontalk immediately informs the user that the person now also has Kontalk (and subsequently intiates invitation workflow).

What do you think? Telegram has something similar and I think its a cool thing, because people immediately start to chat "Oh cool, you have Kontalk now, as well! It's great, did you know ...".

**Comment by daniele-athome** [comment]
I'm sorry but this is not technically possible. Kontalk servers does not store data during user contacts checking, both for privacy and for technical reasons (e.g. limiting resource usage in servers). I'm sure you'll understand. Unless you have some other idea without storing all of the contacts of all users on the server :-)

**Comment by h-2** [comment]
Well, the local Kontalk instance obviously knows which of my contacts has Kontalk. Then after doing a routine rescan of my contact list (does it do that regularly?) if it detects that new people are on the list, it can inform my about it :smiley: -- no servers involved!

**Comment by daniele-athome** [comment]
Well, contacts sync follows scheduling rules defined by the operating system, but I guess it could be triggered with a manually defined (manually as in defined by the application) timer.

**Comment by daniele-athome** [comment]
I've opened #333 for that.

**Comment by h-2** [comment]
Thanks! But to me the interval is not so important, as being informed about new Kontalk-users in my address book. I fully accept if you think its not that important, though.

**Comment by daniele-athome** [comment]
I've put into future developments (4.0 milestone), but it's not written on stone :-) it might even be implemented by someone else entirely. Let's hope that with popularity rising there will be more developers too.
