### ISSUE TITLE
find contacts by mail

### ISSUE THREAD

**Issue by ka223** [kontalk/androidclient#334]
Hi,

the contacts are only fixed to phone numbers.

This number could maybe switch every 2 years, a mail address (which is used by xampp) has generally no date of expiry.

Both can be used by threema, maybe something like that can be integrated in kontalk too?

Thanks

**Comment by daniele-athome** [comment]
Sorry but Kontalk is a phone number based service.
Also this would require users provide email addresses and store them in a server.
