### ISSUE TITLE
Warn user about registering another device

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#338]
If you register a new device from scratch (thus with a new key), the previous key will be invalidated and will be no longer valid for the server. During a registration attempt, the server will check (federated check) if the user id is already being used and launch a BIG WARNING that the other device will be unable to login, suggesting the user to proceed with key export/import. In that case, point the user to a wiki page describing this procedure with the current only available method: key export to zip file and import in another device via file transfer.

Since remote invalidation is no longer being developed, warn the user anyway and add a `force` attribute to the registration request if the user approves.

Ref. kontalk/tigase-extension#32

**Comment by margori** [comment]
I confirm having this issue with collateral: my contacts receive a waring message, refresh contact list not showing my contacts, after a contact send me a message is shown as unknown.

**Comment by daniele-athome** [comment]
Actually that is another bug which is already fixed. It will be released in rc2, hopefully tomorrow night.

**Comment by margori** [comment]
Thanks!
