### ISSUE TITLE
Warning on user's key change

### ISSUE THREAD

**Issue by h-2** [kontalk/androidclient#340]
A few days ago, a friend unregistered his account from the server, deleted Kontalk and then reinstalled it and recreated the account. This implies that his keys changed, right? 
We could immediately chat, though, and I was not informed that any keys had changed. This is a security issue, I think, because it means that a party that controls the server and the transport can MITM the communication, by pretending both people updated their keys. Or did I misunderstand?

I think the user should be warned prominently if they key of another person changes, something like:

**Bob's keys have changed unexpectedly!** Please verify with Bob whether he reinstalled Kontalk or recreated his keys intentionally, otherwise **your communication with Bob could be compromised!** 
*To prevent this from happening to you when reinstalling Kontalk, always export your keys beforehand through the settings and then re-import them.*

**Comment by daniele-athome** [comment]
Thanks @h-2, perfectly right assessment about security. I'll try to make this into beta9.

**Comment by daniele-athome** [comment]
I've thrown in a basic implementation. Of course it can be improved, it's just a quick fix for releasing beta9 soon and receive feedback by the user.
