### ISSUE TITLE
Communication broken after beta8 upgrade

### ISSUE THREAD

**Issue by lkuchenb** [kontalk/androidclient#341]
Both parties upgraded to beta8 from F-droid (versionCode 41) and communication is no longer possible. Messages can no longer be decrypted by the opposite party and are shown as "(encrypted)".

**Comment by daniele-athome** [comment]
Sorry it's a known bug, it has been fixed in beta8.1 the day after releasing beta8. It should be pushed to F-Droid soon. I will contact them to speed up the update.
