### ISSUE TITLE
Separate users table from keys

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#350]
When refreshing the contacts list, fingerprints are overridden without notice. We need to split the users table from the key data.

**Comment by h-2** [comment]
Maybe the keys could be stored inside the address book record of android? That way they would be automatically synced with other devices as well...
Of course one could also use a pgp keyring app, but I think that might confuse users...

**Comment by daniele-athome** [comment]
Storing in Android contacts is unreliable for some devices, so I'll do that just as informative data for the user, but not for actual use in-app.
Also, integrating with something else like OpenKeyChain would be nice; it could confuse some users but other might benefit from it.

**Comment by daniele-athome** [comment]
This is quite urgent because it's also causing a race condition leading to loss of fingerprint and public key from internal storage in some cases (repeated syncs).
