### ISSUE TITLE
Release 3.0-rc1 to Play Store

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#357]
In addition to the standard release checklist, we also need to update Play Store listing.

- [x] phone screenshots
- [x] tablet screenshots
- [x] full description (http://stackoverflow.com/questions/11071127/google-play-app-description-formatting)
- [x] recent changes (expecting people from 2.x)

**Comment by TheLastProject** [comment]
Not sure if you still need help with this, but if you do...

# Full description
>Follow @kontalknet on Twitter or Identica to keep up to date with the latest changes.

>Kontalk is a secure instant messenger, allowing you to send and receive messages and images (other file types coming soon) to and from other Kontalk users completely free of charge (carrier fees for Internet traffic may apply). It uses end-to-end encryption to keep your conversations safe and private, so that only you and the person you are talking to can read it. Kontalk even goes as far as to encrypt your phone number on the servers, so even the server operators can't know who is using Kontalk.

>Kontalk automatically finds other Kontalk users in your phone's contact list, making it even easier to start chatting on Kontalk with your friends. It also supports multiple devices, making it very easy to start chatting on your phone and continue the conversation on your tablet.

>Kontalk is an completely Open Source community project, with all the source code hosted on GitHub (https://github.com/kontalk), allowing everyone to inspect its security and improve it. It relies on community donations to keep the infrastructure running, so if you can, please donate on http://kontalk.net/.

I decided to leave XMPP support out because it is overly technical. When the desktop client becomes as easy to use as the phone client (maybe it is already, I haven't tried it?), the following text could be added after the text for multiple devices:

>Want to continue chatting on your laptop or desktop? No problem, with the desktop client, Kontalk has got you covered, switching being as easy as always.

**Comment by daniele-athome** [comment]
Thanks, we'll surely use some parts :-)

**Comment by abika** [comment]
The desktop client is not yet ready for the masses, but its slowly getting better and better
