### ISSUE TITLE
Keys are lost if you open a conversation while syncing

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#362]
Key warning is shown. Can probably be resolved by splitting users and keys in the database.

Another fix is fixing syncer:

* give an ID to presence request to map responses 
* presence count check should be based on predicted presence count (i.e. number of subscribers buddies in the roster: use presence group).

**Comment by webratte** [comment]
Version 3.0-rc1 
AFTER every sync Key warning is shown for my own number.

**Comment by daniele-athome** [comment]
Can you provide some proof for that? I've tried several times and I saw it happens only of you open a conversation while a sync is ongoing.
Anyway this is part of a minor refactoring that will change the way some things are done (namely separating users data from users keys).

**Comment by webratte** [comment]
I don't know how.
I go to contactlist and click my own contact - Key warning is showing.
Then I click on accept.
The red banner is away.
Then I sync and wait until sync is finished.
The red banner is showing again.

I can make a logcat if it can helps.

**Comment by daniele-athome** [comment]
Exactly. But that happens only in a specific moment which I haven't had time to analyze yet. Tonight I will look into it and release a bugfix as soon as possible.
