### ISSUE TITLE
Own key activity

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#363]
In OTR-like systems, it is very important to be able to verify you are talking to who you think you are talking to. For this, it is important to be able to find out your own key, so the "verify" option in a friend invite can be used to actually make sure you are talking to your friend without anyone in the middle of it.

**Comment by daniele-athome** [comment]
Create an activity with the fingerprint. Use also QR code in the future.

**Comment by juanito003** [comment]
Hi, I hope in 3.0 we would be able to check the key number (or hash) from ourself and from a friend and be able to copy paste it easily. It is important for me to make sure the other contact is the right person by comparing the key hashes. Thanks for all the hard work and for this great app.

**Comment by TheLastProject** [comment]
Seeing how everyone smartphone and tablet has a camera, basically, a scannable QR code would probably be better. But yes, I'd quite like that, especially with a way for Kontalk to tell you if you confirmed someone out-of-band or not.

**Comment by daniele-athome** [comment]
Closed with 281cd6f11a3cb1ddcaaf94f91feb763b207bd395.
