### ISSUE TITLE
Warning when sending message to new/unallowed friend is overly technical

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#366]
So, a lot of my friends got the following error message when trying to send me a message on Kontalk 3 before I allowed them:

"Unable to find a public key for this user. Try refreshing your contact list or disable encryption from settings to send message anyway."

I feel this error message is overly technical and even confusing. It should not appear when an invitation is pending. Instead, the message should remain in "waiting to send" mode and automatically be sent as soon as the invitation is accepted. Perhaps the text "Your friend has not accepted your invitation yet. The message will be send as soon as they accept you" could be displayed on a toast, or simply no text at all.

**Comment by daniele-athome** [comment]
Thanks for reporting. It sounds right. A mechanism for pending invitation approval status should be implemented to queue the message automatically. I'll open a new ticket for that. This one will be about changing the displayed message itself.

**Comment by daniele-athome** [comment]
Implementation note: show a "invite is pending" toast when public key is missing AND subscription is not "both".
