### ISSUE TITLE
Do not notify chat invitation repeatedly

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#372]
Fire chat invitation just once until they are deleted or processed.

**Comment by TheLastProject** [comment]
Not sure if this is related, but my chat invitation didn't arrive to another Kontalk user who upgraded from 2 to 3 after I did until I opened my conversation with them again

**Comment by daniele-athome** [comment]
Yes, that's because subscription pre-approval (which fixes this "bug" you're talking about) isn't implemented in Tigase yet. It's under design and expected for Tigase 7.1.0.
