### ISSUE TITLE
Image previews randomly disappear

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#374]
The image previews shown in conversations tend to randomly disappear after some time. The chat balloon which contained the image preview then looks like an empty message (no text, only the time and, if outgoing, the send status). Clicking on the empty chat balloon will still open the gallery containing the picture.

It happens for both incoming and outgoing messages. I don't know what happens if the image wasn't downloaded yet.

**Comment by daniele-athome** [comment]
Can you send us a logcat of the event? Right after the balloon is displayed on the app. Thanks!

**Comment by TheLastProject** [comment]
Thinking of it, this may be an issue with my custom ROM. My gallery displays all images as videos as well. I'll leave a notice if I find anyone else with the same issue.
```
I/ActivityManager(  409): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.kontalk/.ui.ConversationList bnds=[0,319][80,419]} from pid 633
D/MessageCenterService( 1103): Message Center starting - Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService }
I/ActivityManager(  409): START u0 {act=org.kontalk.conversation.VIEW dat=content://org.kontalk.messages/conversations/9 cmp=org.kontalk/.ui.ComposeMessage} from pid 1103
D/MessageCenterService( 1103): Message Center starting - Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }
D/MessageCenterService( 1103): Message Center starting - Intent { act=org.kontalk.action.CONNECTED cmp=org.kontalk/.service.msgcenter.MessageCenterService }
D/MessageCenterService( 1103): Message Center starting - Intent { act=org.kontalk.action.ROSTER_LOADED cmp=org.kontalk/.service.msgcenter.MessageCenterService }
D/MessageCenterService( 1103): Message Center starting - Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService }
I/ActivityManager(  409): Displayed org.kontalk/.ui.ComposeMessage: +534ms
D/MessageCenterService( 1103): Message Center starting - Intent { act=org.kontalk.action.PRESENCE cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
W/Kontalk ( 1103): unable to load thumbnail, generating one
E/Kontalk ( 1103): unable to generate thumbnail
E/Kontalk ( 1103): java.lang.NullPointerException
E/Kontalk ( 1103): 	at org.kontalk.util.MediaStorage.cacheThumbnail(MediaStorage.java:122)
E/Kontalk ( 1103): 	at org.kontalk.util.MediaStorage.cacheThumbnail(MediaStorage.java:117)
E/Kontalk ( 1103): 	at org.kontalk.message.ImageComponent.populateFromCursor(ImageComponent.java:128)
E/Kontalk ( 1103): 	at org.kontalk.message.CompositeMessage.populateFromCursor(CompositeMessage.java:347)
E/Kontalk ( 1103): 	at org.kontalk.message.CompositeMessage.fromCursor(CompositeMessage.java:374)
E/Kontalk ( 1103): 	at org.kontalk.ui.adapter.MessageListAdapter.bindView(MessageListAdapter.java:75)
E/Kontalk ( 1103): 	at android.widget.CursorAdapter.getView(CursorAdapter.java:250)
E/Kontalk ( 1103): 	at android.widget.AbsListView.obtainView(AbsListView.java:2159)
E/Kontalk ( 1103): 	at android.widget.ListView.makeAndAddView(ListView.java:1831)
E/Kontalk ( 1103): 	at android.widget.ListView.fillUp(ListView.java:708)
E/Kontalk ( 1103): 	at android.widget.ListView.layoutChildren(ListView.java:1633)
E/Kontalk ( 1103): 	at android.widget.AbsListView.onLayout(AbsListView.java:1994)
E/Kontalk ( 1103): 	at android.view.View.layout(View.java:14008)
E/Kontalk ( 1103): 	at android.view.ViewGroup.layout(ViewGroup.java:4373)
E/Kontalk ( 1103): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
E/Kontalk ( 1103): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
E/Kontalk ( 1103): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
E/Kontalk ( 1103): 	at android.view.View.layout(View.java:14008)
E/Kontalk ( 1103): 	at android.view.ViewGroup.layout(ViewGroup.java:4373)
E/Kontalk ( 1103): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/Kontalk ( 1103): 	at android.view.View.layout(View.java:14008)
E/Kontalk ( 1103): 	at android.view.ViewGroup.layout(ViewGroup.java:4373)
E/Kontalk ( 1103): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/Kontalk ( 1103): 	at android.view.View.layout(View.java:14008)
E/Kontalk ( 1103): 	at android.view.ViewGroup.layout(ViewGroup.java:4373)
E/Kontalk ( 1103): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/Kontalk ( 1103): 	at android.view.View.layout(View.java:14008)
E/Kontalk ( 1103): 	at android.view.ViewGroup.layout(ViewGroup.java:4373)
E/Kontalk ( 1103): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
E/Kontalk ( 1103): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
E/Kontalk ( 1103): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
E/Kontalk ( 1103): 	at android.view.View.layout(View.java:14008)
E/Kontalk ( 1103): 	at android.view.ViewGroup.layout(ViewGroup.java:4373)
E/Kontalk ( 1103): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/Kontalk ( 1103): 	at android.view.View.layout(View.java:14008)
E/Kontalk ( 1103): 	at android.view.ViewGroup.layout(ViewGroup.java:4373)
E/Kontalk ( 1103): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1892)
E/Kontalk ( 1103): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1711)
E/Kontalk ( 1103): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
E/Kontalk ( 1103): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
E/Kontalk ( 1103): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
E/Kontalk ( 1103): 	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
E/Kontalk ( 1103): 	at android.view.Choreographer.doFrame(Choreographer.java:532)
E/Kontalk ( 1103): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
E/Kontalk ( 1103): 	at android.os.Handler.handleCallback(Handler.java:725)
E/Kontalk ( 1103): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/Kontalk ( 1103): 	at android.os.Looper.loop(Looper.java:137)
E/Kontalk ( 1103): 	at android.app.ActivityThread.main(ActivityThread.java:5041)
E/Kontalk ( 1103): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/Kontalk ( 1103): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/Kontalk ( 1103): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/Kontalk ( 1103): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/Kontalk ( 1103): 	at dalvik.system.NativeStart.main(Native Method)
D/MessageCenterService( 1103): Message Center starting - Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }
```

**Comment by daniele-athome** [comment]
That's strange. Context is null. This might happen in rare cases when e.g. you're exiting the activity (but of course that's not the case). It's very hard to debug this kind of issues - most probably it's a firmware bug.

**Comment by TheLastProject** [comment]
In that case, feel free to close this, I'll bother you here again when a friend that's not on a custom ROM has similar issues.

**Comment by daniele-athome** [comment]
Ok, I'll close it for now.
Does it happen for every image balloon?

**Comment by TheLastProject** [comment]
It does seem to happen for every balloon, yes

**Comment by daniele-athome** [comment]
Mmm I'd like to investigate a bit anyway before closing it. I'll put it into rc3 milestone.

**Comment by TheLastProject** [comment]
I'd just had this happen to a family member with a Huawaii (non-rooted, non-flashed). At very least, they confirmed the chat bubble was empty over a phone call. The gallery of them works correctly normally, so it doesn't seem to be limited to my device.

**Comment by daniele-athome** [comment]
Thanks @TheLastProject. By not having a device at hand to do the tests, I have to rely on resources on the Internet, which is quite sparse on this. I'll update with my research here.

**Comment by daniele-athome** [comment]
Nothing came up on the internet... this is going to be hard.
@TheLastProject do you have a Huawei device as well? Is your custom ROM stock-based or is it entirely different project such as Cyanogenmod or AOKP or something like that?

**Comment by TheLastProject** [comment]
I run a Samsung Galaxy Gio with a custom ROM which calls itself "MaclawMod" in my about screen, which is a third-party build of CyanogenMod (hackers forsake this device). It's not a perfect custom ROM, but it's the most stable I've found for this phone so far.

**Comment by daniele-athome** [comment]
I might have found a possible cause to this issue... (this more a note for me) apparently, at the moment onFocus is called (where MessageListAdapter is created) getActivity returns null. onFocus is called either by:

* onResume from the same fragment
* onWindowFocusChanged from the parent activity

In the first case, it is ensured by the fragment lifecycle that the activity is already attached, so it's not possible (i.e. it's system a bug)
In the second case, a fragment that might have lost focus in the meantime, receives focus again but the activity was not attached yet (how is that possible?)

In both cases, I'd rather think of this as an Android bug.
However, @TheLastProject what Android version do you and your friend are running? I'll try to emulate this in an emulator. Also if you have other details you can share, such as some particular behaviour you need to reproduce this issue.

**Comment by TheLastProject** [comment]
I'm running Android 4.2.2 myself. The other person, I'm not sure, but some version of Android 4.

It is quite possible it's a device bug. I was told about the issue there over the phone, so there is also the slight possibility they meant something else and it got lost in translation. No need to let this block a release, imho.

**Comment by daniele-athome** [comment]
Thanks, I'll delay this to the next rc, I'm already late :-)

**Comment by TheLastProject** [comment]
Apparently the images do show up on the other phone and I probably misunderstood them. So, at the moment, my device still seems to be the only affected device, which makes it very likely to be a ROM issue.

**Comment by daniele-athome** [comment]
Ok I'm closing the issue for now (as I can't find anything wrong anyway).
