### ISSUE TITLE
Donation via Playstore doesn't work correctly

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#376]
Kontalkversion:5.0-rc1(40)
Androidversion: 4.1.1

Only donate 1€ works.
If I click e.g "show your love to Kontalk" the window disappears but nothing else.
I send you a catlog via mail.

By the way. The donation window should also be translated ;-)

**Comment by daniele-athome** [comment]
@webratte I'm assuming you're talking about version 3.0-rc1 (44) :P

I think this might be the issue:
```
04-02 19:13:42.401 D/Finsky  (19375): [2801] InAppBillingUtils.pickAccount: org.kontalk: Account determined from installer data - [wCg6rw_Bi23gGPcUARTyxgzfgqg]
04-02 19:13:42.401 E/IabHelper(19190): In-app billing error: Unable to buy item, Error response: 7:Item Already Owned
```

I'll investigate further.

**Comment by webratte** [comment]
Ooops seams I live already in future. ;-)
Sorry for my mistake. Of course I talking about 3.0-rc1 (44)

**Comment by daniele-athome** [comment]
Oh, that's nice (from http://developer.android.com/google/play/billing/billing_overview.html#migration):

> Unmanaged items that you have defined for existing applications will be treated as managed products if you make a purchase request for these items using the Version 3 API

So they need to be consumed.

**Comment by webratte** [comment]
It seems not fixed yet in Kontalk 3.0-rc3.
On my HTC Desire X I have still this problem.

**Comment by daniele-athome** [comment]
Damn I forgot to consume purchases for users that already donated! :-| I'll open another issue.

**Comment by webratte** [comment]
Now it works ;-)
