### ISSUE TITLE
Contacts from DAVDroid are not synced

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#377]
Investigate if it's a device issue or contacts created by DAVDroid are saved in a particular state.

**Comment by daniele-athome** [comment]
This is caused by a missing feature in DAVDroid: https://github.com/bitfireAT/davdroid/issues/91

**Comment by erikfleischer** [comment]
Does 'contacts are not synced' mean that contacts synced via DAVDroid onto the phone do not appear in kontalk? (This is the problem I see on my phone with the combination of Android 4.4 + DAVDroid + Davical 1.1.1).

**Comment by daniele-athome** [comment]
@erikfleischer yes that's what I meant. I will do some tests with an emulator to see what I can do.

**Comment by h-2** [comment]
Hm, FWIW I use davdroid for all my contacts and it still works. However I am also on lollipop...

**Comment by daniele-athome** [comment]
@h-2 well that "bug" in Android is still open, so I don't think Android version matters here. But I only did a very first research of the problem, so I might be wrong.
@erikfleischer I assume you're using the latest version of DAVDroid and so are you @h-2 (I mean no special build or beta or whatever).

**Comment by erikfleischer** [comment]
I'am using davdroid 0.7.2 and Kontalk 3.0-rc2. I have installed both Kontalk and Davdroid from f-droid.org if that matters.

**Comment by marc0s** [comment]
Seems that I'm hitting this same bug. Same versions as @erikfleischer: davdroid 0.7.2 and kontalk 3.0-rc2. Android version 5.0.2 from CM12

**Comment by daniele-athome** [comment]
Thanks @marc0s, I'll take note of that and consider also Lollipop on my emulator tests.

**Comment by h-2** [comment]
My davdroid is still still 0.6.11 if that matters, and my kontalk is still beta9 (I currently cannot uninstall or upgrade apps due to some ridiculous bug somewhere causing my phone to reboot when I try :weary: )

Strange that it works for me if it doesn't for @marc0s

**Comment by marc0s** [comment]
@daniele-athome please ask for any logs or whatever if you need it :)

**Comment by donty** [comment]
I use DAVDroid but to check this out I switched my personal contacts to CardDav Sync and it works fine for all of those contacts whether syncd from ownCloud or Zimbra. The grouping of contacts mentioned in one of the links did not help me. Seems not to be a Kontalk problem but a DavDroid approach.

**Comment by hurradiegams** [comment]
Same here, I'm using Android 4.4.4 (PAC-Rom) on a OnePlus One, latest version of DAVdroid. 
Can't access contacts from my address book or add anyone. It only works when someone starts the conversation, but I can't add that person or see the equivalent contact from my address book (though I can see the online status)

**Comment by daniele-athome** [comment]
I've tried on Owncloud with an Android 4.0.3 emulator. I can workaround the issue by adding my contacts to at least 2 groups. Can you confirm?

Anyway, the only fix I can think of is a workaround preference to include non-visible contacts to be included in the sync, but that will include possibly also garbage if the user doesn't keep his address book clean.

**Comment by hurradiegams** [comment]
Hm, I can't move my contacts to any group nor do I have the group-option at all in the contact details. Has maybe to do with all my contacts being on my DAVdroid-account and not a single one locally stored?
I've made a new contact with a known Kontalk-User (local, in a group), and as soon as I copy this new made contact to the SIM card it can be found by Kontalk.

**Comment by daniele-athome** [comment]
@hurradiegams due to a limitation of Android you need to add contacts to groups at the source (that is, owncloud web interface or any other system you use as your backend).

**Comment by marc0s** [comment]
I confirm the workaround of the groups. Nice finding!

**Comment by daniele-athome** [comment]
Thanks @marc0s, good to know (or not? :-(
I've pushed the workaround preference anyway, it will be available in rc3.
