### ISSUE TITLE
Open Galery to attach pictures

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#379]
Kontalk Version 3.0-rc2 (45)
Phone: Samsung galaxy S4 mini
Android: 4.4.2

Steps to reproduce:
* click on the sign for "attachment"
* choose "picture"

A windows with possible apps pops up.

On the Samsung phone in this window is shown only "camera" and "documents"
On my HTC there also shown "galery" and "file" manager".

__To show received pictures it's possible to choose "galery".__

Is this a OS/phone specific issue or is it possible to fix it in Kontalk?

See also the screenshot

![opengalery](https://cloud.githubusercontent.com/assets/6864851/7003013/5bd01ed2-dc43-11e4-94ee-f0ff07799ef5.png)

**Comment by daniele-athome** [comment]
This is a behaviour change in Android since 4.4: ACTION_PICK intents now delivers to document providers - most gallery apps are not.
