### ISSUE TITLE
Users disappear after chat invitation

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#380]
By itself, this behaviour is logical, but I had it confuse several users.

Imagine the following situation:
- User gets chat invitation
- User accepts chat invitation
- User closes chat and goes back to the main screen

The person who sent the chat invitation will disappear from the thread list because there was no message in the conversation. However, I had people tell me "they disappeared" in a panicky way, which states that this behaviour is confusing. Perhaps consider making the chat invitation an actual message displayed in the chat, so it automatically creates a single message in the thread?

**Comment by daniele-athome** [comment]
I don't know... seems like forcing... most times chatting begins right after invitation is accepted. But it might make sense to simulate a "message" in this case.
@acappelli what do you think?

**Comment by acappelli** [comment]
To solve the problem we could use a nice ping sent automatically after confirmation.
what do you think?

**Comment by daniele-athome** [comment]
@acappelli what do you mean? Please elaborate.

**Comment by TheLastProject** [comment]
Seeing how the + button to start a new conversation will be clearer in Material design (I haven't seen screenshots, but I have looked at the used libraries), this can probably be closed in favour of #412.

**Comment by daniele-athome** [comment]
Mmm I don't think so. I'd bet people would go panic anyway :-)
There is no good way of fixing this imho, probably the whole invitation workflow needs to be redesigned...

**Comment by daniele-athome** [comment]
Any solution I come up with seems wrong, I'm getting frustrated :-)
I'm closing it for the moment. We'll see how people will react to the new material design.
