### ISSUE TITLE
Adaptive ping timeouts per connection type

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#383]
Save a ping timeout value for every connection type (WiFi, mobile, etc.).
This can be considered a bug since adaptive ping should be implemented to differentiate network connections.

**Comment by ameenross** [comment]
Just wondering, is this more complex than simply knowing the connection type? For example, my home Wifi is pretty flakey due to interference from other networks - which has gotten worse lately. My mobile connection is much stabler, and my wife's mobile connection is most stable.

**Comment by daniele-athome** [comment]
@ameenross that's the problem: covering all the different scenarios. Not everyone has unstable WiFi and not everyone has stable mobile connection, so apps have to "adapt" to the current situation.
Some programs use a more-or-less basic algorithm, I decided to use a more complex approach, hopefully it will work much better than the others (when it will be completed and tested, and that will require a few release iterations to cover the greatest number of scenarios as possible).
