### ISSUE TITLE
Contact list full of unknown entries

### ISSUE THREAD

**Issue by quizilkend** [kontalk/androidclient#387]
Hey!

Since the update to the RC releases all contacts in my contact list are "unknown" and I always get security notifications about changed keys.

This is my first issue, therefore some important information may be missing - sorry for that.

Best wishes,
Sammy

**Comment by daniele-athome** [comment]
Hi! Are you using DAVDroid by any chance?

**Comment by quizilkend** [comment]
Yes I am.

**Comment by daniele-athome** [comment]
Please refer to #377. It's a supposed combined bug of Android and DAVDroid. We'll try to find a suitable workaround soon.
