### ISSUE TITLE
I see myself in the list of contacts

### ISSUE THREAD

**Issue by giner** [kontalk/androidclient#393]
When want to create a new chat and open "Choose a contact" page I see myself in contacts with my own phone number and I can do nothing with it. I can't remove it, I can't send a message to it. Is it a bug or a feature?

**Comment by daniele-athome** [comment]
You can see yourself: it's a feature.
You can't send messages to yourself: it's a bug. Does it show the *key missing* warning toast? It's a bug that was recently fixed, it will be out in rc3.
