### ISSUE TITLE
Remember last working ping interval

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#397]
The adaptive ping manager works well now, but it still lacks one thing: it doesn't remember which interval worked. If a certain interval works the first time, it is increased by 1.5 times and repeated. But then that interval won't work and it will try to half it back. This is not useful since it will cause repetitive increase/decrease and therefore continue reconnections.

Possible approaches:
* Store the last N intervals used and use an average (can bring too much fluctuation)
* Use the minimum working interval and don't try to increase it back for a few days

Any other ideas?

**Comment by TheLastProject** [comment]
What about simply sticking with an interval with "exponential backoff"?

If the ping timeout was succesfully increased, reset the backoff.
If the ping timeout failed when increasing, increase the backoff, and stay with the previous working value for the backoff time.

This has the benefit that on temporarily unstable networks, but normally stable ones, Kontalk will go back to the higher ping timeout reasonably quickly, and "learns" the average stability of the networks the user connects to.

Example:
```
20 - success
25 - success
30 - fail
25 - stay for 2 hours
30 - fail
25 - stay for 4 hours
30 - success
35 - fail
30 - stay for 2 hours
etc...
```
(2 hours was chosen as an example, I have no clue what would be a sane timeout)

**Comment by daniele-athome** [comment]
Great idea @TheLastProject, thanks! Seems perfect for this use case. I'll try to make it for rc3 this thursday.
