### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#41]
Dark theme for Android client. Use theme attributes whenever possible.

- [x] based on Theme.AppCompat.DayNight.NoActionBar
- [ ] system navigation bar background (OEM issue, tested on Samsung A40)
- [x] options menu
- [x] floating action menu semi-transparent background (too white)
- [x] message status icon indicators (delivery and security status; beweare that they are used inside the balloons and but also in other normal dark views)
- [x] group chat indicator
- [x] message list item view (text color should be linked to the chat balloon theme; same thing for the date view)
- [x] quote content view (both text color and blockquote vertical line should probably be handled by the theme?)
- [x] composer bar push-to-talk background
- [x] composer bar icons (attachment icon is lighter than the others, why?)
- [x] reply bar in composer
- [x] composer attachment selection view (using a fixed background color)
- [x] preference icons
- [x] My personal key activity
- [x] About activity
- [x] audio content view progress bar (when used in light ballons; ~~will need progress and thumb drawables~~ will use tint only for API level 21+, sorry older Android people I'm too lazy)
- [x] audio content view vertical position (what the hell?? Different behavior in API < 21)
- [x] Position/send position fragments
- [x] static map pin color
- [x] other colors? (use attributes!! test registration!!)
- [x] default chat background (probably just negating the colors should be fine); also applies to contact/group info fragment
- [x] theme switch utility (and preference)
- [x] some misuse of colors in location sharing layouts
- [x] showcase colors (text and background)
- [x] investigate use of accent color (it probably should be lighter; note that it's also used as color of positive button in dialogs)
- [x] showcase!

Also the existing chat balloons are too light to be used in a dark theme (it kind of defeats the purpose). We need other 9-patches to either create new themes or create a dark version of the existing ones (the latter would be better because the theme will change automatically with night mode). Probably not all themes would be day/night, I'll do my best.

- [x] Hangout
  - [x] incoming balloon too bright?
- [ ] Silence
- [ ] Classic
- [ ] Classic (old)
- [ ] iPhone

Minor refinements:

- [x] negated chat background tile is maybe too dark
- [x] link text in messages when using dark balloons (blue on blue of the Hangout theme for incoming messages)

Some sources:

https://stackoverflow.com/a/40841611/1045199 (theme overriding AppCompat style)

##

**Comment by daniele-athome** [comment]
Possible reference theme: https://github.com/henrytao-me/android-md-core

**Comment by relan** [comment]
[Theme.AppCompat.DayNight](https://medium.com/@chrisbanes/appcompat-v23-2-daynight-d10f90c83e94) can be used for this.

**Comment by daniele-athome** [comment]
If I'm getting this right:

> One thing to note is that this feature only actually has an effect when running on an API v14 and later device, on devices before that it will default to the light theme.

that doesn't help :-( any thoughts?

**Comment by webratte** [comment]
IMO that featre  is not soooo important.

If it's easy to implement why not do it.(I don't know if it's really easy)

If I'm right the effect would be that it works on new phones and on old phones would be nothing happens.(they only can use the light theme)

Time after time users will change there phones and can set dark theme.

You know what I mean?!

**Comment by daniele-athome** [comment]
Yes I understand @webratte, but I'd like to examine all possibilities before I completely cut off Android < 14 from this, that's all :-)
Besides, I'm already doing some tests with the AppCompat dark theme, and it's pretty nice. Although some stuff must be addressed:

* message status icons
* balloon themes (I think some of them should be re-colored)
* some other minor coloring

**Comment by relan** [comment]
According to the [Google Play stats](https://developer.android.com/about/dashboards/index.html), 98.4% of devices are API 14+. I think it's OK to leave Gingerbred users without some UI improvements.

Theme.AppCompat.DayNight has the following advantages IMO:

* Built into the support library. No extra dependencies.
* Provides a very convenient resource qualifier `-night`: dark resources are clearly separated from the  default ones.
* If one day Google adds a system-wide night mode switch, we'll have to do nothing to support it.

> some stuff must be addressed

Recent versions of the support library work very well with vector graphics. I'm going to replace PNGs with vector images where possible. This will simplify maintainence of graphic resources.

**Comment by daniele-athome** [comment]
> Recent versions of the support library work very well with vector graphics. I'm going to replace PNGs with vector images where possible. This will simplify maintainence of graphic resources.

I remember that it supported vectors only on Lollipop and newer once. Have they improved the support library for older versions too?

**Comment by relan** [comment]
> I remember that it supported vectors only on Lollipop and newer once. Have they improved the support library for older versions too?

[Yes](http://chris.banes.me/2016/02/25/appcompat-vector/).

**Comment by daniele-athome** [comment]
Actually it seems the dark theme is indeed supported, at least on API level 10. I believe what you were talking about to not be supported was the -night modifier, weren't you? If that's the case, it could be easily handled through styles.

![Uploading device-2016-09-17-111209.png…]()

With a few... ehm... imperfections (e.g. that list item is NOT selected :-) but I'm sure we can work out on them. I'll see if it's worth the effort.

**Comment by relan** [comment]
> Actually it seems the dark theme is indeed supported, at least on API level 10. I believe what you were talking about to not be supported was the -night modifier, weren't you?

Not me, but Chris Banes. :) `Theme.AppCompat.Dark` is indeed available on all API levels. The `night` [resource qualifier](https://developer.android.com/guide/topics/resources/providing-resources.html) and [UiModeManager](https://developer.android.com/reference/android/app/UiModeManager.html) are available since API 8. Support library devs probably just didn't care about anything before API 14.

You can see how themes are implemented in F-Droid client [through](https://gitlab.com/fdroid/fdroidclient/raw/master/app/src/main/res/values/styles.xml) [styles](https://gitlab.com/fdroid/fdroidclient/raw/master/app/src/main/res/values-v21/styles.xml) (I took part in this) and, honestly, they're far from being elegant or maintainable.

**Comment by daniele-athome** [comment]
Dark mode will be shipped in next beta.
Only the Hangout theme fully supports light/dark. The other themes weren't ported for now.
