### ISSUE TITLE
Materialdesign

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#411]
A few month ago there was a branch UI-mareial.
Have you dropped it?

**Comment by daniele-athome** [comment]
Hi, we did not forget about it :-) we want to release it after 3.0 stable release, probably for version 3.1. It's a major update.

**Comment by ameenross** [comment]
Could you indicate what this issue is a duplicate of?

**Comment by daniele-athome** [comment]
Mmm I thought I had already opened the PR... sorry it's a pull request for the material branch, #412.

**Comment by ameenross** [comment]
Cool, thx!
