### ISSUE TITLE
Cross-certify subkey

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#417]
Oh s**t!!!!
https://gnupg.org/faq/subkey-cross-certify.html

**Comment by h-2** [comment]
What are the implications of this? :astonished:

**Comment by daniele-athome** [comment]
Nothing so dangerous actually... anyone having your public key can claim the subkey encryption as his own (that is, linked to his public key), but that's it. No actual encryption and/or signing is possible with the public key anyway.

**Comment by daniele-athome** [comment]
Deprecated by #418.

**Comment by daniele-athome** [comment]
Reopening because a singing subkey was introduced when switching to ECC keys.
