### ISSUE TITLE
A problem occurred configuring project ':app'.

### ISSUE THREAD

**Issue by geass** [kontalk/androidclient#433]
When im building gradle im taking this error. How can i solve that ? 

Download https://jcenter.bintray.com/com/android/tools/layoutlib/layoutlib-api/24.2.3/layoutlib-api-24.2.3.jar
Download https://jcenter.bintray.com/com/android/tools/dvlib/24.2.3/dvlib-24.2.3.jar
Download https://jcenter.bintray.com/com/android/tools/lint/lint-api/24.2.3/lint-api-24.2.3.jar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module client-common-java : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by daniele-athome** [comment]
You need to initialize and checkout the 2 submodules client-common-java and emojicon. Please refer to git guide on how to do that.

**Comment by geass** [comment]
Thanks man
