### ISSUE TITLE
Publish on Amazon App Store

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#435]
Setup an account to publish Kontalk also there.
We'll need BlackBerry support too. And also support for [Amazon Device Messaging](https://developer.amazon.com/appsandservices/apis/engage/device-messaging). Or consider using the basic flavor at first.

**Comment by keverets** [comment]
The basic flavor would be enough to get people using Kontalk quickly. Right now I have contacts on Kindle and BlackBerry, and it's a hassle to have them install F-Droid just to be able to install Kontalk (though it's good if they do, that's a barrier to entry that reduces the number that will, and limits the network effect since their contacts are even less likely to do the double-step install).

Setting up an Amazon publishing account is quick & easy (and free, if I remember correctly), so publishing a non-GCM version there should be a straightforward task.

**Comment by daniele-athome** [comment]
I guess publishing 3.1.10-basic wouldn't hurt for the moment. Thanks for the offer by the way. I'll handle it ASAP :-)

**Comment by daniele-athome** [comment]
Ok I've submitted a publish request of v3.1.10 to Amazon, it should be live for tomorrow morning, barring problems. For now I've copied the listing descriptions from Google Play, but it's going to need some polishing (e.g. I'm not sure whether the short description for Amazon has the same meaning of Google Play short description). Also there is a new string "Product feature bullets" which need to be translated (for now it's been copied from English to all languages).
All those stuff should go through Weblate, so for now let's wait for actual publish, I'll close this issue when all tasks have been completed.

**Comment by daniele-athome** [comment]
Ok I think I'm done... I've setup another component on Weblate:
https://translate.kontalk.org/projects/kontalk-androidclient/amazon-appstore/

It's ready for translation in all languages supported by the Amazon Appstore:

* Italian (already done by me)
* French
* German
* Japanese
* Portuguese (Brazil)
* Spanish

A quick explanation on the strings:

* long_description: this should be the exact content of the long description of Google Play, stripped out of all HTML tags and using a minus sign "-" instead of the existing "bullets" in HTML entity form (they are not allowed)
* short_description: a shortened version of the long description, no newlines are accepted (the whole content is printed on a single line anyway). Use the English version as a template to know what to put in there (100% recycled from long description anyway)
* feature_bullets: quick features description, one per line, including the "bullet" character (you can copy that from the original string)
* title: this should stay as-is, "Kontalk Messenger"

I'll post these guidelines also on the devel mailing list.

**Comment by daniele-athome** [comment]
I filled in translations for parts I could copy-paste from Google Play Store listings, but some of those are still missing from Weblate - mainly short description (using the one from Google Play from now) and product feature bullets (copied from English). I think I can close this issue now, translations will eventually come in (I made an announcement on the mailing list).
