### ISSUE TITLE
Make encryption backwards compatible

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#439]
ECC-based encryption introduced a fix to the encryption method which will make older clients mark them as "invalid digital signature". Consider doing something for this (e.g. use some workaround only for 3.0 and then remove it in 3.0.1, something like a soft transition) or simply ignore the problem and let anyone upgrade.
On the new version, we could use [XEP-0092](http://xmpp.org/extensions/xep-0092.html) to check the other user's version and issue a message warning the user to tell his/her buddy to update. Or we could do a double signature verification check, one with the old method and one with the new and declare the message valid nonetheless.

**Comment by webratte** [comment]
I think you should use the easyst way.
Users will upgrade very fast I suppose.

A little warning for upgrade would be nice or unsers could be worried.

**Comment by daniele-athome** [comment]
@webratte don't count on users upgrading: I still have 700+ active users with the old 2.2.9 version, which is due to shut down on Sep 30th :-)

**Comment by daniele-athome** [comment]
Treating as very low priority: the effort is too big for the advantages anyway (a temporary workaround which would last for a single revision - that is, 15 days at most, between 3.0 and 3.0.1). If I'll have time I'll take care of this, otherwise I'll just let people upgrade. It's not such a big deal anyway.

**Comment by webratte** [comment]
> don't count on users upgrading: I still have 700+ active users with the old 2.2.9 version

OK, that's strange.
Especially because in Kontalk 3.x are new features (not only strong encryption). 

If users get error messages they must upgrade.
Maybe you could describe this in Playstore description if you upload this version 3.0.1.
Hopefully users will read it ;-)

**Comment by daniele-athome** [comment]
>  Hopefully users will read it ;-)

Haha very funny :-)

**Comment by TheLastProject** [comment]
For such a small issue (only a small visual red exclamation mark) which is fixed if people just update and which will probably be removed in one or two releases, yet surely increase code complexity, I'd say it's not worth implementing.

**Comment by daniele-athome** [comment]
I also think so. Specially because I'd like to release today :-)
