### ISSUE TITLE
"Last seen" und "message read" out of sync

### ISSUE THREAD

**Issue by h-2** [kontalk/androidclient#450]
I have repeatedly seen now that the information of "Last seen" und "message read" are out of sync, in a way that can't be. E.g: I sent a message 5min ago, the message is being marked as "read" (second green thing) 2min later, but the online status still says "last seen 20min ago".

I have seen this the other way around, as well, but I guess that is possible, because a person can be in the app (i.e. online) but not enter the conversation, so the messages in the conversation don't become marked as read, right?

**Comment by daniele-athome** [comment]
> I have repeatedly seen now that the information of "Last seen" und "message read" are out of sync, in a way that can't be. E.g: I sent a message 5min ago, the message is being marked as "read" (second green thing) 2min later, but the online status still says "last seen 20min ago".

That is part of a server bug we are still trying to mitigate.

> I have seen this the other way around, as well, but I guess that is possible, because a person can be in the app (i.e. online) but not enter the conversation, so the messages in the conversation don't become marked as read, right?

No, that happens because the other party has lost connection but it still doesn't know (and the server realizes it after a few minutes). So the user still seems online, but actually he's not.

Marking invalid because it's a server issue.

**Comment by daniele-athome** [comment]
One more note: a message is delivered when **it reaches the recipient device**. App may not be open at that time. What you're talking about is a different thing: reading notification, not delivery. And "online" in this case means "connected" (thus not necessarily in the foreground). I'm afraid this is a misconception WhatsApp introduced (in "strict" networking terms. Not sure if it can be considered right, but whatever...).
However, we might use the "away" XMPP status to indicate the user has Kontalk in the background. There is already an issue open for that :-)

**Comment by h-2** [comment]
> Marking invalid because it's a server issue.

Ok.

> One more note: a message is delivered when it reaches the recipient device.

Ah, thanks for taking the time to explain. I assumed that the second indicator was for "message read" like in WhatsApp or Telegram. Maybe this could be made more clear somewhere, or changed to not confuse people? Maybe use a yellow check for "delivered to server" that turns green for "delivered to target device" (thats what they imply, right?)?

The conversations Jabber client has support for reading notifications as an experimental feature, as well. This might be kind of cool, although one should definitely be able to set this on a per-user basis.

**Comment by daniele-athome** [comment]
> Ah, thanks for taking the time to explain. I assumed that the second indicator was for "message read" like in WhatsApp or Telegram. Maybe this could be made more clear somewhere, or changed to not confuse people? Maybe use a yellow check for "delivered to server" that turns green for "delivered to target device" (thats what they imply, right?)?

Yes that is what is displayed now.
Single tick means **delivered to server**.
Double tick means **delivered to device**.

Yes I see Conversations is experimenting with [XEP-0333](http://xmpp.org/extensions/xep-0333.html), I'll probably go that way too, replacing also Message Delivery Receipts probably.
