### ISSUE TITLE
Do not hide keyboard if enter is configured as "send"

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#451]
`ComposerBar.submitSend()` invokes `hideSoftKeyboard()` to hide the keyboard if not invoked explicitly by the user before. However, this doesn't seem to work when the enter key is configured as "send" in settings.

**Comment by daniele-athome** [comment]
Seems to be more complicated than it sounded.

**Comment by daniele-athome** [comment]
Seems that invoking the enter action will always hide the input method. Investigate on possible solutions without resorting to intercepting the enter key manually.

**Comment by h-2** [comment]
Maybe this helps:
https://github.com/SMSSecure/SMSSecure/blob/master/src/org/smssecure/smssecure/ConversationActivity.java#L1218
possibly:
https://github.com/SMSSecure/SMSSecure/blob/master/src/org/smssecure/smssecure/ConversationActivity.java#L720

It's the only place I see where they act depending on this setting.

**Comment by h-2** [comment]
Hm, I suspect they catch the enter button and redirect it to the other send button...
