### ISSUE TITLE
Incorrect escaping sequence in translated strings

### ISSUE THREAD

**Issue by Norbert80** [kontalk/androidclient#458]
@daniele-athome

Please have a look at the attached screen shot. Since release 3.0 the text that is displayed if no chat exists does not have bold formatting applied. Instead it displays the tags.

This is a regression. The bug was not present in RC4.
![screenshot_2015-06-14-20-51-12](https://cloud.githubusercontent.com/assets/6921696/8161978/cfca2d6e-137a-11e5-9b95-3a67ed095170.png)

**Comment by daniele-athome** [comment]
Damn escaping! Thanks for reporting.

**Comment by daniele-athome** [comment]
Fixed in 796569a322b5ddf8909e93e80be5bf352aa1eef3.
