### ISSUE TITLE
Larger input screen for writing 

### ISSUE THREAD

**Issue by Fab2100** [kontalk/androidclient#460]
A input screen which grows if the text gets longer would be nice. 
There are only three lines at the moment. A growing text field would be great.

**Comment by daniele-athome** [comment]
I'm not really keen to increase the max number of lines in the text entry. I mean Kontalk is an instant messenger, so **short messages**. Also, the more space you give to the text entry, the less space you have for the rest in the layout. If you can give me some valid reasons why it should grow longer than 3 times (which is **way beyond the average message size**) I could think about it.

**Comment by webratte** [comment]
If you start with 3 lines it could crow up to 6 or 7 lines. I very often write longe messages. And it's not easy to review the written text. 
If I write I must not read received messages. I have to control my currently written message.

The same should implement in Desktopclient ;-)

**Comment by webratte** [comment]
I think I was to fast. 
My comment is stupid :-\
More then 4 lines is not good I belive.
An of course you start with one line....

**Comment by Fab2100** [comment]
I think it is very difficult to scroll through a written message if it is longer than 3 lines, because of the small text field. 
I like it very much to see the whole message i have written before i press the send button. 

What do you think about the option to change the max number of lines of the text field? So every user can choose his preferred input method. 
For people who write usually longer messages this option would be a great improvement.

**Comment by Fab2100** [comment]
And if it grows automatically there would be no deterioration for people who usually write short messages.

**Comment by TheLastProject** [comment]
I think that the field auto-resizing would be great. As said before, people writing short messages will not be affected, and it makes it easier to scroll through longer messages. For what it's worth, WhatsApp auto-resizes the text input field when you type more.
