### ISSUE TITLE
Translate wiki pages for users

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#470]
It could be a good idea to translate all important wikipages. 
First only things like "Export personal key to another device".
Complicated things like server and so on is only for techs and can stay in  english I think. 

Or is this too much work (or maybe not enough webspace) for you.

If it translated you could implement a Help Button in clients.
And so, I think, you get not so much questions.

**Comment by daniele-athome** [comment]
Thanks @webratte, I've created https://github.com/kontalk/androidclient/wiki/%5Bde%5D-Export-personal-key-to-another-device for you to translate. Feel free to also edit the title but please leave the "[de]" language prefix.

I've opened #472 for the help button.

**Comment by daniele-athome** [comment]
For what is worth, I've opened wiki editing to public, so you can create other pages to translate too if you'd like. Just add the "[de]" prefix to the new page.

**Comment by webratte** [comment]
Thank you. I will start translation very soon.
And I will try translate all wikis I understand step by step.
To technical wikis I will not translate because I should first understand before I start work ;-)

**Comment by daniele-athome** [comment]
Thank you! If you need help understanding something, just write here (we could also improve something of the original pages this way).

**Comment by webratte** [comment]
I have just added ainitial  FAQ page to fill up from developers (they know the questions and answeres).
https://github.com/kontalk/androidclient/wiki/FAQ

I have not found a way to set anchors fo rpage  internal links to jump from question to answer :-/ So I made a simple ordered list
Feel free to delete this page if not needed.

**Comment by daniele-athome** [comment]
I've fixed the FAQ page a little thing, linking it to a new page called "Personal key" (under construction) where I explain some things about encryption and key pairs - in the most simplified way I could (also if you want to improve that, be my guest). I'll add more FAQs later when they come to my mind, you can do the same if you want @webratte, I'll review them then.

**Comment by daniele-athome** [comment]
I'm moving this to 3.0.2, we don't need to complete it tomorrow anyway.

**Comment by TheLastProject** [comment]
Dutch is done so far. Is there any way to be notified when it should be updated, like Weblate mails me if there is something new to translate?

**Comment by daniele-athome** [comment]
Well, not easily for the project. However you can use RSS: http://stackoverflow.com/a/8573941/1045199

**Comment by webratte** [comment]
@daniele-athome Will you automatical informed if I chage something in english pages?

Currently I have added a new question into FAQ and enhanced the part " It is used to authenticate you" with "and encrypt messages to you"

**Comment by webratte** [comment]
@TheLastProject I use http://sneakypete81.github.io/updatescanner/ in firefox to be informed if there are changes on a page. 
Of course It works only if I start firefox. But it's better then nothing ;-)

**Comment by daniele-athome** [comment]
Thanks @webratte, I've answered to the last question.

**Comment by webratte** [comment]
@daniele-athome Your page about personal key is easy to understand :+1: 
But a other thing: What means: "delete your account and register again from **scratch**" by your answer in FAQ?

**Comment by daniele-athome** [comment]
It means unregister and register again, recreate your account in Android, much like if you'd uninstall and reinstall (you remove the account from Android settings or from within the app itself, there is a preference "Delete your account"). How can we explain that?

**Comment by webratte** [comment]
> How can we explain that?

@daniele-athome I have just added a suggestion. can you please take a look on it?

**Comment by daniele-athome** [comment]
I've fixed grammar but it's fine, thank you.

**Comment by webratte** [comment]
I have another question.
I don't understand "it tries 10 times using **exponential backoff**"
can you please explain "**exponential backoff**"

**Comment by TheLastProject** [comment]
Exponential backoff means that the waiting time in between grows faster and faster. A simple example of exponential backoff in waiting would be:
Wait 100 seconds
Wait 110 seconds
Wait 121 seconds
Wait 134 seconds

**Comment by daniele-athome** [comment]
Thanks @TheLastProject. I've linked the term to its wikipedia page at https://en.wikipedia.org/wiki/Exponential_backoff.

About technical pages: please do not translate technical pages such as Development rules, Eclipse tutorial page, XMPP estensions and so on, because they are maintained by me (and they will change often) and don't need another language other than english actually (developers should be able to speak english anyway otherwise it can be a problem to communicate :-).

**Comment by daniele-athome** [comment]
I'm closing this issue for now. I removed the "under construction" notice from all pages - we can always add content later - it's fine enough for release now. Thanks for the help!!!
