### ISSUE TITLE
Voice playback stops when screen is rotated

### ISSUE THREAD

**Issue by svrnwnsch** [kontalk/androidclient#473]
When I play a voice message, the playback stops when the mobile phone gets rotated. Playback should continue.
Also while playback the screen should not get turned off automatically, as this also seems to stop playback.

**Comment by daniele-athome** [comment]
Seems fair. Screen rotation is hard to handle in Android, especially when you have to keep state :-)

I've opened #474 for the second bug.

**Comment by daniele-athome** [comment]
Use AudioFragment to play audio and drop internal MediaPlayer istance.
