### ISSUE TITLE
Offline warning

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#481]
Much like having a contact blocked, it would be useful to have a yellow warning if you are currently offline (with the "Go offline" option in the menu), as a reminder before you send a message (currently, you only get a toast when you actually try to send a message).

**Comment by daniele-athome** [comment]
I think we are beginning to abuse the warning bar :-)
I'll add the same warning bar to the conversation list window, but not in the composer itself: the bar there is used for contact-specific warnings.
