### ISSUE TITLE
Remove temporary code to delete .nomedia from pictures folder

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#486]
Counteract #479 since it's a workaround.

**Comment by webratte** [comment]
I think this code should stay more then one Version because some users will skip one or two versions.

Don't you think so?

**Comment by daniele-athome** [comment]
In a normal situation, yes. However this is a fix that modifies a user's action (e.g. the user might have created the .nomedia file on purpose). I'll see how long 3.0.2 will last and, if needed, I'll delay this to 3.0.4 or 3.1 (whichever comes first).
