### ISSUE TITLE
Rename "threads" to "conversations" in strings

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#487]
"Threads" is really more of a tech term. However, "conversations" is longer.

**Comment by TheLastProject** [comment]
If "conversations" is too long, "chats" may be a clear enough alternative

On 2 July 2015 14:17:35 CEST, Daniele Ricci <notifications@github.com> wrote:
>"Threads" is really more of a tech term.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/487

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
You're right it is, thanks!

**Comment by abika** [comment]
Yep, "chats" is good. Will do /Thread/Chat/g also for the Desktop client.
