### ISSUE TITLE
support push messages without gcm with websockets

### ISSUE THREAD

**Issue by pravi** [kontalk/androidclient#490]
This would give better experience for users who prefer not to share metadata with google (fdroid users).

**Comment by TheLastProject** [comment]
As described in another ticket that I can't find back somehow, just set "disconnect when idle" to "Never", which has the same effect.

On 3 July 2015 07:54:55 CEST, Praveen Arimbrathodiyil <notifications@github.com> wrote:
>This would give better experience for users who prefer not to share
>metadata with google (fdroid users).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/490

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
Thanks @TheLastProject, that's the right answer.
