### ISSUE TITLE
Bad key warning after switching conversation too quickly

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#493]
Sometimes, when I switch a notification too quickly, I get the red warning that my contact is using an unknown key. This happens as follows:
1. Get notification for conversation 1
2. Type message in conversation 2
3. Press send
4. Click notification before the message has been sent
5. A bad key warning appears on top of conversation 1

If I leave the conversation and go back, the bad key warning disappears. I assume that this is a race condition where Kontalk doesn't check if the message sent is sent to the current contact.

**Comment by daniele-athome** [comment]
Thanks for reporting. It might actually be related to the reuse of the compose message activity among chats. I'll do some tests to reproduce.

**Comment by TheLastProject** [comment]
While this issue remains very uncommon, I just managed to accidentally reproduce it on version 3.1-beta2 on my new phone, a Motorola Moto E 2015 running CyanogenMod 12.1 (Android 5.1.1).

**Comment by daniele-athome** [comment]
I think I fixed this in 2da46ec, thanks @TheLastProject.
