### ISSUE TITLE
ask user for key backup

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#499]
Ask user for backup the personal key after key is generated.
Maybe show a info like "If you store this backup on your PC or other external device you can restore your Kontalk Account if you change your phone. ... You can also use this backup to use Kontalk on other devices (Maybe a link to wiki)

It's just a idea that "non techs" not always create new accounts by receiving SMS.

What do you think?

**Comment by daniele-athome** [comment]
Thanks, I've "extended" #483 to include this need.
