### ISSUE TITLE
Don't start registration without Internet connection

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#500]
As you need an Internet connection to start using Kontalk, Kontalk should tell you to enable WiFi or 3G instead of the new registration screen on first start, if it is not already enabled. Currently, you can fill in your registration information and submit it, causing Kontalk to just show a registering progress indicator which can't ever complete.

**Comment by daniele-athome** [comment]
Good finding, thanks.

**Comment by TheLastProject** [comment]
Alternative, simpler solution: Simply show a toast (or dialog?) saying "An active Internet connection is required to register for Kontalk. Please activate WiFi or 3G and try again".

**Comment by TheLastProject** [comment]
The same goes for a key import, by the way.

**Comment by daniele-athome** [comment]
Fixed, but still **untested**.
