### ISSUE TITLE
Add build instructions in documentation

### ISSUE THREAD

**Issue by strk** [kontalk/androidclient#502]
Like it's done for the desktop client, it would help to have build instructions for the android version.
It's very rare to find them for free android apps, which makes it hard for me to start contributing (as a developer).

**Comment by daniele-athome** [comment]
https://github.com/kontalk/androidclient/wiki/Setup-Android-Studio-project is a bit old, but it's a start. I'll fix it as soon as I have the time. I'll also create a page for gradle-only builds - in the meantime if you want you can start to write it :-)

**Comment by strk** [comment]
I was thinking more of an headless way to setup. I'm used to vim and Makefiles... Guess gradle is the equivalent approach for java ?

**Comment by daniele-athome** [comment]
Yes Gradle is a build system for Java.

**Comment by strk** [comment]
does the android app also require JDK8 ? ( see https://github.com/kontalk/desktopclient-java/issues/31 )

**Comment by daniele-athome** [comment]
I don't think so. And I've never used a JDK 8 feature in the app, so: no.

**Comment by daniele-athome** [comment]
I've fixed Android Studio setup page and created a new one for headless building: https://github.com/kontalk/androidclient/wiki/Build-instructions (absolutely UNTESTED (sorry, had no time), you're welcome to test it and report any bug here :-)) I'm closing the issue for now.
