### ISSUE TITLE
Could not find method jcenter() for arguments [] on repository container

### ISSUE THREAD

**Issue by strk** [kontalk/androidclient#503]
Build procedure I tried:
```
git submodule init
git submodule update
gradle run
```

What I obtained in the last step:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/usr/src/kontalk/androidclient/build.gradle' line: 4

* What went wrong:
A problem occurred evaluating root project 'androidclient'.
> Could not find method jcenter() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.362 secs
```

Ubuntu 14.04.2 LTS
Gradle 1.4
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
Ivy: non official version
JVM: 1.7.0_79 (Oracle Corporation 24.79-b02)
OS: Linux 3.13.0-44-generic amd64

**Comment by daniele-athome** [comment]
You must use the internally provided gradle script:

```
./gradlew build
```

(there is no `run` method: an Android app can't run on Linux/Windows).
Be sure to set ANDROID_HOME environment variable to your SDK installation path beforehand.

However it won't produce a valid apk: it still needs to be signed. I'll provide the steps on a wiki page.

**Comment by daniele-athome** [comment]
@strk please use kontalk-devel@googlegroups.com for these kind of discussions. This bug tracker is meant for analyzing and discussing bugs, not individual build issues. Thanks.

**Comment by strk** [comment]
Thanks, will do (once I find it, see #503). It'd be also instructive to read some mail from the archives.

**Comment by daniele-athome** [comment]
Sure. Here it is: https://groups.google.com/d/forum/kontalk-devel
I'll add that as part of #504.

**Comment by strk** [comment]
Uhm, it takes a google account to subscribe  ?

--strk;

**Comment by daniele-athome** [comment]
No, you can use any email account. See here: http://blog.neowork.com/how-to-subscribe-to-a-google-group-without-a-google-account/

**Comment by HernandoNJ** [comment]
I had the same trouble. In my case, it was a newie mistake. Maybe it could be helpful for anyone. I reverted the code from the one I changed to the original one.

The code as I changed it:

buildscript {
    ext.kotlin_version = '1.2.71'
    repositories { google()  jcenter()
    }
The original code:

buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
    }
