### ISSUE TITLE
Synchronize key trust settings

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#505]
Find a way for clients to communicate with each other and pass along their public key trusting information (or maybe store it into the roster?). Best option is to include it into kontalk-keys.zip.

UX note: distinguish "unknown key" from "changed key".

**Comment by strk** [comment]
+1 for including in kontalk-keys.zip -- meanwhile the lack of contact keys would be better signalled as "missing" rather than "changed" (the latter is a confusing message)
