### ISSUE TITLE
User location sharing

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#51]
_From [daniele.athome@gmail.com](https://code.google.com/u/daniele.athome@gmail.com/) on May 28, 2013 10:31:24_

Send user location using XEP-0080: User Location http://xmpp.org/extensions/xep-0080.html

_Original issue: http://code.google.com/p/kontalk/issues/detail?id=85_
##

**Comment by TheLastProject** [comment]
For OpenStreetMap support, it may be useful to look at [the source code of Where Am I](https://bitbucket.org/edunivers/whereami/src), an Android app made to show where an user is displayed on OpenStreetMap. It hasn't been updated in a year, but may still give some useful hints. (I don't know the app, randomly stumbled upon it on F-Droid, I can't vouch for the code quality or usefulness)

**Comment by TheLastProject** [comment]
https://github.com/osmdroid/osmdroid seems to be the library it uses. It markets itself as a replacement for Android MapView so hopefully has a similar API

**Comment by daniele-athome** [comment]
Thanks, I'll check them out.

**Comment by h-2** [comment]
Liberario (the free bus/tram application for almost all places in the world) uses https://github.com/grote/OSMBonusPack

**Comment by karlitos** [comment]
Hello,

may I ask what is the current status of the location sharing ?

I think it would be great if the user could choose from different map providers  when choosing/displaying the location. (Google maps, OSM, HERE maps ...) I am asking this because I work for HERE and our Android devs could maybe help with this task.

**Comment by daniele-athome** [comment]
Hi @karlitos, we currently had some work done in two branches: `position` and `xmpp_position`, with different parts that were made for the old protocol and for XMPP. But they are so old and the code was so much refactored that those branches are now useless (besides, it was just a very small prototype and it was hard-coded to Google Maps).

The idea is to offer an activity (or a dialog for tablets) to choose a location (or a POI that can be searched) from. But the whole thing would have to be developed, not only support for HERE maps (and as you said it should have support for multiple maps providers). Your help in this would be much appreciated, but I don't know how much effort you can allocate.

**Comment by daniele-athome** [comment]
Awaiting review and merge at #1027.
