### ISSUE TITLE
provide better error message if network connection fails (firewall blocks) and offer kontalk service on port 443

### ISSUE THREAD

**Issue by pravi** [kontalk/androidclient#514]
Phone is lenovo a6000. Tried both play store version and fdroid version. Its my friends phone. It fails with an error with no option to fallback to voice.

**Comment by TheLastProject** [comment]
"with an error"? Which error, exactly? Any chance you could get a logcat?

**Comment by pravi** [comment]
The issue was not with android version but firewall. After switching from local wifi, which heavily blocks services, to mobile data, verification worked. Does verification service use a non https port? Can there be a better error message if connection failed?

**Comment by pravi** [comment]
Many organizations block ports other than 80 or 443 (blanket port ban). Would it be possible to tunnel traffic through 443? Some vpn services do it to by pass blocking of openvpn port (1194).

**Comment by daniele-athome** [comment]
Well Kontalk servers do have port 443 open for direct SSL connections, although the Android client isn't ready for that yet. This requirement is covered by #302.

**Comment by daniele-athome** [comment]
In the meantime, I've opened #516 to support direct SSL connection without proxy in case of problems.
