### ISSUE TITLE
"Hold mic to record" hint when clicking or pressing mic shorter than 800 ms

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#515]
Give the user a hint.

**Comment by TheLastProject** [comment]
This doesn't seem to work for me on the 3.0.2 released on F-Droid. It only vibrates on tap, but doesn't show a toast.

**Comment by daniele-athome** [comment]
Thanks @TheLastProject, I'll verify on a 5.1 emulator later.

**Comment by daniele-athome** [comment]
I can reproduce another race condition relating to this, but not your bug. Can you confirm the steps to reproduce? Just click on the mic for < 800 ms at the first time shows no toast at all?

**Comment by TheLastProject** [comment]
Indeed, just tap quickly. The mic vibrates, but no toast appears.

**Comment by TheLastProject** [comment]
I just realized the hint does appear if you hold the microphone long enough for the REC text to appear, but not when shorter than that.

**Comment by daniele-athome** [comment]
That's actually very helpful, I might know how to fix it. Thanks.
