### ISSUE TITLE
How can i setup my server ?

### ISSUE THREAD

**Issue by geass** [kontalk/androidclient#520]
I want to make an app base on Kontalk, i setup openfire and changed uris on Kontalk settings . But im getting that error :

Trust anchor for certification path not found

What i should setup to my server ?

**Comment by daniele-athome** [comment]
Kontalk is not designed for any standard XMPP server; we have some extensions that need to be installed as well. Those extensions are only for the Tigase XMPP server.
For these kind of questions please use our Google group kontalk-devel@googlegroups.com thanks
