### ISSUE TITLE
Very long messages cannot be send

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#521]
The bugfix for #460 caused a regression, making it impossible to send extremely long messages, as the input yield scales up in such a way that the send button (also the smiley button) ends up outside of the screen.

**Comment by TheLastProject** [comment]
Field, not yield. GitHub's mobile site doesn't let me edit messages...

**Comment by TheLastProject** [comment]
This does not happen when the Enter button is set to send, the input field never scales then and always stays a single line.

**Comment by daniele-athome** [comment]
I don't understand. The send button is fixed to the bottom of the screen, even when the text fields height increases. I've tried on Android 2.3.7 and 4.4. Can you show me a screenshot please?

**Comment by TheLastProject** [comment]
That is weird, I can't reproduce it now, not even with the exact same text. Guess it was a one-time fluke. Closing this until I find a way to reproduce.
