### ISSUE TITLE
Inform user about new version

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#522]
In current version I will informed if my chat partner used a older kontalkversion:
(Yello banner: Your buddy is using an older version of Kontalk. Some features might not work correctly.)

What do you think about inform the other person the same way like:
A new version of Kontalk is available. You should update to get all new features and bugfixes.

I think users will faster update this way!?

**Comment by TheLastProject** [comment]
The problem with that is that a new version may not always be available. For example, F-Droid tends to update a few days late. On top of that, basically everyone has Google Play, F-Droid, Aptoide or whatever, which notify on updates. The people who don't update simply don't want to update, another note won't have any real effect on them and could confuse many with slowly-updating app stores.

At least, this is what I believe to be the case.

On 25 July 2015 21:07:17 CEST, webratte <notifications@github.com> wrote:
>In current version I will informed if my chat partner used a older
>kontalkversion:
>(Yello banner: Your buddy is using an older version of Kontalk. Some
>features might not work correctly.)
>
>What do you think about inform the other person the same way like:
>A new version of Kontalk is available. You should update to get all new
>features and bugfixes.
>
>I think users will faster update this way!?
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/522

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by webratte** [comment]
OK, that sounds correct.

And I need still the information if my chat partner used a older version so I know that some features possible not work.

@daniele-athome If you think like @TheLastProject (and now I also to) feel free to close this issue :-)

**Comment by daniele-athome** [comment]
I agree with @TheLastProject :-) for the moment I won't second this request, sorry.
