### ISSUE TITLE
Key import failed

### ISSUE THREAD

**Issue by ezeenova** [kontalk/androidclient#525]
After wiping and reinstalling my phone, I am unable to import the kontalk-keys.zip file. The password dialogue never appears; instead I am told that "Personal key import failed." I put the kontalk-keys.zip file in /storage/sdcard0/, which is the same location Kontalk put it in when I originally exported it. I have also verified the file's checksum every time I moved it.

I'd rather not upload the file, as I'd like to keep using the key if possible.

**Comment by daniele-athome** [comment]
Thanks for reporting. It might be related to the old key format (what's your original registration date or app version? We can also check by looking at the public key - kontalk-public.asc, can you send that to us please?)

**Comment by ezeenova** [comment]
I don't remember exactly when I first registered, can I see that within the app somehow? I believe the first version I installed was v3.0-beta7.

This is my public key:
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v@RELEASE_NAME@

mQENBFT3WgMBCADwlbnD0wsGSnVZOVBn3i/cNnWhqvivunZZ94CfhQAvHePoWrZ6
4IxvWZrQHIAhjMHsy3Tjr4YSEVzCtzJ5vmbjyqd6jaY0KMhNhpENxaO5J3cAmM9N
WsO8GacCxvxwUKlUlqNswMpuORKdKeiM2osA/tkctyFP4gBOF9bsRBdLVAVi1nfR
9+R2767CyERcRsha6HGh3kcSlh1qHMBI9kZN9wABqooyQIfMYW1bOBwb+Evg6jLs
xdnZHj94ooXbk217vkRl5CfaP8dWWR6Rjdu9ZSOZ5AGnhVTz1Sq4yz6ZxgHsQogU
mM/QZc9F+eXnWSJNeIUTw+rPLmVRb8SfuuWVABEBAAG0TUFsZXhhbmRlciBCZXNz
bWFuIDwyMTRmNjk0MjU5MGVjMzhjMGZiMzg4MzUwMTgxYWVjMGM5NjIzM2RlQGJl
dGEua29udGFsay5uZXQ+iQEcBBMBAgAGBQJU91ogAAoJEFsk61/zXRHbIokH/Agl
fh+KX18sThoU+DxYw/cf6Gq0u+jqrLNuDKsaSscyhJseTKKBeUQ9FY2X/2GM/6/f
GIyND2xed8kOQC5gzFe2VeD5Gz1GmELct9ksSJGtsCkYsUUCkGDqXz4TU8uQhT9L
2PSmqpBq8DWvpUdnp4dL4NYXinVlzQmkTYKisGJCqM361qohiNY7kiLIsFvWXroK
gHmAeLKjwhkLuzxEA7fnrXBRDDUl+uunmHUwjvo5HxO0zOVa6/uduqDbOEW/Kkzh
oSaZdHtnJ0s9+omkwBRYeIxhr9wpiRnCgc3WeCPVnqQcW2nlXSgyT4bPg5gZz3nU
vNnW1XThQle2gyZA4ciJARwEEAECAAYFAlT3WiMACgkQ5l6+6GhiwwDznwf/a4hs
pKFrpDLYOHm20u32f+Qj4tpoyZm/rEddc8UyOSq7gGhOix8Em8Wa3ugKnSkuHyVO
Zab5UBhToLi2O3DgKl0kf/ecH9oHEAZV84UXe3t5o250Nq6x2uPMFrPEO6GIVJQt
gLK4eugcL5KAjxskF9QMMc7nOwcYM9FuCLT+A7Rw5TpL0S6Xrhh3BJVCWWwiu6+v
3rVuDlRKqjZQcGB+OY2QTebawjSV2qjwzHn3KFWNRPtnMc11KTigUgK+Lc2d3GmZ
doGyTszw4WNjnHpboUpDPVprGyjD/1wjVZeQviriYGrOmCRH1CMKhkWbm1T8uaUL
fYjaERW7WaZjf7TWUbkBDQRU91oAAQgA2enO9XUSRBIjzW1Ee1VmzNA06kW/PG5v
YDaAIt8qercJ9lj+TsoC33zLQhM6YFRqsCsS0cIuol5sob/aVLTQjWZKNyqvA0NX
ZNrpcG/7aCulqnR1vUNeGcog21TjSd1ZJgyazEVpKcCoEEbA3KaJprBHkCmKJb+d
1S4ae3wL1okDKOvhvRvCfHYys2YX05eWYKMiDndBuFzh16CDewD3uWffAXgaNL2c
6M1oypuPvLlJpdYhvMp/miOcuXTAVZ7Iy6kktkBap1upvqNWu3uOn+Ff8kz5ZJYk
dPQWxXTzcy4nZzUJFbNJ00GFO5gk74V2rdf5JYZEu6KEIY8MmbczwwARAQABiQEc
BBgBAgAGBQJU91ogAAoJEFsk61/zXRHbun4IANF3kgOZtnANDOIdadGgyZKa+wSZ
3REV3sudJEXZ6QErrwxfa/NB+oqFDZ5tclybw3NsfO8annnmBNKIHeVLkrBt6WLO
fZeC80mlim90tlQA3S+chY17LXzyPNEmklGzXGiFcbkYuP2SrBcee58j3NrEMxiK
RJEh/J2raP1DW/IrX7Sl/HCdEZKM2UPmQi9w1q4kOhl4FmGs2dXM2dqb60K6D7SW
mExfGa9xENayJ1Zwu6mWOiJqTRliE66EHXaLhJvks8l+zdTfJc6aG19zLihIoonk
SYQFD6ukraePQD1EHBcQwyijzxZtBsUD1iB5KQgAvSKT7Wkg2bXKo8SXZgk=
=A1nr
-----END PGP PUBLIC KEY BLOCK-----

**Comment by daniele-athome** [comment]
That's an old key format, but it should work. Any chance you can also provide a system log for analysis? Thanks.

**Comment by ezeenova** [comment]
https://gist.github.com/ezeenova/e6959d3100dda72035c3

**Comment by daniele-athome** [comment]
Thanks, I'll try to make some tests by generating an old-format key and get back to you. It may take a few days because of other tasks, sorry.

**Comment by ezeenova** [comment]
You can go ahead and close this if you'd like, since it seems like it was a one time thing that won't affect current or future versions of Kontalk. I've long since switched to a new key, so importing the old one is no longer necessary.

**Comment by ezeenova** [comment]
Oh hey, I can close it myself!

**Comment by daniele-athome** [comment]
Sorry but the task had low priority since it's a legacy thing and I'm already having trouble handling the high priority stuff :-( I'm glad you overcame it though.
