### ISSUE TITLE
Key import but I still receiving a SMS

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#527]
Samsung Galaxy Mini 2 (whitout a SIM Card)
Android 2.3,6
Kontalk 3.0.2 (Playstore version)

What I do:
* Copy the Key to the phone
* Put my phonenumber (from the mainphone with SIM Card) into the field.
* press menu->import key
* the password window appears
' enter my password
* press OK

Now the information is shown "Requesting verification code SMS…".

I receive a code on my mainphone.

Here I stopt it because I think there will generated a new code. And that is not what I want. 

But I think if I import the key there should not be a request for a new code?!

**Comment by webratte** [comment]
OK, I have just tested a few things.
The key I used was a older key.

With the new key it works fine.
But will the key import is running ther still is a window  "Requesting verification code SMS…"

Maybe you should align that.

**Comment by daniele-athome** [comment]
Yes that was the issue and yes, that's message is not exact. I've opened #529.
