### ISSUE TITLE
own phone number

### ISSUE THREAD

**Issue by beli3ver** [kontalk/androidclient#536]
Is it possbile, that on the contacts panel my own number can be display none.
It is really annoying but I must have my own contact card to send it to customers.

**Comment by TheLastProject** [comment]
There are mixed feelings on this by different users. I know a fair amount of people who like having their own number in contacts and who use it to send notes to themselves.

**Comment by beli3ver** [comment]
Maybe a option in zhe settings

**Comment by daniele-athome** [comment]
I really don't understand from the original post if @TheLastProject got your request right. Are you talking about Kontalk showing your own number entry in the contact list?

**Comment by beli3ver** [comment]
Yes, thats what I mean.
It would be great, that there is an option to set it to display none

**Comment by daniele-athome** [comment]
I see it as an advantage: XMPP allows you to have multiple resources connected, so you would want to communicate something between devices sometimes. I'm sorry I'm not seeing any real advantage on creating one more option to alter this behaviour.
