### ISSUE TITLE
Service request

### ISSUE THREAD

**Issue by Azharbagh** [kontalk/androidclient#537]
Dear All,

i am new here and i want to request one service request if someone can help me to make service script which can i use on kontalk android app please

**Comment by daniele-athome** [comment]
Hello,
I really don't understand what you're talking about, sorry. What kind of service script do you want to run within Kontalk?

**Comment by Azharbagh** [comment]
its like gotext you ever use gotext or you know about that?

**Comment by daniele-athome** [comment]
Kontalk is nothing like Gotext. Gotext was a service to send SMS through external carriers. Kontalk is a internet-based instant messenger, sorry.

**Comment by Azharbagh** [comment]
oh i see.. so to use Kontalk must need other one also installed Kontalk?

**Comment by daniele-athome** [comment]
That's right.
