### ISSUE TITLE
implement axolotl/omemo for xmpp compatibility

### ISSUE THREAD

**Issue by pravi** [kontalk/androidclient#538]
As discussed in #492 , axolotl would be useful for kontalk compatbility with xmpp. Conversations released version 1.6.0 with axolotl support (called omemo) today. They are drafting an xep already. Since code for this already exist, I think it would be easy to implement.

**Comment by h-2** [comment]
:+1:
This would be super great and eliminate all "but foobar is more secure that Kontalk" claims.

**Comment by iNPUTmice** [comment]
some general information about OMEMO and links to the XEP can be fonud here: [conversations.im/omemo](http://conversations.im/omemo)

**Comment by daniele-athome** [comment]
Thanks @iNPUTmice, I'll take a serious read at that as soon as possible.

**Comment by pravi** [comment]
@daniele-athome see https://github.com/LibreSignal/LibreSignal/issues/10#issuecomment-198814605 I think implementing this feature can convince some LibreSignal contributors to join kontalk instead.

**Comment by daniele-athome** [comment]
Thanks for the feedback @pravi.

**Comment by daniele-athome** [comment]
Merged into #132. Set for release 3.3 for now (no precise estimate though).
