### ISSUE TITLE
No notification on active conversation with screen off but unlocked

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#549]
How to reproduce:
1. Disable screen locking
2. Switch to conversation
3. Turn off screen
4. Let the person who you're in a conversation with message you

Expected result:
New message notification

Actual result:
Silence

This only happens when there is no screen locker configured. If you use PIN/Pattern/whatever locking Kontalk will notify you just fine.

**Comment by daniele-athome** [comment]
Thanks for reporting. I can't remember if you're still using the material version or not... What version has this bug?

**Comment by TheLastProject** [comment]
I reproduced it on both 3.1-beta1 and 3.1-beta2. I'm not sure if it's a material issue, but it at least happens on material

On 19 September 2015 18:09:37 CEST, Daniele Ricci <notifications@github.com> wrote:
>Thanks for reporting. I can't remember if you're still using the
>material version or not... What version has this bug?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/549#issuecomment-141684001

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
Unable to reproduce on Android 4.4. I'll try later on a 5.1 emulator - probably a behaviour change in focus or activity lifecycle was introduced with Lollipop.

**Comment by TheLastProject** [comment]
I forgot to state, I reproduced this on Android 5.1.1, on two different devices. My bad!

On 22 September 2015 14:25:23 CEST, Daniele Ricci <notifications@github.com> wrote:
>Unable to reproduce on Android 4.4. I'll try later on a 5.1 emulator -
>probably a behaviour change in focus or activity lifecycle was
>introduced with Lollipop.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/549#issuecomment-142272436

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
@TheLastProject I've fixed some stuff related to this issue with 3.1.2, please try it out and let me know if you can still reproduce this.

**Comment by TheLastProject** [comment]
It seems this bug still exists. I reproduced it by setting "Automatically lock" to "30 minutes after sleep" and disabling "Power button instantly locks", then starting a conversation with myself, sending a picture and immediately pressing the power button to turn off (but, because of the settings, not lock) the screen and waiting for a notification, which simply didn't come.

I will try to test later with a second device to make absolutely sure, as this way of testing obviously could have timing-related false positives, although I tried to minimize the risk of these by sending a picture.

**Comment by daniele-athome** [comment]
Thanks @TheLastProject, I'll do some more tests on my side with the latest version.

**Comment by TuningGuide** [comment]
I also got the problem of no notifications when sceen is off with version 3.1.2 (Fdroid) on Cyanogenmod 12.1 (5.1.1). All options under notification settings are activated (led, vibrate, sound)

**Comment by TuningGuide** [comment]
#80 is this issue related? Even if it is quite old.

**Comment by daniele-athome** [comment]
Thanks @TuningGuide, no #80 is not related (that was an app configuration error).

**Comment by daniele-athome** [comment]
I don't know what else I can try to reproduce this. I will continue researching on the Internet for similar issues but is not going to be easy if I can't figure out how this happens.
@TheLastProject can you provide a logcat of this behaviour please? It would really help to figure out the issue. @TuningGuide the same for you: if you can provide a system log it would be greatly helpful.

**Comment by daniele-athome** [comment]
Resurrecting old thread :-)
@TheLastProject any news on that log? That is, if the issue still occurs.

**Comment by TheLastProject** [comment]
Sorry, forgot all about it. I used ["adb logcat | grep `adb shell ps | grep org.kontalk | cut -c10-15`"](http://stackoverflow.com/a/24410415), giving the following output:

```
E/SQLiteLog( 1267): (2067) abort at 28 in [INSERT INTO threads(encrypted,mime,status,msg_id,timestamp,peer,content,direction) VALUES (?,?,?,?,?,?,?,?)]: UNIQUE constraint failed: threads.peer
V/ComposeMessage( 1267): marking thread as read
W/art     ( 1267): Long monitor contention event with owner method=int org.kontalk.provider.MessagesProvider.update(android.net.Uri, android.content.ContentValues, java.lang.String, java.lang.String[]) from MessagesProvider.java:667 waiters=0 for 401ms
```

**Comment by daniele-athome** [comment]
Just those 3 lines of log?
Can I send you an apk (with a different package name) with a few more debug logs to help me with this?

**Comment by TheLastProject** [comment]
Well, the logging style may not be perfect, but sure.

On 21 March 2016 20:32:23 CET, Daniele Ricci <notifications@github.com> wrote:
>Just those 3 lines of log?
>Can I send you an apk (with a different package name) with a few more
>debug logs to help me with this?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/549#issuecomment-199441350

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TheLastProject** [comment]
After testing this more and comparing several apps, it seems no app actually manages to get this right and WhatsApp works around this by always playing a small sound on receiving/sending a message, like described in #75. I'll close this issue in favour of #75, because I consider that a sufficiently decent workaround.

**Comment by daniele-athome** [comment]
I think it's issue in Android activity lifecycle here: onPause and onResume don't get called because there is no lock screen to cover Kontalk's activity. However, this happens only on some devices.

Thanks @TheLastProject for your patience and help with this.

**Comment by TuningGuide** [comment]
My HTC notifies me now. But the Sony Stock Rom (5.1.1) of my girlfriend does not. Booth tested with Kontalk 3.1.3

**Comment by daniele-athome** [comment]
@TuningGuide with the same conditions? No screen lock configured?

**Comment by TuningGuide** [comment]
Oh, you're right I configured a screen lock on my HTC.

**Comment by daniele-athome** [comment]
@TuningGuide ok it might be another issue than.
About the Sony device: please note that there is an interval between screen off and screen lock (usually it's 3 to 5 seconds depending on the firmware) during which this problem might occur. Is this your case? Can you test it please?

**Comment by TuningGuide** [comment]
Booth phones were unlocked and display active.

**Comment by daniele-athome** [comment]
Ok so that's not covered yet. Please refer to #75 :-)

**Comment by TuningGuide** [comment]
It turned out that my girlfriend had "Benachrichtigungen anzeigen" (show Notifications) disabled in Settgins -> Apps -> Kontalk. :trollface:
