### ISSUE TITLE
App crashes after current update (3.0.5)

### ISSUE THREAD

**Issue by duff-y** [kontalk/androidclient#550]
After updating the application via f-droid to v.3.0.5 it crashes immediately after starting with the following message: "Kontalk" has ended.

Any suggestions what I can do in this case? Until this update everything worked fine on my GT-I9195 with CM 12.1.

If you need more information, don't hesitate to ask me (:

**Comment by abika** [comment]
there was a bug in 3.0.5, already fixed with [3.0.6](https://github.com/kontalk/androidclient/releases/tag/v3.0.6). Better downgrade to 0.4 until 0.6 is available in F-Droid

**Comment by duff-y** [comment]
Wow, that was a quick response. Thanks a lot, I'll give it a try.
