### ISSUE TITLE
New material balloons

### ISSUE THREAD

**Issue by breversa** [kontalk/androidclient#551]
Hi,
I've started using Kontalk just before the Material theme came out, and when it did, I noticed that contrary to the Classic theme, the speech bubbles lack background, making message exchanges a bit less comfortable to read. Background color (+ shadow) would a welcome addition.

Also, messages in the Classic theme only take half the width of the screen (rather fine on a 4" device with portrait display, but less so on a tablet with landscape display), hence creating narrower but longer message bubbles, as more new lines are needed.

**Comment by daniele-athome** [comment]
Thanks for reporting. Those balloons are just temporary, we plan to change them soon, probably something with a solid background color (not white :-). I'll use this issue to track changes.

**Comment by daniele-athome** [comment]
Closed in a127a860c0cd4ea42f3d9f7ea3e3e56efa325e4c.
