### ISSUE TITLE
Offline mode indicator

### ISSUE THREAD

**Issue by breversa** [kontalk/androidclient#552]
Is there any way to see whether I'm on/offline without opening the menu and checking whether the "go off/online" option exists ?

The title bar would be a very good place for a status indicator, whether text (e.g. "Kontalk (online)"), icon, or simply a color change (from blue to red, but think of the colorblind people ^^)… or a combination of them.

**Comment by daniele-athome** [comment]
Changing the background color or adding something to the title can help. I'll set this for the material design release.

**Comment by breversa** [comment]
Thanks for taking this into account !
I actually believe an explicit info (= word, not only color, or both) would be better, so that new users won't wonder "Why is the background color suddenly different ?"

**Comment by abika** [comment]
simply setting the title to "Kontalk (offline)" would be best imo, if not too long for very small screens

**Comment by daniele-athome** [comment]
Duplicate of #481.
