### ISSUE TITLE
Incorrect warning message on chat window about version

### ISSUE THREAD

**Issue by ffami** [kontalk/androidclient#555]
This is Kontalk version 3.1-beta2 on Android L via f-droid. The chat window shows a warning message that reads "your buddy is using an older version of Kontalk. Some features might not work correctly." when I can confirm both ends are on the same version.

**Comment by daniele-athome** [comment]
You mean 3.1-beta2 exactly?
I'm releasing a new beta this weekend, mind trying that first and get back to me if this happens again?

**Comment by ffayad** [comment]
Yes 3.1-beta2. 
Sure, will do. Thank you!
