### ISSUE TITLE
App icon gone after update with Play Store

### ISSUE THREAD

**Issue by abika** [kontalk/androidclient#556]
Friends reported this: After Kontalk was updated from the Google Play Store the app start icon for Kontalk was missing from the home screen. 

I'm using F-Droid, didn't experience this and so can't really say anything here. Maybe somebody else had this issue too?

**Comment by daniele-athome** [comment]
That's because the main activity class changed, the launcher intent is no longer valid and the home app deletes it.

**Comment by abika** [comment]
oh, and it was actually me who did it, right.) Good to know...)

**Comment by daniele-athome** [comment]
We both did, me right after you :P Don't worry, not a big deal.
