### ISSUE TITLE
Message details on tap

### ISSUE THREAD

**Issue by breversa** [kontalk/androidclient#557]
Hi,

I noticed that in Kontalk 3.1-beta2 (F-Droid version), I need to do the following to display a message's details :
- long tap on a message to select it
- tap the 3-dot menu icon
- tap "Message details"

That's a lot to simply check out (for instance) the message sent and receive times.

Here's a suggestion :
- single tap on a message display its details (like in CyanogenMod's SMS app)
- long tap behaviour remains unchanged

**Comment by TheLastProject** [comment]
While thinking of this a bit, the Telegram way of doing it, showing common options on a single tap, is most likely better, as it would make every action quicker, also sharing a message:
![screenshot_2015-10-03-14-42-42](https://cloud.githubusercontent.com/assets/1885159/10262937/22b4916e-69dd-11e5-80e0-fc54a47ea7ba.png)

In Kontalk's case, the options should probably be:
- Details
- Copy
- Share
- Delete

**Comment by breversa** [comment]
That's a good context menu indeed, however, I still think that short-tap should bring details, and long-tap that menu, as I much more often check details than copy/share/delete messages.

The reason is that I use the F-Droid version that does not support push, so I often want to make sure that I got the messages at the correct time.

**Comment by daniele-athome** [comment]
I think I'll stick with Google guidelines here (contextual action mode), and I'll implement single click with message details for text messages. I've actually thought of doing that a long time ago but always forgot to do it.

**Comment by daniele-athome** [comment]
Closed in bae80438ee4be531a6feb7ff7df66258577e3978.
