### ISSUE TITLE
UI improvement : display "[contact] is writing" above the message input box

### ISSUE THREAD

**Issue by breversa** [kontalk/androidclient#559]
Kontalk 3.1-beta2 (F-Droid version), when a contact is writing in a conversation, the message "is writing…" is displayed below its name, in the title bar.

However, new messages are displayed at the bottom of the screen (just above the "Tap to write" box).

So if you're expecting a reply from someone, your eyes keeps looking up and down between the title bar and the message list. Not that it's a big effort, but if "is writing…" could be written above the input box and replaced by the real message once it's received.
Some IM like MSN Messenger or Kopete did that, and it was quite comfortable. :-)

**Comment by TheLastProject** [comment]
Personally, I prefer it the way it is currently. The way you describe it, there either needs to always be some space left, or the messages need to be pushed up. The current way uses less space and is less visually jarring.

**Comment by breversa** [comment]
Yes that's true, especially on smaller-screened devices.
But for larger devices, it would only push the messages up one line. And even then, that line could use a smaller font to avoid wasting to much space.

**Comment by daniele-athome** [comment]
Thanks for reporting @breversa.
On tablets, Kontalk actually shows (it's not very aesthetically nice, I didn't put much effort on it yet) the online status and the "typing..." message at the bottom of the screen (below the messages, above the composer bar). But that's not suitable to mobile phones, sorry. Personally I hate when in Hangouts there are those items moving up and them because people start and stop typing.

**Comment by breversa** [comment]
Yes, I saw that the layout was different on my tablet, but since I didn't have the latest version (which somehow crashes on start), I didn't want to base my comment on it.

However, I don't get what you mean by "I hate when in Hangouts there are those items moving up and them because people start and stop typing."

**Comment by daniele-athome** [comment]
> Yes, I saw that the layout was different on my tablet, but since I didn't have the latest version (which somehow crashes on start), I didn't want to base my comment on it.

What version are you using on your tablet?

> However, I don't get what you mean by "I hate when in Hangouts there are those items moving up and them because people start and stop typing." 

Hangouts uses a small balloon with three dots inside to simulate a "typing..." notification, much like you're proposing.

**Comment by breversa** [comment]
I'm using v3.0.6 from F-Droid on a Samsung Galaxy Tab 3 8" running CyanogenMod 12 (unofficial).

I think I understand what you mean regarding Hangout. If the messages are moved up when the "typing…" balloon is displayed, then moved down if the contact stops typing, I understand it can be bothersome.

I think it could be avoided by creating a smallish placeholder empty line between the last message and the input box. The "typing…" notification would appear in that line.
That way, messages don't get moved up and down when the contact starts/stops typing. If the line is small enough (= same size as the time font ?), lost screen space can be minimal.

**Comment by daniele-athome** [comment]
That's what happen now in tablet UI in Kontalk too, but in the phone. I think it would be occupying a space reserved for the messages only.

**Comment by breversa** [comment]
What about providing a test version for phone only, since the code is already there ? :-)

**Comment by daniele-athome** [comment]
I'm sorry, I don't really have the time. Besides, the tablet online message mode was a temporary hack because I didn't know anywhere else to put it (and it's pretty ugly too); it needs to be redesigned anyway.

**Comment by breversa** [comment]
Alright, it's not a dealbreaker anyway.
Feel free to ask me if/when you need help testing it. :-)

**Comment by daniele-athome** [comment]
Sure, thanks!
Please don't take it personally, but I'm pretty much alone on this project right now, and I tend to exclude or delay whatever is not absolutely necessary or wanted or less important (I know importance is a personal thing, but since I'm alone... :-) )

**Comment by breversa** [comment]
Of course I do not take it personally ! You're single-handedly doing an awesome job providing an IM solution that does not rely on a closed third-party provider like Facebook AND does not require yet another login/password to remember ! :-D

I'd like to help contribute to the code, but my dev years are far now, before Android even existed, so the least I can do is test the app, report bugs, heavily encourage my friends to use it… and THANK YOU for what you do !
