### ISSUE TITLE
Warn user when trying to go back from code validation screen

### ISSUE THREAD

**Issue by muzirian** [kontalk/androidclient#560]
Pressing back or home button on android to minimize the app during registration cancels the registration.
But when i tried registering again for the same number it said it was once registered.
![1444029183142](https://cloud.githubusercontent.com/assets/14972525/10274760/b14bc96a-6b5e-11e5-9f3d-d6ec89cefd73.png)

Screenshot of screen whete i tried to minimise, but it also happened on previous part of registering screen as well

**Comment by daniele-athome** [comment]
Thanks for reporting. This is actually the intended behaviour: going back is going back, canceling registration. To exit Kontalk you either need to use multitasking or the home button.
A safe thing to do here is probably put a confirmation dialog when the user tries to go back that warns about this. I'll use this issue to track that change.

**Comment by muzirian** [comment]
Tapping home/multitasking button also cancels the registration.

**Comment by daniele-athome** [comment]
Ok that should not happen. I'll do some tests. Any relevant indication for reproducing this issue in particular?

**Comment by muzirian** [comment]
I tried to reproduce it now.i deleted my account and when tried registering agian it give a toast saying 'registraion failed, try again later', so i tried with a different number but still cant register.

**Comment by muzirian** [comment]
Force stopped, cleared cache and tried again with new number, the issue persists.
Minimising after tapping register cancels it giving a toast saying its been canceled but ill get a sms anyway.

**Comment by muzirian** [comment]
Tried multiple times now, minimizing has problems 
![1444041348474](https://cloud.githubusercontent.com/assets/14972525/10278448/162365d4-6b7b-11e5-87da-5d657c16b221.png)

**Comment by daniele-athome** [comment]
Some thoughts about how this work and I think I've been understanding your issue.
When you click the register button, a request is sent to our registration provider, but if it's too late to cancel that, it will be carried out anyway. If you try again, the system will complain that you have a pending (the previous one that you cancelled) registration request, so you'll have to wait like 5 minutes or so.

If you press home or switch app while the "Registering..." dialog is still on, you will abort the registration process and you will get in this "stale" status that I described just before.

I will put a confirmation dialog when coming back from the code input activity, but there is nothing I can do if a user cancels the registration too late.
Of course, if I got your issue wrong, don't hesitate to shot a comment :-)

**Comment by muzirian** [comment]
I understand that you are adding a warning message when you try to go back.

" Tapping home/multitasking button also cancels the registration."
The last screenshot was from registration canceled when by pressing home button.
I guess that issue too will be fixed.

**Comment by daniele-athome** [comment]
If I'm getting this right, you're describing the case when you press the home button while the progress dialog is open ("Registering..." dialog), right? In that case, pressing home will abort it and will make you enter in that limbo situation where you have to wait some minutes to try it again.

**Comment by muzirian** [comment]
ya something like that
