### ISSUE TITLE
Material design part 2

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#562]
Some leftovers from #412:

- [x] ~~use initials-based avatar for outgoing picture if none available~~ (outgoing avatars not used anymore)
- [x] ~~preference category headers (https://github.com/jenzz/Android-MaterialPreference - not enough though)~~
- [x] drop pre-v11 composer bar?
- [x] text placeholder for missing media files (e.g. Image: image/jpg)
- [x] compose message list: use inset overlay scroll bars?
- [x] tiled default background
- [x] indexed scrolling in contacts list
- [x] some leftover dialogs (e.g. registration fallback button dialog)
- [x] final clean

**Comment by h-2** [comment]
* [ ] dark theme

:)

**Comment by daniele-athome** [comment]
Continuing on to #812.
