### ISSUE TITLE
3.1 beta3 keeps crashing often

### ISSUE THREAD

**Issue by pravi** [kontalk/androidclient#564]
Just says 'unfortunately kontalk stopped working'. 3.1 beta2 seems to be fine.

I have cyanogen mod 12.1 without gapps in YU yuphoria.

**Comment by TheLastProject** [comment]
Do you have a logcat? Surely something must be logged, even if it crashes in the background.

On 10 October 2015 03:52:35 CEST, Praveen Arimbrathodiyil <notifications@github.com> wrote:
>Just says 'unfortunately kontalk stopped working'. 3.1 beta2 seems to
>be fine.
>
>I have cyanogen mod 12.1 without gapps in YU yuphoria.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/564

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
I should have fixed that, IIRC. I'm releasing 3.1 stable today, feel free to reopen this issue with a logcat possibly.
