### ISSUE TITLE
Unexpected key change warning upon opening chat through notification quickly after sending message

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#568]
I just got the personal key changed message on switching conversation real quick again. The warning slid over the text input field, which makes it much more likely for people to actually deal with it when it should, which is good, but the bug still being there is bad.

When I clicked identity, I saw the correct contact name displayed, but I can't check whose key it was displaying, as Kontalk won't let you see the key of someone under normal conditions.

It only ever happens when you just sent a message and then click a notification for me, so the easiest way to reproduce would probably involve a spambot sending a message a second so you always have a notification to click, then send a message to someone and click the notification quickly.

**Comment by TheLastProject** [comment]
I'm sorry, but literally on the first day I updated to 3.1.1, this happened to me again, so it wasn't fixed :(

**Comment by daniele-athome** [comment]
:-(
