### ISSUE TITLE
Entries disappear in contact list after unfocusing Kontalk

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#569]
CyanogenMod 12.1, Android 5.1.1

How to reproduce:
1. Open Kontalk
2. Click on the new conversation FAB
3. Press Android app switcher key
4. Select Kontalk

Expected result: Contact list remains correct
Actual result: Some entries disappear from the contact list, leaving letter headers with no contacts (may need to scroll to notice)

When closing the contact chooser and opening it again, the list is created correctly

**Comment by daniele-athome** [comment]
Thanks for reporting. I found out about this issue just yesterday night by chance.
The contacts list is being refactored by @acappelli and will be replaced by a revamped interface in 3.1.1. I'm going to close this as fixed in 45e5e99802a4b53bf3dfc8d5b37afe5bd43e22af.
