### ISSUE TITLE
Clarify new icons license

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#571]
[6628dc](https://github.com/kontalk/androidclient/commit/6628dc9905cfaecb7b878efefae45e435c5ebd9d) adds new icons without clear attribution. These icons look exactly the same as the Telegram ones, but don't seem unique enough to fall under Telegram's copyright. They do, however, use the Google Material Design icons, which [are released under the Creative Commons Attribution 3.0 license](https://github.com/google/material-design-icons#license).

Currently, because the whole repository only has one GPLv3 COPYING file, without further explanation, the art would fall under the GPLv3 as well, a relicensing that I believe is not allowed. At very least, Google is not attributed correctly for their share of the icons.

Of course, I could be wrong and this could completely be original Kontalk work, but seeing the similarity of the icons, I have my doubts.

**Comment by daniele-athome** [comment]
Thanks for reporting @TheLastProject. Those are actually Material Design icons directly from the Google repository (with a circle around them). @acappelli would you mind doing some research about this and make the necessary changes please?

**Comment by acappelli** [comment]
All icon's is under the [Creative Common Attribution 4.0 International License (CC-BY 4.0)](http://creativecommons.org/licenses/by/4.0/)
For more information: https://github.com/google/material-design-icons

**Comment by daniele-athome** [comment]
> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made.

@acappelli can you write something about that maybe in the credits section of the about activity? Actually we should probably do another tab with the 3rd party stuff we've used... for this specific case, that library for showing 3rd party stuff credits you showed me some time ago could fit the task. What do you think? We could use that and also put Material Design icons as a "3rd party library".

**Comment by TheLastProject** [comment]
Even more relevant with #689 now.

**Comment by daniele-athome** [comment]
Included in the README for now. The full-blown about section will be covered by #691.
