### ISSUE TITLE
Description (secondary text) unnecessary in settings

### ISSUE THREAD

**Issue by realdmitchell** [kontalk/androidclient#573]
Go to Settings screen in kontalk
Example: Sync from SIM contacts. The secondary text (see screenshot), changes when I tick or untick. Why does it need to change? If the user ticks, it is understood it will sync from SIM.

The item/secondary text for "Root": is confusing (at least for me). I am not a fanboy of 'G' but kindly look in the page [1]. 

The link [2] is an older API documentation but more clear. There's one important exception to the using secondary text for status: checkbox settings. Here, use secondary text for description, not status. Status below a checkbox is unnecessary because the checkbox already indicates it. The reason why it's appropriate to have a description below a checkbox setting is because—unlike other controls—it doesn't display a dialog or navigate to another screen where additional information can be provided.

If you look in "Settings - packages/apps/Settings" there is no "Changing " secondary text anywhere. Please keep the description minimal and _fixed_.

Thanks!

![kont](https://cloud.githubusercontent.com/assets/11135093/10479751/74d05d48-7266-11e5-8675-6dd519ab5a62.png)

1. https://www.google.com/design/spec/patterns/settings.html#settings-labels-secondary-text
2. http://www.androiddocs.com/design/patterns/settings.html

**Comment by daniele-athome** [comment]
Thanks for reporting. This is an old behaviour from previous Android guidelines in Android 2 and 3.
I was in need of doing a serious review of the settings screen anyway.
