### ISSUE TITLE
"Select Ringtone" does not work

### ISSUE THREAD

**Issue by TwizzyDizzy** [kontalk/androidclient#576]
Hi folks,

I have just installed the latest (3.1 (76)) release of Kontalk on Android 5.1.1 (Cyanogen Mod 12).

Unfortunately selecting a ringtone (in my case "none") does not work. If I select a ringtone and press "OK" and reopen the "Select Ringtone" dialogue, the state is reverted to "Default notification sound".

Cheers
Thomas

**Comment by daniele-athome** [comment]
Thanks for reporting. I've just reproduced it, I'll look into it later.

**Comment by TwizzyDizzy** [comment]
Thanks for fixing :)

**Comment by breversa** [comment]
I was about to report the same issue on CM12.1. Thanks for taking care of it ! :-)

**Comment by breversa** [comment]
Complicated and cons-ladden workaround :

* In Kontalk v3.1, I exported my key
* Using Titanium Backup, I saved Kontalk
* I deinstalled/downgraded to v3.1-beta3 (F-Droid version)
* I restored the save (DATA only)
* I had to reimport my previous key, and even then, lost my previous chats history
* I selected the notification sound I wanted
* I upgraded to v3.1

Now, I have the notification sound I wanted, but it took me much more time than needed, and lost my history, so it's not worth it IMO (unless your notification sound was the most ridiculous one ever and you just can't stand it anymore !).

So Daniel, are you gonna release even a beta soon ?

**Comment by daniele-athome** [comment]
I'm having a hard time focusing my efforts on the app these days. I'm focusing on server development because there is a message loss issue which I haven't been able to figure out yet. If everything goes well, expect 3.1.1 this weekend (a lot of improvements with milestone "3.1.1" will be delayed though; it would be mainly bug fixing).

**Comment by breversa** [comment]
Of course the server goes first ! Sound is only cosmetic and not deal-breaking, so you can safely put that issue to the bottom of your to-do list ! :-)
