### ISSUE TITLE
Owncloud on DAVDroid does not show contact pictures on Android 6.0

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#580]
Reported on the forum.

**Comment by h-2** [comment]
Owncloud is currently breaking pcitures, but that is unrelated to kontalk I think:
owncloud/contacts#1072
owncloud/contacts#1054

**Comment by daniele-athome** [comment]
Thanks @h-2, I'll add those issues to my analysis.

**Comment by daniele-athome** [comment]
I'm merging this into #664.
