### ISSUE TITLE
Top of new conversation list is not top of scrollbar

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#593]
This one is quite minor, but when I am at the top of the new conversation screen (either by just opening it or scrolling up), the scrollbar is not all the way at the top. If I hold the scrollbar, I see an entry for # before C, but no A or B entries. It seems like an (empty?) # field is always created, even if there are no contacts with such a nick. The first letter I have an entry for is C.

![screenshot_2015-11-11-15-13-20](https://cloud.githubusercontent.com/assets/1885159/11099262/a70edf8c-88aa-11e5-91ea-cce8663578f1.png)

The last name in my list starts with an S, but scrolling down to there does make the scrollbar correctly appear at the bottom.

**Comment by daniele-athome** [comment]
Thanks, I've noticed it too recently, I'll look into it.

**Comment by daniele-athome** [comment]
It should be fixed in a7ce3dfed1ab2bee301d1ce336b7f404729f9312.
