### ISSUE TITLE
Replace search dialog with search widget

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#596]
Apparently, using a "search widget" is the recommended way and looks nicer. See https://gitlab.com/fdroid/fdroidclient/merge_requests/168 for how F-Droid did it. Do note that Google lists this for 3.0 and up, although the F-Droid merge request seems to work on Android 2.3 as well. Make sure to test version compatibility.

**Comment by daniele-athome** [comment]
Thanks, we had already it covered on #562, but I guess an extra specific issue won't hurt ;-)
Thanks for the pointers!
