### ISSUE TITLE
Messages from another another contact are mistreated as own messages.

### ISSUE THREAD

**Issue by abika** [kontalk/androidclient#599]
(Reported by another user)
During a chat conversation occasionally incoming chat messages are treated as coming from oneself. There are inserted in a new chat (with oneself as contact) and labelled with "bad signature". Further messages are not affected. First time observed with version 3.1 but also with 3.1.1.

It could be a server bug (wrong `from` JID) or the client is doing something wrong.

**Comment by daniele-athome** [comment]
Yesterday server upgrade should have fixed this bug. At what time did he reported it last time?

**Comment by abika** [comment]
two days ago. So its probably fixed, thanks!

**Comment by daniele-athome** [comment]
Feel free to reopen if it happens again.

**Comment by Manizuca** [comment]
Happened to me yesterday, from 3 consecutive messages, 2 appear as sent by me. version 3.1.1

**Comment by daniele-athome** [comment]
I've been tracking this issue for a few weeks now. I've opened a ticket to Tigase here:
https://projects.tigase.org/issues/3689

I thought I've fixed it in kontalk/tigase-extension@68a378062b89947cb7ddb903a03b77a3a7822afe, apparently it wasn't.
Anyway this is a server problem so I'm keeping this closed.

**Comment by daniele-athome** [comment]
Continuing in server issue kontalk/tigase-extension#59.
