### ISSUE TITLE
smackVersion?

### ISSUE THREAD

**Issue by maxlinux2000** [kontalk/androidclient#602]
today I can't build locally kontalk.

git clone https://github.com/kontalk/androidclient.git
studio.sh

Open the folder in android studio, and I get this error

Error:(21, 0) Could not find property 'smackVersion' on project ':client-common-java'.
<a href="openFile:/home/max/ANDROID/androidclient/build.gradle">Open File</a>

How to fix it?

**Comment by daniele-athome** [comment]
I'm guessing the submodules have not been checked out. You need to update them after cloning the repository:
https://github.com/kontalk/androidclient/wiki/Setup-Android-Studio-project

**Comment by maxlinux2000** [comment]
Sorry, but the error still occurs:

rm -rf androidclient
git clone https://github.com/kontalk/androidclient.git
studio.sh

in Android Studio I select with "Open File o Project" the androidclient folder

And after a bit i get this error:

Error:(21, 0) Could not find property 'smackVersion' on project
':client-common-java'.
<a href="openFile:/home/max/ANDROID/androidclient/build.gradle">Open File</a>


there is something that I can do?

ciao
MaX


On 11/20/15, Daniele Ricci <notifications@github.com> wrote:
> Closed #602.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kontalk/androidclient/issues/602#event-470105644


-- 
ciao,
MaX

**Comment by abika** [comment]
please: read carefully what Daniele already wrote. You need to update the git submodule with
```
cd androidclient
git submodule update --init
```

**Comment by maxlinux2000** [comment]
tnx!!  now it's working :)

**Comment by sannysinghs** [comment]
👍
