### ISSUE TITLE
sometimes messages come as if we are sending it ourselves

### ISSUE THREAD

**Issue by pravi** [kontalk/androidclient#604]
I noticed it once and another contact also reported the same issue. My messages are shown under their name with invalid signature.

**Comment by daniele-athome** [comment]
Thanks for reporting. Can you give at least one message exact date and time? This bug should have been fixed about a week or so ago.

**Comment by pravi** [comment]
4:00 pm today

**Comment by marc0s** [comment]
I confirm this on my side as well. 14:06 CET today. Ping me if you need sender or recipient information as well, or any other extra information.

**Comment by daniele-athome** [comment]
Thanks @marc0s, yes please I'd like to know sender and recipients numbers (or hashes). Send them to the devteam email, thanks!

**Comment by h-2** [comment]
Same here. One of my contacts reported this behaviour a few days ago.

**Comment by daniele-athome** [comment]
This bug was fixed on Tigase a few weeks ago.
