### ISSUE TITLE
Build Success , but App not installed in andriod 

### ISSUE THREAD

**Issue by praveenkathari** [kontalk/androidclient#605]
Build was success by using the instructions 

https://github.com/kontalk/androidclient/wiki/Build-instructions

while i was trying to install in andriod , it gives me "App not installed" message .

Please help thanks

**Comment by daniele-athome** [comment]
Please pastebin the output of Gradle and the output of adb install.
P.S. this board is for bug tracking, please refrain from using GitHub for help requests, use the Google groups.
