### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by pittedmetal** [kontalk/androidclient#608]
New user here. Just recently started using kontalk. About a week back. 

I can't seem to upload anything. I can send and receive texts but can't upload pictures, contacts and audio. This issue just cropped up yesterday and I could upload and download media before successfully. 

I asked my friend to upload some media but every single upload failed. 

I did try updating the server list, restarting the message center and even selecting the "Accept any SSL certificate" option but the issue still persists. I have also tried clearing the app data to no avail. 

I'm running CyanogenMod 12.1 on my phone without any google services or apps. 

![kontalk_upload_error](https://cloud.githubusercontent.com/assets/9088566/11535842/b5ab7298-993b-11e5-9a87-fbafeb7105e2.png)

**Comment by daniele-athome** [comment]
Thanks for reporting. I have another user with the same ROM and having the same problem. Can you send a logcat to the devteam e-mail please?

**Comment by pittedmetal** [comment]
I have sent a logcat to the devteam email.

**Comment by daniele-athome** [comment]
@pittedmetal sorry for the late reply. I've been having some unauthorized users trying to download/upload attachment with a revoked key. I wanted to know if it was your case too, but since it's working now... :-)
Please let me know if you encounter any problems.
