### ISSUE TITLE
Export personal key in user-defined path

### ISSUE THREAD

**Issue by strk** [kontalk/androidclient#610]
Exporting the private key reports success while it could instead not write to the sdcard due to Android 4.4.2 security policy forbidding write to the sdcard root dir (or something like that).

The result is that the keys are not exported.

I'm now stuck with key in the device, btw, any workaround to save keys ?

**Comment by daniele-athome** [comment]
That's weird. I have Android 4.4.4 and can export the key successfully (besides, Kontalk has the right permission to do that). Do you have any security measure in place that might be causing this?

**Comment by strk** [comment]
It's a Galaxy S3 Neo on which I'm having problems writing to the SD card from _any_ application.
I've read somewhere that it was intentionally a security measure but cannot find any way to disable it, maybe it was fixed in 4.4.4

**Comment by daniele-athome** [comment]
Ok, I'll investigate on that and keep you posted.

**Comment by daniele-athome** [comment]
Source: https://source.android.com/devices/storage/traditional.html

> The WRITE_EXTERNAL_STORAGE permission must only grant write access to the primary external storage on a device. Apps must not be allowed to write to secondary external storage devices, except in their package-specific directories as allowed by synthesized permissions. Restricting writes in this way ensures the system can clean up files when applications are uninstalled.

I guess the only way is to use Storage Access Framework through a file picker that will let the user choose a path (which we will have permission to access at that point).
