### ISSUE TITLE
Failed to authenticate in local tigase xmpp server

### ISSUE THREAD

**Issue by siuyinjanice** [kontalk/androidclient#615]
Hi support,

I have a kontalk client requesting my local tigase xmpp server.  It can establish connection and send XML stream to the server.  But the server failed to response the EXTERNAL sasl mechanism XML.  Below are log from the client:

`01-02 13:27:24.491 D/SMACK   (  684): SENT (22): <stream:stream xmlns='jabber:client' to='siuyinjanice.ddns.net' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>`

`01-02 13:27:24.495 D/SMACK   (  684): RECV (22): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='siuyinjanice.ddns.net' id='20be2159-edde-45fa-a431-b06603fe4c0b' version='1.0' xml:lang='en'>`

`01-02 13:27:24.515 D/SMACK   (  684): RECV (22): <stream:features><sm xmlns="urn:xmpp:sm:3"/><roster xmlns="http://kontalk.org/extensions/roster"/><ver xmlns="urn:xmpp:features:rosterver"/><register xmlns="http://jabber.org/features/iq-register"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>KONTALK-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><csi xmlns="urn:xmpp:csi:0"/></stream:features>`

`01-02 13:27:24.515 D/SMACK   (  684): SENT (22): <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'></starttls>`

`01-02 13:27:24.527 D/SMACK   (  684): RECV (22): <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>`

`01-02 13:27:24.731 D/SMACK   (  684): SENT (22): <stream:stream xmlns='jabber:client' to='siuyinjanice.ddns.net' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>`

`01-02 13:27:24.735 D/SMACK   (  684): RECV (22): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='siuyinjanice.ddns.net' id='20be2159-edde-45fa-a431-b06603fe4c0b' version='1.0' xml:lang='en'>`

`01-02 13:27:24.779 D/SMACK   (  684): RECV (22): <stream:features><sm xmlns="urn:xmpp:sm:3"/><roster xmlns="http://kontalk.org/extensions/roster"/><ver xmlns="urn:xmpp:features:rosterver"/><register xmlns="http://jabber.org/features/iq-register"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>EXTERNAL</mechanism><mechanism>KONTALK-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><csi xmlns="urn:xmpp:csi:0"/></stream:features>`

`01-02 13:27:24.779 D/SMACK   (  684): SENT (22): <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='EXTERNAL'>=</auth>`

`01-02 13:27:39.783 E/MessageCenterService(  684): connection error`

`01-02 13:27:39.783 E/MessageCenterService(  684): org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 15000ms (~15s). Used filter: No filter used or filter was 'null'.`

`01-02 13:27:39.783 E/MessageCenterService(  684): 	at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:250)`

`01-02 13:27:39.783 E/MessageCenterService(  684): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.loginNonAnonymously(XMPPTCPConnection.java:374)`

`01-02 13:27:39.783 E/MessageCenterService(  684): 	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:457)`

`01-02 13:27:39.783 E/MessageCenterService(  684): 	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:415)`

`01-02 13:27:39.783 E/MessageCenterService(  684): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:204)`

`01-02 13:27:39.783 E/MessageCenterService(  684): 	at org.kontalk.service.XMPPConnectionHelper.connect(XMPPConnectionHelper.java:254)`

`01-02 13:27:39.783 E/MessageCenterService(  684): 	at org.kontalk.service.XMPPConnectionHelper.run(XMPPConnectionHelper.java:137)`

`01-02 13:27:39.783 D/MessageCenterService(  684): retrying in 1 seconds (retry=1)`

Also attached tigase server log. 
[tigase.log.0.txt](https://github.com/kontalk/androidclient/files/76564/tigase.log.0.txt)

Please kindly advise how to fix this.  Thanks.

**Comment by daniele-athome** [comment]
Hi,
I still see this error in the logs:

```
java.lang.UnsatisfiedLinkError: no gnupg-for-java in java.library.path
```

Didn't you fixed this? Or are the logs cumulative of previous starts?

**Comment by siuyinjanice** [comment]
Yes, the error is still not fixed when I run the client and server again today.  I have reopened issue #614 for followup.  Thanks.

**Comment by siuyinjanice** [comment]
When it process the EXTERNAL SASL request from client it threw the following exception in server:

2016-01-07 19:30:50.876 [urn:ietf:params:xml:ns:xmpp-sasl Queue Worker 0]  SaslAuth.process()  FINER: SASL unsuccessful
tigase.auth.XmppSaslException
        at tigase.auth.mechanisms.SaslEXTERNAL.evaluateResponse(SaslEXTERNAL.java:43)
        at tigase.xmpp.impl.SaslAuth.process(SaslAuth.java:277)
        at tigase.server.xmppsession.SessionManager$ProcessorWorkerThread.process(SessionManager.java:2526)
        at tigase.util.WorkerThread.run(WorkerThread.java:128)

Please refer to the full server log here: 
[tigase.log.0.txt](https://github.com/kontalk/androidclient/files/81145/tigase.log.0.txt)

Please advise what is the possible cause of this exception.
Thanks.

**Comment by daniele-athome** [comment]
Any news on this? You didn't return on IRC after our last chat.

**Comment by siuyinjanice** [comment]
No news on this.  In fact I have attached the tigase.log.0 for your information in my last post to see if you have any idea about the problem.

**Comment by siuyinjanice** [comment]
Hi Daniele,

I wonder if this is caused by the certificate generated on the server, I used the following commands to generate the cert:

openssl req -nodes -new -newkey rsa:2048 -keyout siuyinjanice.ddns.net.key -out siuyinjanice.ddns.net.csr

openssl x509 -req -days 365 -in siuyinjanice.ddns.net.csr -signkey siuyinjanice.ddns.net.key -out siuyinjanice.ddns.net.crt

cat siuyinjanice.ddns.net.crt siuyinjanice.ddns.net.key > siuyinjanice.ddns.net.pem

Is there any problem in the above commands? If so, could you show me the steps on how to generate the certificate correctly?

Thanks.

Janice

**Comment by daniele-athome** [comment]
You can test that with any XMPP client configured to connect to your server (e.g. Pidgin has a nice debug window you can monitor). It is enough that the SSL handshake completes correctly (it will tell you authorization denied, that's normal).

**Comment by siuyinjanice** [comment]
Hi Daniele,

I use Pidgin to connect to my server and it is ok.  But for the Kontalk client, it receive <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><invalid-authzid/></failure> and keep retrying to sending the  handshake request to the server.  Log as follows:


01-26 15:25:07.199 D/SMACK   (  704): SENT (1): <stream:stream xmlns='jabber:client' to='siuyinjanice.ddns.net' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>

01-26 15:25:07.211 D/SMACK   (  704): RECV (1): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='siuyinjanice.ddns.net' id='59ad39f5-7d76-4d3e-800c-9fdafe8a6f7d' version='1.0' xml:lang='en'>

01-26 15:25:07.259 D/SMACK   (  704): RECV (1): <stream:features><sm xmlns="urn:xmpp:sm:3"/><register xmlns="http://jabber.org/features/iq-register"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/><csi xmlns="urn:xmpp:csi:0"/><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required/></starttls><roster xmlns="http://kontalk.org/extensions/roster"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features>

01-26 15:25:07.259 D/SMACK   (  704): SENT (1): <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'></starttls>

01-26 15:25:07.287 D/SMACK   (  704): RECV (1): <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>

01-26 15:25:07.343 I/Choreographer(  704): Skipped 31 frames!  The application may be doing too much work on its main thread.

01-26 15:25:07.651 I/qtaguid (  290): Failed write_ctrl(s 0 10021) res=-1 errno=1

01-26 15:25:07.651 W/NetworkManagementSocketTagger(  290): setKernelCountSet(10021, 0) failed with errno -1

01-26 15:25:10.207 D/SMACK   (  704): SENT (1): <stream:stream xmlns='jabber:client' to='siuyinjanice.ddns.net' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>

01-26 15:25:10.211 D/SMACK   (  704): RECV (1): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='siuyinjanice.ddns.net' id='59ad39f5-7d76-4d3e-800c-9fdafe8a6f7d' version='1.0' xml:lang='en'>

01-26 15:25:10.235 D/SMACK   (  704): RECV (1): <

01-26 15:25:10.235 D/SMACK   (  704): RECV (1): stream:features><sm xmlns="urn:xmpp:sm:3"/><register xmlns="http://jabber.org/features/iq-register"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>EXTERNAL</mechanism><mechanism>KONTALK-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms><csi xmlns="urn:xmpp:csi:0"/><ver xmlns="urn:xmpp:features:rosterver"/><roster xmlns="http://kontalk.org/extensions/roster"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features>

01-26 15:25:10.235 D/SMACK   (  704): SENT (1): <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='EXTERNAL'>=</auth>

01-26 15:25:10.687 D/SMACK   (  704): RECV (1): <

01-26 15:25:10.687 D/SMACK   (  704): RECV (1): failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><invalid-authzid/></failure>

01-26 15:25:10.687 E/MessageCenterService(  704): connection error

01-26 15:25:10.687 E/MessageCenterService(  704): org.jivesoftware.smack.sasl.SASLErrorException: SASLError using EXTERNAL: invalid-authzid

01-26 15:25:10.687 E/MessageCenterService(  704): 	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:365)

01-26 15:25:10.687 E/MessageCenterService(  704): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1040)

01-26 15:25:10.687 E/MessageCenterService(  704): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:944)

01-26 15:25:10.687 E/MessageCenterService(  704): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:959)

01-26 15:25:10.687 E/MessageCenterService(  704): 	at java.lang.Thread.run(Thread.java:856)

01-26 15:25:10.687 D/MessageCenterService(  704): retrying in 4 seconds (retry=2)

01-26 15:25:14.906 D/MessageCenterService(  704): using server siuyinjanice.ddns.net

01-26 15:25:15.179 V/MessageCenterService(  704): connection created.

I don't think this is normal, right?  Could you give some advice about this?

**Comment by siuyinjanice** [comment]
sorry the styling replaced some text.

Here is the log
[logcat.txt](https://github.com/kontalk/androidclient/files/105148/logcat.txt)

**Comment by daniele-athome** [comment]
Could you retry the registration from the app please? DB data could be inconsistent.
Some versions of Android has a bug in the Account Manager, so please delete the account and then kill the app from Settings and register again.

I need to be more verbose in authentication logging... otherwise it's a mess, a thousand things could be wrong with your configuration.

**Comment by siuyinjanice** [comment]
In fact, today i reinstall the genymotion virtual device and everything starts from the beginning (install the app and do registration).  Should I remove all data in DB first before I do that?

**Comment by siuyinjanice** [comment]
sorry, for DB do u mean the server DB or the SQLLite DB in the android emulator?

**Comment by daniele-athome** [comment]
The server database.

**Comment by siuyinjanice** [comment]
Hi Daniele,

I have dropped all the tables in the server DB and create them again and insert records with the sql scripts in tigase-server/database and tigase-extension/data.  But another exception occurs:

```
2016-01-27 20:13:01.916 [in_1-c2s]         ConnectionManager.writePacketToSocket()  FINEST: c2s@siuyinjanice.ddns.net/10.0.2.15_5222_10.0.2.2_49549, type: accept, Socket: c2s@siuyinjanice.ddns.net/10.0.2.15_5222_10.0.2.2_49549 Socket[addr=/10.0.2.2,port=49549,localport=5222], jid: null, Writing packet: from=null, to=c2s@siuyinjanice.ddns.net/10.0.2.15_5222_10.0.2.2_49549, DATA=<stream:features><sm xmlns="urn:xmpp:sm:3"/><register xmlns="http://jabber.org/features/iq-register"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/><csi xmlns="urn:xmpp:csi:0"/><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required/></starttls><roster xmlns="http://kontalk.org/extensions/roster"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features>, SIZE=463, XMLNS=null, PRIORITY=NORMAL, PERMISSION=NONE, TYPE=null
2016-01-27 20:13:01.957 [ResultsListener-socketWriteThread-2]  SocketThread$ResultsListener.run()  WARNING: Protocol execution exception.
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: tigase.xmpp.XMPPDomBuilderHandler.endElement(Ljava/lang/StringBuilder;)Z
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at tigase.net.SocketThread$ResultsListener.run(SocketThread.java:568)
Caused by: java.lang.AbstractMethodError: tigase.xmpp.XMPPDomBuilderHandler.endElement(Ljava/lang/StringBuilder;)Z
	at tigase.xml.SimpleParser.parse(SimpleParser.java:303)
	at tigase.xmpp.XMPPIOService.processSocketData(XMPPIOService.java:703)
	at tigase.net.IOService.call(IOService.java:253)
	at tigase.xmpp.XMPPIOService.call(XMPPIOService.java:215)
	at tigase.xmpp.XMPPIOService.call(XMPPIOService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
What would be the possible cause of this error? Please kindly advise.

**Comment by siuyinjanice** [comment]
Hi Daniele,

I tried to setup my local server again but failed to build this time.  Is there any maintenance doing which updated the source code in github right now?

```
[INFO] Reactor Summary:
[INFO] 
[INFO] Tigase XMPP Server Master project ................. SUCCESS [13.565s]
[INFO] Tigase XMPP Server ................................ SUCCESS [2:24.410s]
[INFO] Kontalk Tigase extension .......................... FAILURE [12.048s]
[INFO] Kontalk XMPP server ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:54.705s
[INFO] Finished at: Thu Jan 28 20:46:51 HKT 2016
[INFO] Final Memory: 40M/97M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project tigase-extension: Compilation failure: Compilation failure:
[ERROR] /root/tigase-extension/src/main/java/org/kontalk/xmppserver/auth/KontalkCertificateCallbackHandler.java:[174,28] cannot find symbol
[ERROR] symbol:   method getUserRepository()
[ERROR] location: variable session of type tigase.xmpp.XMPPResourceConnection
[ERROR] /root/tigase-extension/src/main/java/org/kontalk/xmppserver/KontalkIqRegister.java:[502,20] cannot find symbol
[ERROR] symbol:   method getUserRepository()
[ERROR] location: variable session of type tigase.xmpp.XMPPResourceConnection
[ERROR] /root/tigase-extension/src/main/java/org/kontalk/xmppserver/KontalkRoster.java:[135,40] cannot find symbol
[ERROR] symbol:   method getUserRepository()
[ERROR] location: variable session of type tigase.xmpp.XMPPResourceConnection
[ERROR] /root/tigase-extension/src/main/java/org/kontalk/xmppserver/auth/KontalkAuth.java:[51,23] cannot find symbol
[ERROR] symbol:   method getUserRepository()
[ERROR] location: variable session of type tigase.xmpp.XMPPResourceConnection
[ERROR] /root/tigase-extension/src/main/java/org/kontalk/xmppserver/auth/KontalkAuth.java:[56,16] cannot find symbol
[ERROR] symbol:   method getUserRepository()
[ERROR] location: variable session of type tigase.xmpp.XMPPResourceConnection
```

Here is the full log:
[mvnResult.txt](https://github.com/kontalk/androidclient/files/108165/mvnResult.txt)

**Comment by siuyinjanice** [comment]
Hi Daniele,

Any updates to my previous comment about failed to build the tigase-extension module? Any target date to update the production branch (a build-error-free one)?

**Comment by daniele-athome** [comment]
Sorry for the late reply. The current production branch on both tigase-server and tigase-extension is now working fine. You'll need to update the database schema by running the command described here though (new Tigase version, sorry):
http://docs.tigase.org/tigase-server/snapshot/Administration_Guide/html/#tigaseServer71

I've just upgraded the Kontalk production server and it's working fine so you can proceed. We'll see on the IRC.

**Comment by siuyinjanice** [comment]
Hi Daniele,

When running mvn install, it failed when running the surefire tests, one of the report shows this:

```
java.lang.UnsatisfiedLinkError: no jkyotocabinet in java.library.path
```

Should I set somewhere the java.library.path to include the jkyotocabinet?

**Comment by daniele-athome** [comment]
Weird,it should already have been set by the Maven script... while I check, try to delete `src/test/java/org/kontalk/xmppserver/pgp/PGPLocalKeyringTest.java` from the `tigase-extension` directory.
I'm sorry it's being troublesome to make everything work correctly, but the server is still unstable and constantly changing (because it's based on a development version of Tigase), but we will go through this!

**Comment by daniele-athome** [comment]
Just pushed to all branches:
kontalk/tigase-extension@0667a1d75b575edb3c8c8676a970ce89f83f1db1

Just change the registration provider to `org.kontalk.xmppserver.registration.DummyProvider`. Verification log will be stored in the validations table on the server database and logged to Tigase logs.

**Comment by siuyinjanice** [comment]
Hi Daniele,

I used the DummyProvider to register now and there is no more error now.

Thank you so much for your time and help.

Janice

**Comment by daniele-athome** [comment]
Great! Contact me anytime if you wish to contribute to the project.
