### ISSUE TITLE
Jolla/alien-dalvik compatibility (write contacts)

### ISSUE THREAD

**Issue by fabrixxm** [kontalk/androidclient#616]
The [Jolla phone](http://jolla.com) can run Android apps under alien-davik vm.
Kontalk Android client keep warning me that contact's personal key is changed, but the identity dialog show fingerprint as "(unknown)".
I can send and receive messages but they aren't encrypted, and every time I open a conversation, the alert shows up.

I've had a look at kontalk's databases and I saw that in users.db I've got null in every row of "public_key" of "keys" and "users" tables.

I've tried to get a log out of kontalk while updating contact list.
The result is in [this gist](https://gist.github.com/fabrixxm/058c5bb45b2917e9df5b).
What seem suspicious is the error in [lines 2230-2259](https://gist.github.com/fabrixxm/058c5bb45b2917e9df5b#file-android-log-L2230-L2259)
(I've covered phone numbers with "#"s)

Looks like it fails to write data and then stop the update process. The phone number in that lines is mine.

**Comment by daniele-athome** [comment]
Hello @fabrixxm, thanks for reporting.
Kontalk needs access to the contacts to do what it does in that piece of logs. I don't know how the Jolla permission model works, does the Kontalk app have permission to write to contacts?

**Comment by fabrixxm** [comment]
There is an option "allow Android apps to access your contacs" but is not clear if only in read or in read/write..
I'm going to ask on Jolla forum...

**Comment by fabrixxm** [comment]
If doesn't have write access, it's necessary?
I mean, I saw on android that kontalk contacts in Contacts app list their phone number under "kontalk" field, which when clicked opens conversation window in kontalk.
I don't really think that user experience can be cloned on jolla, as I'm pretty confident that alien-dalvik contacts are a copy from jolla's contacts db, one way.
If write access to contacts is not required for "normal" operation of program (list contacts, send messages, update keys etc etc), maybe I can try to build a version which doesn't try to write into contact's db...

**Comment by daniele-athome** [comment]
Kontalk writes to contacts because it adds its own contact entry for quick access to the linked Kontalk conversation. However, It is not strictly necessary to work, it's just a shortcut from Contacts.
We will have to adapt to the new permission model in Android 6.0 anyway, so in the meantime I've opened #617 for that. However, handling your case might be different. I mean handling a permission model with prior knowledge that I won't be able to write contacts is a thing, but handling unexpected exceptions is another. So I will keep this open to keep track of Jolla/alien-dalvik compatibility.

**Comment by fabrixxm** [comment]
:+1: 
> [...] handling a permission model with prior knowledge that I won't be able to write contacts is a thing, but handling unexpected exceptions is another.

I understand, but stop the entire sync process because a non strictly necessary pass failed is quite.. extreme, I think :-)

**Comment by fabrixxm** [comment]
I'm trying with [this trivial patch](https://github.com/fabrixxm/androidclient/commit/ab6bab0d72daab50afacc29a0450c7bc3a051a02) and looks like it works, for me, on Jolla...

**Comment by daniele-athome** [comment]
I've applied your patch to the code (with some minor modifications and an explanation in a comment), it will go into the next release. Thank you!

**Comment by fabrixxm** [comment]
:+1:
