### ISSUE TITLE
Android 6.0 new permission model

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#617]
Handle the new permission model and make some things not mandatory:
- [x] write contacts
- [x] microphone
- [x] position
- [x] camera
- [x] storage access

### Contacts

We have two different permissions here: `READ_CONTACTS` and `WRITE_CONTACTS`.
Read access is mandatory, otherwise Syncer won't be able to sync anything.
Write access is optional (but convenient. Needed for raw contacts dedicated to Kontalk).
Both need to be asked in the registration screen and in the conversation list.

### Microphone

We may ask this when doing the first audio recording. Modifications needed in `AudioDialog` and `ComposerBar`.

### Position

We can ask this when requesting location the first time. Both "Location" and and "Send location" fragments needs this because they have the "show my location" button.

### Camera

Requested when we need to shoot the private key transfer QR code.

### Storage access

We had better request this on first start. Abort download and uploads (if compression is needed) when the user rejects access to storage. In that case, show a notification that can be clicked to request the permission again and restart the operation.
**This permission is also needed for camera pictures and audio recordings.**

---

https://github.com/afollestad/assent

**Comment by h-2** [comment]
Just updated to CM13 and Kontalk has lost the contact photos. Other apps don't have problems and clicking on a contact does open the android contact-drawer...

**Comment by daniele-athome** [comment]
Thanks @h-2, I've actually been having issues with contact photo on Android 4.4 too. I'll investigate.
Despite you don't have the contact picture, can you still open the contact drawer if you click on the contact icon?

**Comment by h-2** [comment]
> can you still open the contact drawer if you click on the contact icon?

Yep, thats what I meant above. Works without problems and also shows the picture inside the drawer.

**Comment by daniele-athome** [comment]
> Yep, thats what I meant above. Works without problems and also shows the picture inside the drawer.

Oh ok, sorry, I thought you were talking about other apps. I'll get back to you with news.

**Comment by daniele-athome** [comment]
@h-2 contact pictures should have reappeared since 3.1.5 if I recall correctly. Can you confirm please?

**Comment by h-2** [comment]
Yep, all pictures are back!

**Comment by daniele-athome** [comment]
Work is under way in `feature/target-api-23` branch.
Unfortunately, we can't bump directly to 26 or 27 because there are other behavioural changes to be handled. One step at a time :-)

**Comment by daniele-athome** [comment]
Everything is implemented, so closing for now. We'll do extensing testing in the beta channel.
