### ISSUE TITLE
User-editable default invitation text

### ISSUE THREAD

**Issue by breversa** [kontalk/androidclient#619]
An option to edit the default text sent to invite contacts to Kontalk would be nice.

I know you can edit it before sending it, but you need to do it everytime you want to invite a new contact.

What I'm thinking of is an editable field in settings where you can set the text you want, which would serve as the default text for all further invitations.

**Comment by breversa** [comment]
Background :
In the current (french) version (3.1.1), the invitation text offers to download Kontalk from either F-Droid (yay ! :D ) or Play Store, but only give a link for the latter. I'd like to point to F-Droid too, or only.

**Comment by daniele-athome** [comment]
Although modifying the default invitation message would be cool, the main problem here is using a neutral URL (e.g. kontalk.org) that allows downloading a client for any platform or any store. I'll open another issue for that myself. However, for this one I will have to reject because it's something that anyone could do by saving the text into a note or something and sharing it when needed.

**Comment by TheLastProject** [comment]
A Google Play URL is supported by F-Droid at least so it seems neutral enough. I'd just recommend to get rid of the phrase "Google Play Store" so the invite says "Hey! Check out Kontalk, a free messaging app! https://play.google.com/store/apps/details?id=org.kontalk" instead

On 9 January 2016 16:55:51 CET, Daniele Ricci <notifications@github.com> wrote:
>Although modifying the default invitation message would be cool, the
>main problem here is using a neutral URL (e.g. kontalk.org) that allows
>downloading a client for any platform or any store. I'll open another
>issue for that myself. However, for this one I will have to reject
>because it's something that anyone could do by saving the text into a
>note or something and sharing it when needed.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/619#issuecomment-170254461

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
I'm hoping some day there will be an iOS version too :) so I think pointing to kontalk.org would be wiser. In addition, kontalk.org will have a link the desktop version too.

**Comment by breversa** [comment]
Agreed with Daniel here : a link to kontalk.org with links to F-Droid, Play
Store, (Apple Store one day) and desktop version would be the best idea. :-)

2016-01-09 17:37 GMT+01:00 Daniele Ricci <notifications@github.com>:
