### ISSUE TITLE
Notification actions for messages

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#630]
Up to 3 of the following:

* Reply (duplicate of open until we introduce quick reply)
* Call
* Mark as read
* Delete

**Comment by TheLastProject** [comment]
I'd like to go only for reply and mark as read. Neither calling nor deleting messages is likely to be a common action. Replying and ignoring (mark as read) are definitely more common than any other action.

On 23 January 2016 01:21:55 CET, Daniele Ricci <notifications@github.com> wrote:
>Up to 3 of the following:
>
>* Reply (duplicate of open until we introduce quick reply)
>* Call
>* Mark as read
>* Delete
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/630

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
The fact is the reply action would need something different from the simple opening (e.g. A quick reply box), otherwise it's a duplicate we can use for something else (and quick reply is not coming very soon, sorry). This would leave the mark as read action alone.
I'm also strongly in favor of the call action: it's much more common than you think.

I said "up to 3" but we will end up with one or two eheh
