### ISSUE TITLE
Can't download material-dialogs

### ISSUE THREAD

**Issue by mvdan** [kontalk/androidclient#635]
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_basicDebugCompile'.
   > Could not resolve com.github.afollestad.material-dialogs:core:0.8.5.3.
     Required by:
         org.kontalk:app:unspecified
      > Could not resolve com.github.afollestad.material-dialogs:core:0.8.5.3.
         > Could not get resource 'https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.3/core-0.8.5.3.pom'.
            > Could not GET 'https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.3/core-0.8.5.3.pom'.
               > peer not authenticated
   > Could not resolve com.github.afollestad.material-dialogs:commons:0.8.5.3.
     Required by:
         org.kontalk:app:unspecified
      > Could not resolve com.github.afollestad.material-dialogs:commons:0.8.5.3.
         > Could not get resource 'https://jitpack.io/com/github/afollestad/material-dialogs/commons/0.8.5.3/commons-0.8.5.3.pom'.
            > Could not GET 'https://jitpack.io/com/github/afollestad/material-dialogs/commons/0.8.5.3/commons-0.8.5.3.pom'.
               > peer not authenticated
   > Could not resolve com.github.vlivanov:ListViewVariants:f606578467.
     Required by:
         org.kontalk:app:unspecified
      > Could not resolve com.github.vlivanov:ListViewVariants:f606578467.
         > Could not get resource 'https://jitpack.io/com/github/vlivanov/ListViewVariants/f606578467/ListViewVariants-f606578467.pom'.
            > Could not GET 'https://jitpack.io/com/github/vlivanov/ListViewVariants/f606578467/ListViewVariants-f606578467.pom'.
               > peer not authenticated
```

Looks like this: https://stackoverflow.com/questions/22887829/peer-not-authenticated-while-importing-gradle-project-in-eclipse

I've built other apps using jitpack, so don't know what's going on.

**Comment by daniele-athome** [comment]
I can build everything correctly.
Try to delete your ~/.m2 and ~/.gradle folders.

**Comment by mvdan** [comment]
Still the same. What's worse, the links work when opened on Chrome.

I'm on my university's network, so that shouldn't be a problem. Just in case, I'll try tonight when I get back home.

Out of curiosity, what Gradle version do you build with? This is on 2.10. If you're using an older version, could you try that one?

**Comment by daniele-athome** [comment]
Just yesterday we updated the Gradle wrapper to 2.10 and it builds just fine.
You could however try with more verbose logging (maybe you will get more information out of it).

**Comment by TheLastProject** [comment]
It seems that the F-Droid developers fixed this by [removing gradle.properties before building](https://gitlab.com/fdroid/fdroiddata/commit/bbf22a9ef14f661717baeceb08e1eac9b50c5f6b), leaving me to think it was probably some strange out-of-memory exception (because the gradle.properties file specified using extra memory when building). Seeing how F-Droid can build again, I suppose this issue can be closed? Or does anything still have to be done?

**Comment by mvdan** [comment]
@TheLastProject you're referring to the jvm issue though, right?

**Comment by TheLastProject** [comment]
@mvdan I'm referring to how this issue was made because F-Droid couldn't build Kontalk 3.1.2 and I assumed the issue was no longer relevant now that Kontalk 3.1.2 builds on F-Droid. I suppose I was wrong in that assumption?

**Comment by mvdan** [comment]
Well this is the issue I was having on my machine - as far as I know it's not the one that we were having on the buildserver. CC @krt16s

**Comment by daniele-athome** [comment]
@TheLastProject actually I had the same issue too on a 32-bit virtual machine of mine. Removing gradle.properties didn't work. I gave up eventually because I was already switching to 64-bit in the meantime.
I think Gradle always says the same thing when some awkard problem happens when launching the Java VM.

**Comment by daniele-athome** [comment]
Anyway: it might be related to using 32-bit Java.

**Comment by krt16s** [comment]
I just fixed the java issue. I had no more problems with material-dialogs since upstream moved to jitpack.
