### ISSUE TITLE
Crash when opening a chat invitation

### ISSUE THREAD

**Issue by asirinelli** [kontalk/androidclient#638]
With a freshly installed app from Google Play store v 3.1.2 (80), when I receive a chat invitation from a new contact, the app crashes. I cannot accept or reject the invitation as the app crashes as soon as I click on the invitation to open it.

I have stored the crash log: https://gist.github.com/anonymous/dc4ddee62bec90b63ad0

**Comment by daniele-athome** [comment]
Thanks for reporting! We also got a couple of identical reports on Google Play, I'm fixing it right now, although I'm probably going to release in 1 or 2 days.
