### ISSUE TITLE
Get Kontalk scored on the Electronic Frontier Foundation Secure Messaging Scorecard ?

### ISSUE THREAD

**Issue by breversa** [kontalk/androidclient#639]
In order to improve Kontalk's visibility, why not get it scored on the EFF Secure Messaging Scorecard : https://www.eff.org/secure-messaging-scorecard ?

Other opensource tools have been scored, such as Signal, Telegram and TextSecure.

**Comment by daniele-athome** [comment]
Great idea! Moved to kontalk/specs#13.
