### ISSUE TITLE
Include a Changelog link on F-Droid

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [kontalk/androidclient#652]
Include a Changelog Link, within the F-Droid App', on Info' Page. Not present, as of: 3.1.3.

**Comment by locutis-of-borg-1999** [comment]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 3.1.3.

**Comment by daniele-athome** [comment]
Thanks for reporting. Will do for next release.

**Comment by locutis-of-borg-1999** [comment]
:-)

**Comment by daniele-athome** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/1254
