### ISSUE TITLE
Add Signal/SMSSecure balloon theme

### ISSUE THREAD

**Issue by mimi89999** [kontalk/androidclient#656]

**Comment by mimi89999** [comment]
I can work on it.

**Comment by daniele-athome** [comment]
Ok thank you! It should be relatively easy to add a new theme.
You should write a new balloon theme class by extending `AvatarMessageTheme` (I can see the outgoing avatar is not shown in SMSSecure, you can override the `setOutgoing` method to hide the relevant view) and then put a reference to that class into the theme factory (`MessageListItemThemeFactory`) by assigning a new string to it ("signal" or "smssecure").
Then you have to add a new element to the arrays.xml file and its translation (only add English, others will be added through Weblate) in strings.xml.

When you're finished, please open a pull request.
Thank you!

**Comment by daniele-athome** [comment]
Also, please run a syntax check through `./gradlew check` before opening the pull request. Thanks!

**Comment by mimi89999** [comment]
Should I put it after hangout or at the end?

**Comment by daniele-athome** [comment]
After Hangout, please.

**Comment by mimi89999** [comment]
I can't assembleDebug:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_basicDebugCompile'.
   > Could not resolve com.github.afollestad.material-dialogs:core:0.8.5.6.
     Required by:
         androidclient:app:unspecified
      > Could not resolve com.github.afollestad.material-dialogs:core:0.8.5.6.
         > Could not get resource 'https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.6/core-0.8.5.6.pom'.
            > Could not GET 'https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.6/core-0.8.5.6.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve com.github.afollestad.material-dialogs:commons:0.8.5.6.
     Required by:
         androidclient:app:unspecified
      > Could not resolve com.github.afollestad.material-dialogs:commons:0.8.5.6.
         > Could not get resource 'https://jitpack.io/com/github/afollestad/material-dialogs/commons/0.8.5.6/commons-0.8.5.6.pom'.
            > Could not GET 'https://jitpack.io/com/github/afollestad/material-dialogs/commons/0.8.5.6/commons-0.8.5.6.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve com.github.vlivanov:ListViewVariants:f606578467.
     Required by:
         androidclient:app:unspecified
      > Could not resolve com.github.vlivanov:ListViewVariants:f606578467.
         > Could not get resource 'https://jitpack.io/com/github/vlivanov/ListViewVariants/f606578467/ListViewVariants-f606578467.pom'.
            > Could not GET 'https://jitpack.io/com/github/vlivanov/ListViewVariants/f606578467/ListViewVariants-f606578467.pom'.
               > sun.security.validator.ValidatorException: PKIX pa

**Comment by daniele-athome** [comment]
I remember having bumped into this too, but I can't remember how I fixed it...
Can you run a `./gradlew clean` and try again?

**Comment by mimi89999** [comment]
Even ***./gradlew clean*** fails with the same error.

**Comment by mimi89999** [comment]
I need to add the certificate to java...

**Comment by mimi89999** [comment]
I don't know how to fix this.

**Comment by mimi89999** [comment]
Maybe related to: https://github.com/jitpack/jitpack.io/issues/423

In this case updating gradle wrapper should fix the issue.

**Comment by daniele-athome** [comment]
Weird... it works for me on 2.10.
Ok then, please include the upgrade to the Gradle wrapper in the PR.

**Comment by mimi89999** [comment]
> I can see the outgoing avatar is not shown in SMSSecure

The outgoing avatar is not shown in the latest version of Hangouts.

**Comment by mimi89999** [comment]
![screen](https://cloud.githubusercontent.com/assets/8530546/13526709/fe051230-e209-11e5-807f-de827960b4f6.png)
In SMSSecure and Signal you can choose the color of incoming messages. For testing I used white. If you prefer a color to another, I can change it...

**Comment by daniele-athome** [comment]
> The outgoing avatar is not shown in the latest version of Hangouts.

Oh I didn't notice that (I don't use Hangout much).

>  In SMSSecure and Signal you can choose the color of incoming messages. For testing I used white. If you prefer a color to another, I can change it...

Let's start with two colors, as Signal does: white for outgoing, color_primary_dark (that is, the toolbar background color) for incoming messages.

**Comment by mimi89999** [comment]
I never used Hangouts. I saw a screenshot...

**Comment by daniele-athome** [comment]
I didn't think of looking at the screenshots because I have it installed eheh actually I didn't even bother I just trusted what you said :-)

**Comment by mimi89999** [comment]
In SMSSecure incoming text color is white. In Kontalk the text color is black. When I changed the balloon color, all incoming messages became unreadable.

**Comment by h-2** [comment]
Cool to see a new theme! Will this maybe make a dark theme easier, too?

**Comment by daniele-athome** [comment]
@mimi89999 I think you have to change only the background color (or maybe I'm not getting what the problem is). Can I see the code you're writing?

**Comment by daniele-athome** [comment]
@h-2 I'm afraid not so much, sorry :-( balloon theming needs some improvement to be usable with a dark theme and also the rest of the application should be themed too (although that could be relatively easy to do by using XML styles).

**Comment by mimi89999** [comment]
Black text on dark background is unreadable...

**Comment by daniele-athome** [comment]
@mimi89999 ok sorry I thought about another thing.
You could use a new text appearance style to be applied in `TextContent.setDarkBackground()` (which will autonomously decide which style to apply), called by `AvatarMessageTheme.processComponentView()`.

**Comment by mimi89999** [comment]
Here is my code: https://github.com/mimi89999/androidclient/commit/fc82f0bbe503527351299a889b36c6c61dc4d463

**Comment by daniele-athome** [comment]
Thanks. A small review:

* please move the Gradle wrapper version upgrade to a separate commit
* please avoid duplicating the whole XML layout of balloons. I think changing the colour could be made inside the new theme class by using a custom style that you can define in styles.xml (https://github.com/kontalk/androidclient/issues/656#issuecomment-192674972)

If you fix those two things and create a pull request I'd be happy to merge it.
Thank you!!

**Comment by daniele-athome** [comment]
Didn't we say use color_primary_dark for incoming? I don't understand, is that your final commit or do you need to amend something?

**Comment by mimi89999** [comment]
No, it's not my final commit. After you wrote:

> Can I see the code you're writing?

I commited the current state of my local version...

**Comment by pejakm** [comment]
@mimi89999 What's the status of this?
