### ISSUE TITLE
High battery usage in Kontalk 3.1.4-preview

### ISSUE THREAD

**Issue by mimi89999** [kontalk/androidclient#659]
While working on #656 I noticed this:
![screen](https://cloud.githubusercontent.com/assets/8530546/13550789/d84626ac-e325-11e5-8898-2d7ecb6c5023.png)

The output of ***adb shell dumpsys batterystats***:
[batterystats.txt](https://github.com/kontalk/androidclient/files/160066/batterystats.txt)

ROM: CM13 nightly
HW: Samsung Galaxy S4 mini GT-I9195 (serranoltexx)

**Comment by mimi89999** [comment]
I use BasicDebug. I don't have GMS on my phone. In Kontalk I set ***Disconnect...*** to ***Never***

**Comment by mimi89999** [comment]
The logcat:
[logcat.txt](https://github.com/kontalk/androidclient/files/160079/logcat.txt)

**Comment by daniele-athome** [comment]
Hello,

```
03-05 23:27:44.558 23087 29187 W AbstractXMPPConnection: org.jivesoftware.smack.XMPPException$StreamErrorException: conflict You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
03-05 23:27:44.558 23087 29187 W AbstractXMPPConnection: <stream:error><conflict xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
```

Both versions can't run together at the same time because the XMPP resource is your device ID. Therefore, you need to keep one of them offline while using the other (menu > go offline).
