### ISSUE TITLE
Contact picture API broken for older Android versions

### ISSUE THREAD

**Issue by larjona** [kontalk/androidclient#671]
Hi everybody. Thanks for working in Kontalk and congratulations for the 3.1.4 release.

I upgraded my Kontalk from 3.1.3 to 3.1.4 using F-Droid in my Android 2.3.7 phone (Cyanogen 7.2) and it worked fine.

But now, I obtain a crash when opening Kontalk. I suspect it's a contact sync issue, because I see all the time the spinning circle of contact sync in the notification bar, and if I go to Settings -> Account and sync and I manually syncronize the Kontalk account, I get a crash too.

I'm attaching both logs.

I've tried to think if I did something unusual in my contacts that triggered this problem and the only thing that comes to mind is that I edited one of my Kontalk contacts to add an email address. I edited the contact again to remove the email, but the crashes remain (I suppose, because it's the sync what is causing problems). But maybe I'm wrong and the problem has nothing to do with adding an email or with contacts.

I'm not sure what to do, if uninstalling and reinstalling, or downgrade... I can wait some days for your answer, maybe it's something easy to fix or if you need that I do some test, just tell.

Thanks!

[alogcat20160407.txt](https://github.com/kontalk/androidclient/files/208098/alogcat20160407.txt)
[alogcat20160407_contactsync.txt](https://github.com/kontalk/androidclient/files/208097/alogcat20160407_contactsync.txt)

**Comment by daniele-athome** [comment]
Thanks for detailed report. Solving a bug for Android 6 opened another bug for older versions of Android. Unfortunately this wasn't documented (of course).
I'll implement a fallback for the old behaviour when the new one doesn't work. And I'll probably publish a hotfix then.

**Comment by daniele-athome** [comment]
It seems I'm not the only one:
http://stackoverflow.com/questions/8331894/loading-contact-picture-via-lookup-key-and-opencontactphotoinputstream-convenien
