### ISSUE TITLE
Kontalk 3.1.5 in Android 2.x not sending messages, reports "Network not available, pleasy try again later".

### ISSUE THREAD

**Issue by larjona** [kontalk/androidclient#674]
Dear all
Thanks for the fix for #672 and quick release of version 3.1.5.
With this version now I have no crashes, but Kontalk is still not working, I'm afraid.

If I go to settings and try to update the servers list, the program reports there is no network connection (attached log).
When I send a message, it remains with the symbol of the clock, unsent.
I'm not sure if this is a bug or a problem in my contact list, or a problem in my phone. If I can do any other test, please tell.
I'm using Android 2.3.7 (Cyanogenmod 7.2) and Kontalk 3.1.5 installed from F-Droid. My phone is rooted.

Thanks!
[kontalk20160408.txt](https://github.com/kontalk/androidclient/files/210677/kontalk20160408.txt)

**Comment by svrnwnsch** [comment]
I am also having many connections problems with the kontalk servers since 1 week. Uploading voice messages never works and sending text sometimes works sometimes not.

**Comment by daniele-athome** [comment]
Thanks for reporting. Can I see the whole log or at least the full stacktrace please? I'd like to verify something (3.1.5 was released just to fix the error you reported).

**Comment by larjona** [comment]
Hi
My problem is solved. It was my fault: In my Android Settings -> accounts and sync ->  Background data was unchecked (I unchecked it to avoid the crashes of 3.1.4) and Autosync was unchecked too. When I activated those checkboxes, Kontalk began to work again.
I'll close this issue because I think what @svrnwnsch reports is a different problem.

Thanks!
