### ISSUE TITLE
SmackException Bad file number

### ISSUE THREAD

**Issue by svrnwnsch** [kontalk/androidclient#676]
I cant upload any voice messages to the kontalk server and I did find the following exception in catlog which could be part of the problem.

`04-09 16:53:03.299 E/MessageCenterService(2283): org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'beta.kontalk.net:5222 prio:5:w:0' failed because java.net
.SocketException: java.io 
.IOException: fcntl failed: EBADF (Bad file number), 'beta.kontalk.net:5222' failed because java.net
.SocketException: java.io 
.IOException: fcntl failed: EBADF (Bad file number)`

**Comment by daniele-athome** [comment]
Thanks for reporting. Could I see the whole log or at least the full stacktrace please?

**Comment by daniele-athome** [comment]
It could be related to Digital Ocean floating IP mechanism. I've set the hostname to the real host IP address. Please wait up to 24h for DNS propagation. Feel free to reopen if it still happens.

**Comment by daniele-athome** [comment]
It turned out it was related to IPv6 support on the server. I've disabled it for now until I can do a proper analysis of the issue.
