### ISSUE TITLE
Update emojicon library

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#679]
On January 5th, a new version of emojicon got released. The most noticeable change is that, in https://github.com/rockerhieu/emojicon/commit/48eafe8e88582d1697e2b5c379feb466d7f06b4e, it adds a LOT of emoji. It would be nice to have access to these emoji in Kontalk.

(Sorry if this should've gone to https://github.com/kontalk/emojicon, I'm not quite sure what was the best place for this request)

**Comment by daniele-athome** [comment]
Thanks @TheLastProject, here is just fine.

**Comment by daniele-athome** [comment]
Note to myself: tablets need bigger emojis.

**Comment by daniele-athome** [comment]
Closed in ea733d55052aa7891e9c4a371581fab26d48380f and fc27b9d07dc35cd2bf0884c29f221b90a2e48384.

**Comment by TheLastProject** [comment]
Not trying to be annoying, just trying to save you just that tad bit more time: Seeing how you'll release 3.1.7 soon and this was fixed and will probably end up in that release, you may want to change this milestone.

**Comment by daniele-athome** [comment]
You're very right :-) I forgot that, thanks.

**Comment by TheLastProject** [comment]
I hate to say this, but it seems the new emoji aren't actually visible or reachable in any way. To make sure I didn't actually fail myself, I looked specifically for the first new emoji I saw in the diff (https://github.com/kontalk/emojicon/blob/cf94b38a742f8df3c71f4111bcb41212689c5353/library/src/main/res/drawable-nodpi/emoji_002a_20e3.png) but could not find it anywhere :(

**Comment by daniele-athome** [comment]
Weird... no difference involved between Kontalk fork and upstream, it must be an upstream problem. Would you mind trying with upstream emojicon sample app please?

**Comment by TheLastProject** [comment]
Is there any chance you could provide an APK for me? Upstream unfortunately doesn't seem to have the newest release listed on GitHub, the newest version they have in Releases is 1.2, and I do not have a working installation of the Android SDK. I did find their [Travis](https://travis-ci.org/rockerhieu/emojicon), but I couldn't find any binaries there either. My last hope, AndroidGems, simply looks malicious, apparently requiring a special (proprietary?) app to even download it.

**Comment by daniele-athome** [comment]
Sorry I don't have one at the moment. No problem though, I'll build one later tonight and try it myself.

**Comment by TheLastProject** [comment]
Did you get any further with this? The "tonight" was 3 days ago ;) Maybe consider reopening the ticket?

**Comment by daniele-athome** [comment]
Eheh sorry, totally forgot :-) No need to reopen, I've just set a reminder to myself.
