### ISSUE TITLE
Kontalk v3.1.5 crashes when I launch it.

### ISSUE THREAD

**Issue by 0strip0nebulosa0** [kontalk/androidclient#680]
I have reported about bug in Kontalk v3.1.4 (https://github.com/kontalk/androidclient/issues/672). Unfortunately, recent Kontalk v3.1.5 crashes when I launch it. I'm attaching log below.

I have upgraded Kontalk from 3.1.4 to 3.1.5 using F-Droid app.

Thanks a lot for the nice application!
[logcat.txt](https://github.com/kontalk/androidclient/files/214908/logcat.txt)

**Comment by daniele-athome** [comment]
Thanks for reporting! Fix will be available in a couple of days at most.
Note to Google: **unbelievable**.
