### ISSUE TITLE
Submenus for Settings

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#692]
There will be more and more items in the settings menu.
Especially when groupchat will come.
I think it would be more clear if it subdivides in submenus.

Maybe it's a nice work for @relan ;-)

**Comment by daniele-athome** [comment]
I think a more comprehensive reorganization of the whole settings would be even better because group chat as you said will introduce several other items. I'll think about something when it will be the time. Of course @relan and @webratte if you have any proposal please share.

**Comment by relan** [comment]
@webratte, you mean subscreens? Settings are a pain when you need to support pre-Honeycomb devices: Gingerbread does not support fragments and preference-v7 support library is not an option because it [looks ugly on Lollipop](https://code.google.com/p/android/issues/detail?id=205161) and later.

**Comment by webratte** [comment]
Yes, something like this.
Just a way to bring more clarity into the settings.
However it could be solved.

**Comment by abika** [comment]
+1 for "submenus", i.e. one subscreen for each category.
I can even try implementing this with preference headers...

@relan fragments are already used in the preferences: the privacy settings are shown in a `PreferenceFragment`. With my humble knowledge of Android this works fine with support-v4

**Comment by daniele-athome** [comment]
I remember having some issues with preference headers across Android versions, especially 2.3 and 4.0. Devs are complaining about the support library to be somewhat... messy when it comes to real backward compatibility.

**Comment by abika** [comment]
It is indeed hard to do this with preference headers: Android's `PreferenceActivity` cannot be used with `PreferenceFragmentCompat`s. And there is also no "compat" version of `PreferenceActivity`.

But using multiple `PreferenceFragment`s works. I have to test it a bit more before pushing that...

**Comment by TheLastProject** [comment]
I believe the milestone of this should be 3.1.9? Small administrative thing :smile:
