### ISSUE TITLE
Tablet support: fix compose activity opening directly

### ISSUE THREAD

**Issue by 0strip0nebulosa0** [kontalk/androidclient#701]
I use Kontalk application v.3.1.8 on my tablet (Sony Xperia Z3 Tablet Compact, Android 5.1.1). Everything is fine but if I choose a contact from my contact list (It is the column in Kontalk application. See the screenshot 1.), I will not be able to send pictures, but I will be able to send messages (The application do not show an any error). If I open Kontalk from notification area, when I have received a message, Kontalk application will open in full screen (See the screenshot 2.) and I will be able to send messages & pictures. Can you fix it? I attach the screenshots with described problem.
![1](https://cloud.githubusercontent.com/assets/18327693/14917930/79088846-0e32-11e6-95ac-ae954773ae26.jpeg)
![2](https://cloud.githubusercontent.com/assets/18327693/14917939/8bc4e3e4-0e32-11e6-9b45-26e804dd3450.jpeg)

**Comment by daniele-athome** [comment]
Thanks for reporting. Sorry for this, tablet support is not very well tested. I'll investigate and provide a fix.

**Comment by TwizzyDizzy** [comment]
I don't know, if my issue is related so please ignore, if it's not the same problem (I'll open an other issue then). I'm on 3.1.9.1 (no tablet, but HTC One m7) and the sending of images seems to work, but not the download. I see the preview of the image that was sent to me, but on tapping on the image (for downloading) I receive the notification, the the attachment download failed.

Cheers
Thomas
