### ISSUE TITLE
Registering on a new device does not give sufficient information on how to copy account between devices

### ISSUE THREAD

**Issue by keverets** [kontalk/androidclient#717]
When registering on a new device, Kontalk warns:

"<b>The number you are using is already registered to Kontalk.</b> If you have registered another device, proceeding in this manner will cut it off from Kontalk. Please refer to our documentation on how to copy your account between devices. Choose OK to continue anyway."

However, the user has no available documentation, and there's no link to help them open a browser to find it.

Perhaps the "how to copy your account between devices" could be made into a link to https://github.com/kontalk/androidclient/wiki/Export-personal-key-to-another-device so that the user can touch on it and get the info they need.

**Comment by TheLastProject** [comment]
How about an extra button in the dialog named "Read More" which opens the browser to that URL? Seems better. Although, obviously, in the future, Kontalk should probably have multi-device support, which seems to be discussed in https://github.com/kontalk/desktopclient-java/issues/51 although it will surely still take a while.

**Comment by daniele-athome** [comment]
> How about an extra button in the dialog named "Read More" which opens the browser to that URL?

Exactly my thoughts. Thank you both for the suggestion.

Key sharing between devices is a hard thing to make people comfortable with, so if you have other ideas on how to improve the process, please share.
