### ISSUE TITLE
Error uploading multiple files with new upload service

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#727]
There is something wrong with the new upload method. Multiple upload URLs are requested correctly, but somehow after the first it gets a 403 Forbidden error. Probably the same first URL is used for all the uploads.

**Comment by TheLastProject** [comment]
I can reproduce this issue. What I noticed is that, if I restart the message center from the options, one more image gets properly sent immediately, so it indeed seems to be an internal state issue.
