### ISSUE TITLE
Registration test phone call only performed once - but might be missed in dead spot

### ISSUE THREAD

**Issue by keynlotepan** [kontalk/androidclient#748]
When my wife registered yesterday, she was in a dead spot of our apartment. So she did not receive the registration test phone call. I proposed to go to the window to be available. But no second attempt of a call occured and the fall back SMS approach was performed. Unsuccessfully this measure causes costs and could be avoided by a first fallback, consisting of a hint (asking if the user is in a dead spot after a timeout) and a call retry before the final fallback causing costs.

**Comment by daniele-athome** [comment]
Thanks for reporting, this is a good idea: request the call again and eventually fallback to the SMS method after 2 or 3 attempts.

**Comment by daniele-athome** [comment]
Note to myself: detect whether the phone reception is present by calling the telephony service.

**Comment by daniele-athome** [comment]
Thinking more about it:

* the phone number the user is trying to register might not be the same one hosted on the device being used (see: tablets)
* the registration method is currently being changed from an incoming-call approach to an outgoing-caller ID verification approach (no costs for the user of course; the SMS fallback will still be present if all else fail)

I'm closing this issue. If you have anymore comments or suggestions, feel free to share them.
