### ISSUE TITLE
Play a sound while app is opened and a new message arrives

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#75]
_From [etemu.com](https://code.google.com/u/etemu.com/) on August 14, 2013 20:49:51_

It should be possible to chose a sound/vibration for a new incoming message. At the moment there is only a notification sound played, if the app is not active in the foreground.

_Original issue: http://code.google.com/p/kontalk/issues/detail?id=125_
##

**Comment by pejakm** [comment]
It would be great if the "soft sounds" (as op from #531 calls them) would be different for sending messages/receiving messages while conversation is opened. May I suggest this set of sounds:
https://freedesktop.org/wiki/Specifications/sound-theme-spec/

Quick preview of the most interesting sounds:


[audio-volume-change.oga](http://vocaroo.com/i/s1ZNTCUWXXP3)
*Copyright: Lucas McCallister*
*URL: http://www.freesound.org/samplesViewSingle.php?id=67091*
*License: CC-BY-SA (relicensed with permission from author)*

[bell.oga](http://vocaroo.com/i/s17ZyDXq1wkK)
*Copyright: Dr. Richard Boulanger et al*
*URL: http://www.archive.org/details/Berklee44v12*
*License: CC-BY Attribution 3.0 Unported*

[dialog-information.oga](http://vocaroo.com/i/s1io4peVZk5V)
[dialog-warning.oga](http://vocaroo.com/i/s1e6qkuARcem)
[message.oga](http://vocaroo.com/i/s1X1y4U0CDdx)
*Copyright: Ivica Bukvic*
*URL: http://gnome-look.org/content/show.php/%22Borealis%22+sound+theme?content=12584*
*License: CC-BY-SA*

**Comment by pejakm** [comment]
`dialog-warning.oga` IMHO is perfect for sound of incoming messages when conversation is opened. It is similar to the same purpose sounds of Viber and WhatsApp.

**Comment by TheLastProject** [comment]
I'd personally vote for message for incoming and audio_volume_change for outgoing, as they're basically the same but message is slightly louder.

**Comment by daniele-athome** [comment]
@pejakm @TheLastProject I'm sorry but the files linked above are expired (I know, long due :-)
Could you point me to the right ones please? I'm evaluating some sounds and I'd like to hear those you suggested last year. Thanks!

**Comment by daniele-athome** [comment]
In the meantime I've closed the issue because I've implemented it using two sounds I found. There is time to replace them of course so if you have suggestions please go ahead.

**Comment by pejakm** [comment]
@daniele-athome You can download the theme (http://people.freedesktop.org/~mccann/dist/sound-theme-freedesktop-0.8.tar.bz2) and check all the files. :)
