### ISSUE TITLE
Wiki quick start guide and guidelines

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#756]
I like initiative people are taking on the wiki of this repository, but they need proper guidelines for creating new pages, updating links to other languages, and so on.

- [x] new page guidelines
- [x] add language to existing page (add to english page header, prefix page title with language code, update sidebar)

Fixes:

- [x] fix Serbian pages (missing language code in page title)

**Comment by pejakm** [comment]
> fix Serbian pages (missing language code in page title)

I didn't know this is required.

**Comment by daniele-athome** [comment]
Don't worry, I didn't mention it anywhere yet. This issue is for reminding me that I should :-)

**Comment by pejakm** [comment]
I've fixed Serbian pages, you can check that. :)

**Comment by daniele-athome** [comment]
Perfect, thank you!

**Comment by pejakm** [comment]
I would also like to update *Push notification without Google Cloud Messaging* wiki page, as it contains no information about microg.org fdroid repo or the fact that for already patched roms you don't have to use Xposed at all. Should I just merge the changes and you will review later or post my diff somewhere?

**Comment by webratte** [comment]
@daniele-athome  Is there also a (easy) way to optimize the help pages for mobile phones?
Because we call this pages most times via mobil devices I think.

**Comment by daniele-athome** [comment]
@pejakm please go ahead. 

@webratte I'm afraid not, until GitHub makes them readable from mobile. Or I set up something to render those pages externally...

**Comment by webratte** [comment]
@daniele-athome OK, I have supposed this.
So I think it's OK for now.

**Comment by pejakm** [comment]
It's there, just copy it and translate: https://github.com/kontalk/androidclient/wiki/Push-notification-without-Google-Cloud-Messaging
I tried to make it as simply as possible, because microG website and wiki already explained the setup process in details.

**Comment by webratte** [comment]
Thank you @pejakm just translated.

@all This translation needs review from more tech people like me!!!!

**Comment by daniele-athome** [comment]
I started this page:
https://github.com/kontalk/androidclient/wiki/Contributing-to-the-wiki

And I've linked it from the home page (from "this wiki for a start") and translated it to Italian. @translators would you mind editing the other languages of the home wiki page please?

The "Contributing to the wiki" page is still a WIP, I'd like your feedback on that before closing this issue.
Also I'd ask you to not translate that page: "internal" documentation and project engagement pages should be kept in English only (I think translations should be applied only to user documentation).

**Comment by pejakm** [comment]
Serbian home page - done.

**Comment by webratte** [comment]
German home page - done.

Should we not clarify this side (https://github.com/kontalk/androidclient/wiki/Contributing-to-the-wiki) should not be translated?

**Comment by daniele-athome** [comment]
> Should we not clarify this side (https://github.com/kontalk/androidclient/wiki/Contributing-to-the-wiki) should not be translated?

Totally right. I've just added a paragraph at the end stating that.

@pejakm sorry I had to delete your Serbian translation for the Development rules page, no offense :-)

**Comment by webratte** [comment]
I mean exactly this page:

https://github.com/kontalk/androidclient/wiki/Contributing-to-the-wiki

Or did I misunderstood and it should be translated?

**Comment by daniele-athome** [comment]
That's right. I've added a paragraph to *that* page at the end stating what pages should not be translated (including that page itself).

**Comment by webratte** [comment]
Your right.
Sorry sometimes I should read the hole Paragraph 😞
