### ISSUE TITLE
Avoid typing the phone number in when importing the key

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#772]
Quick idea: encrypt the phone number with the public key and store it into the zip file.
Or I could just store into the zip file in cleartext - no real need to protect it.
Any other ideas are welcome.

**Comment by relan** [comment]
That's a good idea. Now you tap Import key, select archive, enter password and then get an error about the phone number. Such UX is bad. Also, Import key action should be more prominent.

A [nice article](https://uxdesign.cc/the-absolute-minimum-android-developers-need-to-know-about-ux-part-5-of-5-67ace6c0da57#.tb8yshdci) about login screens.
