### ISSUE TITLE
New notifications features

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#774]
Implement MessagingStyle and direct reply where possible.

- [x] MessagingStyle
- [ ] direct reply

---

https://developer.android.com/guide/topics/ui/notifiers/notifications.html#direct

**Comment by keshto** [comment]
direct reply seems to only work on 7.0+ would be nice to get it to work on prior versions of android as well if it is not too hard, maybe even if hitting reply jumps to chat activity. In any case. +1000 on this ticket. It is one ui pain point I notice each day.
