### ISSUE TITLE
Empty menu under 'invite users' 

### ISSUE THREAD

**Issue by tetris4** [kontalk/androidclient#775]
Open kontalk > new message button > menu button > invite users
When hitting this I get a warning 'No apps can perform this action'. The share button in Kontalk works fine 
This is relevant log:

```
07-05 13:53:41.875 I/Timeline(3958): Timeline: Activity_launch_request id:org.kontalk time:46315959
07-05 13:53:41.880 I/ActivityManager(3334): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.kontalk/.ui.ConversationsActivity bnds=[193,806][331,966] (has extras)} from uid 10016 on display 0
07-05 13:53:42.995 D/MessageCenterService(12229): Message Center starting - Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
07-05 13:53:43.690 I/Timeline(3334): Timeline: Activity_windows_visible id: ActivityRecord{2ed0775c u0 org.kontalk/.ui.ConversationsActivity t2886} time:46317773
07-05 13:53:44.875 I/Timeline(12229): Timeline: Activity_launch_request id:org.kontalk time:46318955
07-05 13:53:44.875 I/ActivityManager(3334): START u0 {cmp=org.kontalk/.ui.ContactsListActivity} from uid 10057 on display 0
07-05 13:53:44.880 V/WindowManager(3334): addAppToken: AppWindowToken{326ae5cd token=Token{28bc7f64 ActivityRecord{1f0ab4f7 u0 org.kontalk/.ui.ContactsListActivity t2886}}} to stack=1 task=2886 at 1
07-05 13:53:44.945 D/MessageCenterService(12229): Message Center starting - Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }
07-05 13:53:45.230 V/WindowManager(3334): Adding window Window{15aba993 u0 org.kontalk/org.kontalk.ui.ContactsListActivity} at 12 of 15 (after Window{35fb2cbf u0 org.kontalk/org.kontalk.ui.ConversationsActivity})
07-05 13:53:45.370 D/MessageCenterService(12229): Message Center starting - Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
07-05 13:53:45.405 I/ActivityManager(3334): Displayed org.kontalk/.ui.ContactsListActivity: +482ms
07-05 13:53:45.795 I/Timeline(3334): Timeline: Activity_windows_visible id: ActivityRecord{1f0ab4f7 u0 org.kontalk/.ui.ContactsListActivity t2886} time:46319877
07-05 13:53:46.455 V/WindowManager(3334): Adding window Window{2f715bda u0 PopupWindow:a2a00e3} at 13 of 16 (after Window{15aba993 u0 org.kontalk/org.kontalk.ui.ContactsListActivity})
07-05 13:53:48.985 D/MessageCenterService(12229): Message Center starting - Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }
07-05 13:53:49.535 V/WindowManager(3334): Adding window Window{1c2955f5 u0 android/com.android.internal.app.ChooserActivity} at 13 of 16 (after Window{15aba993 u0 org.kontalk/org.kontalk.ui.ContactsListActivity})
07-05 13:53:53.370 W/PackageManager(3484): Failure retrieving resources for org.kontalk: Resource ID #0x0
```

![screenshot_2016-07-05-21-16-41](https://cloud.githubusercontent.com/assets/1158465/16596879/3973a668-42f6-11e6-923f-85be63dcaae8.png)

Am using a Galaxy Note I (GT-N7000). It is running the NightOwl ROM, a port of Cyanogenmod customized for this device. 
I would be happy to share any further information if needed.

**Comment by daniele-athome** [comment]
Thanks for your report.
I've inspected the relevant part of code. When Kontalk checks for available apps to deliver the invitation, it automatically excludes itself (because Kontalk can handle the "send" action when you share text to send from other apps; this is to avoid recursion) and shows all the other apps available.
This is however done *after* the list of available apps has been retrieved. The app blindly checks if the list contains more than 1 app and *then* checks if Kontalk is inside the list.

This can lead to Kontalk stating that there is no app if Kontalk has been disabled for the ACTION_SEND intent. I assume you have other apps available for sending text (the Android stock Messaging app is one of them, but I guess any IM app will do). If that's the case, I don't want to exclude any possibility so I'll ask you: do you use some application to disable app components (e.g. intent filters, alarms, etc.) or some other security/privacy feature in your firmware that might interfere?

**Comment by tetris4** [comment]
Hi Daniele,

No I don't use any kind of application or security feature that would block that, at least none that I know of. 
Yes I have other messaging apps installed (the standard messaging app that comes with cyanogen and libresignal come to mind). 
What is interesting is that only kontalk suffers from this. All the other apps seem to show a relevant menu when I hit invite users, but perhaps they are not calling the same function (?).
Fwiw, the 'share' menu in Kontalk works fine.

Forgive my ignorance but what does 'ACTION_SEND' invoke? Does kontalk only use sms for invitations?

**Comment by daniele-athome** [comment]
Ok, thanks @tetris4.

ACTION_SEND is a generic Android action issued by applications when they want to send something (text, picture or anything else). It's like an instruction to the system stating: "please send this text content to someone, some how". The system then presents a popup to the user for choosing the application to handle that. In your case, no app is found that can handle that text message (i.e. the invitation text message), so the error.
Any app that can handle an ACTION_SEND could be used for sending an invitation (e.g. Hangouts, WhatsApp, Viber, even some non-IM apps).

First of all, I didn't notice the timestamp of the last line of the log (the one I thought it was related to the issue): it's like 3+ seconds later then the actual popup opening:

```
07-05 13:53:46.455 V/WindowManager(3334): Adding window Window{2f715bda u0 PopupWindow:a2a00e3} at 13 of 16 (after Window{15aba993 u0 org.kontalk/org.kontalk.ui.ContactsListActivity})
07-05 13:53:48.985 D/MessageCenterService(12229): Message Center starting - Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }
07-05 13:53:49.535 V/WindowManager(3334): Adding window Window{1c2955f5 u0 android/com.android.internal.app.ChooserActivity} at 13 of 16 (after Window{15aba993 u0 org.kontalk/org.kontalk.ui.ContactsListActivity})
```

(Technical notes to myself :-)
The `ChooserActivity` seems to be launched, so I can guess here that the message is generated by the system. I can see there are many ways of generating an intent chooser (for example, just copying the Intent could not be enough; **be sure to set the package name from resolveInfo**).

I'll fix this and give you a test APK to try it out, if it's ok with you @tetris4 (it can be installed alongside your current Kontalk installation).

**Comment by daniele-athome** [comment]
I don't need if this is going to fix the issue, but for now I've added what I think is a workaround. Let's see what happens on your platform. You'll find an apk to use soon (4.0.0-alpha6) in the [group chat issue](https://github.com/kontalk/androidclient/issues/179). You may subscribe to it if you'd like.
