### ISSUE TITLE
Public Key Infrastructure password problem

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#783]
I see that Kontalk has an ability to generate new public key. So the password for the new public key must be new. If you accidentally forgot your password (like me) what you gonna do? Generate new key, so you will have ability to create new password. Ok, generated new Public Key but the problem is that I can create new password. Please fix it.

**Comment by daniele-athome** [comment]
I'm sorry I'm not following. Generating a new key will ask you for a new password, it doesn't matter if it's new. I mean you're creating a whole new identity, the old one will become void (and your contacts will be warned about this change).

**Comment by Buranek** [comment]
Yes and I mean that **exporting** password also must be new and user must be asked to write new password.

**Comment by daniele-athome** [comment]
Exporting the key does ask you for a new password (if it was not set before, otherwise it asks the password you set before). This is by design, I don't see the problem (maybe I'm not getting your point).

**Comment by Buranek** [comment]
Of course. I think that new password must be everywhere. It seems like it's the only ability to retrieve forgotten password.

**Comment by daniele-athome** [comment]
Yes, and another way to more easily break the private key. There is a reason why the password check is there: if you forget the password, there is no normal way to recover it (unless having root access, but that's a whole other story, not covering possible attack vectors here).
Despite it would be possible to break the private key by using extreme measures (e.g. root access), am I the only one here thinking that some protection is better than none?
@Buranek please elaborate more deeply on this. I mean why I should take this course of action and why it would be more secure than the current way of working. I'd also like to hear other opinions - anyone listening, please raise your voice.

**Comment by abika** [comment]
I still don't get it. If you forgot your password you have to generate a new key. Anything else would make the use of a password meaningless.
And after creating a new key you can set a new password and an old password is not used anywhere, right? That's how it should be.

You simply can't have both: Secure key protection with password AND password recovery for forgotten passwords at the same time.

**Comment by Buranek** [comment]
Ok, now I get it. Is there any way to recover forgotten password with root?

**Comment by daniele-athome** [comment]
In theory, they should be stored in the Android Account Manager, but I don't really know how to retrieve them (and they are probably encrypted somehow).

**Comment by Buranek** [comment]
Yes, encrypted as MD5 and is easily decryptable.

**Comment by abika** [comment]
Huh? I doubt md5 is used which is known to be insecure 10years+. But even if so the password is not "easily decryptable".

**Comment by Buranek** [comment]
From first attempt with https://hashkiller.co.uk/md5-decrypter.aspx

**Comment by abika** [comment]
ok, with a rainbow table its indeed quite possible (depending on the password). And md5 is really used? How can this be?

**Comment by daniele-athome** [comment]
I don't think Android account manager has an hashed version of the password since it has to be provided to the app in cleartext. It's probably encrypted symmetrically somehow, but that's Android internals, not really documented anyway.
