### ISSUE TITLE
Uncontrollable external contacts

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#784]
It's normal I think to add some Jabber contacts to Kontalk. But the only way is to ask them to add you. You can't normally add Jabber contact to Kontalk from Android client. I think it's real through database editor but that's not normal.
By the way: is it real to add OTR support to Kontalk to securely contact with normal Jabber contacts?
So what I want: controllable roster.

**Comment by TheLastProject** [comment]
For the OTR thing, see #123 or #496.

Non-Kontalk XMPP contacts should probably be added to the Android contacts list so they can be removed/renamed/etc. Currently, once someone adds you there is no way at all to remove them.

**Comment by daniele-athome** [comment]
As a workaround for removing a user, for now you can use the block feature: it will actually unsubscribe from a user and then block it. As for the rest, @TheLastProject already mentioned the relevant open issues, so I'm marking this as duplicate. Thanks for reporting though!
