### ISSUE TITLE
Too small icon

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#785]
That's minor problem, anyway it exists. Look at the Conversations icon — it's big enough and at the Kontalk icon — it's tiny comparing to Conversations icon
![screenshot](https://cloud.githubusercontent.com/assets/6697344/17659180/f5ca2b9c-62e1-11e6-812a-b1103a327f36.png)

P.S.: If you want, you can get these green icons here: https://github.com/Buranek/pix/tree/master/Android%20style/Launcher%20icons

**Comment by daniele-athome** [comment]
The Kontalk icon size is by design, it's not a mistake.
