### ISSUE TITLE
Android studio import error

### ISSUE THREAD

**Issue by rambabugithub** [kontalk/androidclient#791]
Hi, after import the project into android studio i got this error,please help me

Error:(28, 0) Could not get unknown property 'smackVersion' for project ':client-common-java' of type org.gradle.api.Project.
<a href="openFile:C:\Users\HP\Downloads\New folder (2)\androidclient-master\build.gradle">Open File</a>

**Comment by daniele-athome** [comment]
You forgot to init the submodules:

https://github.com/kontalk/androidclient/wiki/Setup-Android-Studio-project
