### ISSUE TITLE
Problems authenticating

### ISSUE THREAD

**Issue by lupa18** [kontalk/androidclient#792]
**1.** When I try to use the call "last 4 digits" for authenticate, doesn't work. See image: 

![screenshot_20160820-185551](https://cloud.githubusercontent.com/assets/463429/17897366/f2cd621a-6921-11e6-8baa-80dbe63c6f61.png)
 
I tried 3 times (with 3 different calls). None of those numbers works. I think (in this country) there is some kind of proxy-phone and the number calling is not showing correctly. 

**2.** Then, I tried the "other method", and received a sms with the code, but can't use it because, it quickly switches to "put your phone number" screen (the beginning). 

So I got a loop and never can authenticate again (see image). Maybe will be necessary put a button "I already have the sms code", or similar like that.

![screenshot_20160820-194004](https://cloud.githubusercontent.com/assets/463429/17897430/2ee466f4-6922-11e6-96ff-d88fc0af3282.png)

**Comment by Buranek** [comment]
Saw the same problem.

**Comment by daniele-athome** [comment]
For the first problem I'm afraid I can't do anything. We provide a fallback method just to address these kind of issues (mobile telephony can be a pain in some countries).
For the second problem I think I've found the issue, it will be fixed in next alpha.

**Comment by daniele-athome** [comment]
Fixed in c01cdc7.

**Comment by lupa18** [comment]
thanks !
