### ISSUE TITLE
Bb codes support

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#800]
Please add support of text markup via bb codes.

**Comment by TheLastProject** [comment]
BB Code seems horrible. I'd much prefer basic Markdown support if anything, which is also what Telegram supports through their bold bot.

**Comment by daniele-athome** [comment]
I agree, I'm sorry. Markdown is much a better option.

**Comment by Buranek** [comment]
Ok, markdown would be nice if you'll implement it.

**Comment by daniele-athome** [comment]
Opened #801.
