### ISSUE TITLE
(Re-)Adding a user to group does not work on receiver side

### ISSUE THREAD

**Issue by abika** [kontalk/androidclient#804]
Here is the workflow:
* Alice creates a group with Bob and herself
* Bob leaves the group
* Alice adds Bob again, he gets the (correct) message ("Users added: Bob") but the group list still contains only Alice

[And deletion of a group chat does nothing]

**Comment by daniele-athome** [comment]
Thanks @abika, I'll look into it.

**Comment by daniele-athome** [comment]
@abika what do you mean when you say

> [And deletion of a group chat does nothing]

**Comment by abika** [comment]
oh not quite right. Well, if you select "Delete chat" inside a group chat all messages are deleted (except group commands) but the chat itself is not deleted.

**Comment by daniele-athome** [comment]
Yeah that's actually by design. But I should probably rename that menu item to something like "delete messages". Or I could keep it like that and put a "also leave group" checkbox in the confirmation dialog. What do you think?

**Comment by abika** [comment]
Why isn't it possible to remove the entire chat? When deleting one in the desktop client the user automatically leaves the group (with warning message) and the chat is deleted.

**Comment by daniele-athome** [comment]
Because I was trying to introduce the concept of "clear a chat" without actually deleting it. In case of groups it makes sense since you might want to delete group history without actually leaving it.

**Comment by daniele-athome** [comment]
I agree the feature itself needs to be redesigned. As a workaround for now, you can completely delete the chat and leave the group if you delete the thread from the main activity (I know, ugly).

**Comment by abika** [comment]
Ah, ok. In this case the option label string just needs to be changed.
