### ISSUE TITLE
Sticker Integration

### ISSUE THREAD

**Issue by tushar-bhatia** [kontalk/androidclient#810]
Hello guyyz....m glad to tell you that I have integrated stickers in the kontalk just by sending a unique code like emojicons....

**Comment by TheLastProject** [comment]
For those as confused as me seeing this issue pop up out of nowhere, some context is available on kontalk/desktopclient-java/issues/71.

**Comment by tushar-bhatia** [comment]
yes that was my mistake...That issue has to be opened here but i accidently opened it in desktop client....But now I got success in integrating the stickers so i confess here

**Comment by daniele-athome** [comment]
[I thought I was clear on the use on Unicode](https://github.com/kontalk/desktopclient-java/issues/71#issuecomment-244891426):

> Anyway, stickers are not handled by unicode (like emojis), so using a code is not really an option here.

Or am I misunderstanding your comment?

**Comment by tushar-bhatia** [comment]
well @daniele-athome you said that stickers are not handled by unicode...!!!! I clearly remembered that comment and you told me to transfer the complete image..!!! But i contradict you idea of transmitting the complete sticker. Anyways thats for your concern

**Comment by daniele-athome** [comment]
Ok so what's your implementation then? Show us :-)

**Comment by tushar-bhatia** [comment]
i hosted a service which provides 256*256 png images with their unique code....The unique is build by md5() function which returns a 32 bit unique code....service returns all the stickers with their code in jSON format...I parse the jSON and store all the stickers in HashMap containg unique code as a key and sticker as a object...When i click on any sticker...It returns its unique code and i Transmitted that unique code as a TextComponent.....In the message list adaper I check the content of the message being sent...If it is a TextCompont and its content is any of the key in my HashMap then I manually added a ImageCompone in the ViewStub instead of TextComponent and set the sticker bitmap as its imageBitmap....

**Comment by daniele-athome** [comment]
Ok let's see it then! Would you prepare a pull request for that? Also what about the hosted service? Is it free software too? What about the sticker artworks?

**Comment by tushar-bhatia** [comment]
well I have also added some cool features like you can change your app theme at any time....Changing theme will modify your app look an feel compleely..!!! Now i am looking forward to integrate the audio and video calls..!!! This app is gonna make boom..!!!

**Comment by daniele-athome** [comment]
Alright, that's great but what about some pull requests so anybody can see it?

**Comment by tushar-bhatia** [comment]
Actually I work for a company and m not allowed to share the code because of the NDA clause between the client and company..!!!

**Comment by daniele-athome** [comment]
I thought you were contributing to the project. Good luck then. Be aware of [GPL terms](https://www.gnu.org/licenses/gpl-3.0.en.html) though.

**Comment by h-2** [comment]
@tushar-bhatia what was this thread about then? What a shame... While for me it is not really crucial, I think stickers are used by many people, and if one could e.g. query telegram servers to use their stickers that would probably make many people happy.
@tushar-bhatia maybe you can get your company to allow you to contribute to open source projects?

**Comment by tushar-bhatia** [comment]
yes I agree with you but there are certain terms and conditions which we all have to follow..!!!
