### ISSUE TITLE
Clock sync issues

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#813]
Freaking unbelievable.

```
gpg: key [...] was created 37 seconds in the future (time warp or clock problem)
```

Was causing a key import error. For now this has been worked around on the server with the `--ignore-time-conflict` option to gpg2, but that can't work in the long run. Either:
- use a server-provided timestamp to create the key
- warn the user about the wrong time and tell him/her to adjust

Remember to revert kontalk/tigase-extension@97e4e01c048df9002e735e840bd6c7ab1ceb59dc once this is done.

**Comment by tomterl** [comment]
Just my 2¢: option one is the way to go; while option 2 is correct - users should set up their devices correctly - it will not help adoption, and I seriously hope to get my extended WhatsApp contacts to switch , god knows how their clocks are ticking ;-)
