### ISSUE TITLE
Switch to another emoji library

### ISSUE THREAD

**Issue by arielenter** [kontalk/androidclient#814]
I just installed kontalk from f-droid, and I think is awesome.

I have one question. When I want to use emojis, I only see apple's emojis set. Aren't these emoji copyrighted and not under any license that allows its 3rd-party use?[1] Did this emojis came with kontalk or where they picked from my phone?

I saw this publication about kontalk getting to use a more permissive licensed emojis:
https://github.com/kontalk/androidclient/issues/8
Is it still not possible to use different emojis other than apples'?

How can I use a more free software friendly emojis set?

Thank you.

[1] https://github.com/slp/Telegram-FOSS/issues/35

**Comment by daniele-athome** [comment]
Apple Emoji's licensing is indeed unclear. I even found a statement from Apple itself stating that they are not licensed. But then there is the copyright.

We are using [emojicon](https://github.com/rockerhieu/emojicon) for our emoji right now, and we have a issue open (#461) to support its builtin "use system emojis" flag, but that would be available only from Jelly Bean (I believe 4.2.2 at least).

That said, I can accept a proposal to switch to a different library, but I don't really have time right now. This could be addressed in the future or if you or anyone feels up to the task, you're welcome to do it of course :-)

**Comment by TheLastProject** [comment]
Something which uses Emoji One is probably a nice choice

On 15 September 2016 20:12:42 CEST, Daniele Ricci <notifications@github.com> wrote:
>Apple Emoji's licensing is indeed unclear. I even found a statement
>from Apple itself stating that they are not licensed. But then there is
>the copyright.
>
>We are using [emojicon](https://github.com/rockerhieu/emojicon) for our
>emoji right now, and we have a issue open (#461) to support its builtin
>"use system emojis" flag, but that would be available only from Jelly
>Bean (I believe 4.2.2 at least).
>
>That said, I can accept a proposal to switch to a different library,
>but I don't really have time right now. This could be addressed in the
>future or if you or anyone feels up to the task, you're welcome to do
>it of course :-)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/814#issuecomment-247406723

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arielenter** [comment]
I wanted to say thank you. I just made a 10 euros donation. Hope it helps, even if it's just a little. I'm a free software enthusiast, and I really appreciate kontalk. The fact that I can contribute by coding is awesome to me. Thank you. Although I lack the knowledge at the moment, but hopefully I'll change that in the future. Never the least, really, thank you so much for your work. I truly appreciate it :+1:

**Comment by daniele-athome** [comment]
@arielenter thanks for your donation and your belief in the project! They're really appreciated. Keep spreading it! Looking forward to your code contributions.

**Comment by arielenter** [comment]
Just to mention that Telegram-FOSS seem to have gotten emojiOne and twemoji working

https://github.com/slp/Telegram-FOSS/issues/53#issuecomment-249371694

I just thought it would be interesting news, not to pressure at all ok? xD

For me it's not essential. Just a little think to have in the future :)

**Comment by daniele-athome** [comment]
Thanks for the pointers @arielenter, I will keep them under observation.

**Comment by TheLastProject** [comment]
I have to add to this that I can unfortunately no longer recommend EmojiOne due to their change to a more restrictive licensing scheme: https://github.com/Ranks/emojione/issues/488

**Comment by Crissov** [comment]
Emojione 2.x will remain free and there is a fork that shall be kept up-to-date: https://github.com/EmojiTwo/emojitwo/

**Comment by jvschiavo** [comment]
Why not just use Noto color emojis?

**Comment by relan** [comment]
Google made their own emoji library, but only for API 19+: https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat.html
