### ISSUE TITLE
Mark Groupchats in Chatlist

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#818]
Is it a good idea to mark Groupchats (e.g. by text colour or other things) to make they different to 1to1 chats?

**Comment by daniele-athome** [comment]
Good idea. First of all it should have a different default avatar than a contact. What else do you suggest?

**Comment by TheLastProject** [comment]
Telegram does this by prefixing all groups with a group icon:
![Google Play screenshot](https://lh3.googleusercontent.com/W_PpbXcnG2nVWykfyQX2_yGTpoBhXZRh8Dc1q2eti5QVgnkk3SrnYJDoM5PEboEW4Q=h900)

**Comment by webratte** [comment]
@TheLastProject This seams not different for me.
On your screenshot I searched a few seconds to find the prefix.

But at the moment I have no better idea.
I will think about it.

**Comment by webratte** [comment]
What about a verry very light gray (just a little bit darker then the other chats) background similar while mark by long press?

**Comment by daniele-athome** [comment]
No, sorry, that's against Android UI rules: background should reflect state, not type (except in some rare situations, which Kontalk is not).

**Comment by webratte** [comment]
OK, that sounds logical.

**Comment by webratte** [comment]
The more I think about it the more I agree with @TheLastProject.
Other messengers e.g. Threema do it also this way.
So there seems to be no Better way.

**Comment by abika** [comment]
The icon in Telegram is really hard to see imo.

In the desktop client the title font for group chats in dark green maybe this is an option. [And i just noticed this is not very considerate of colorblind people... ]

Maybe an indication in the chat icon? A border or different background (only for the icon)?

**Comment by daniele-athome** [comment]
The group avatar will have a different default icon for now (I will do it soon). After custom group pictures will be implemented, I think the problem should relatively go away for two reasons:

* the custom picture will be easily recognizable by the user
* I've just implemented name prefix for groups (e396a16500728e7baff21f9711eacae9cf90bbb0)

**Comment by daniele-athome** [comment]
Ad-hoc default icon for groups in 303048795ea5cdac9c6ca8b1cc1a12e4dc0e5f68.

**Comment by daniele-athome** [comment]
I've added a group indicator like Telegram does in d9bdb7e2ce29bac1a923883723af56f7fe932565. If you have any other ideas I'm listening :-)
