### ISSUE TITLE
Will there ever be an on-line shared profile picture support in the future?

### ISSUE THREAD

**Issue by arielenter** [kontalk/androidclient#824]
I notice there isn't a way to establish an on line shared picture for your profile yet. For what I can gather, only the pictures I established on my personal phone book are display.

This can be helpful for privacy reason, and I notice that some users like it this way, but I think that having the choice to do it or not would be good in my opinion. For instance, the official desktop client displays a warning note in the bottom of the option to change your own profile picture that says: The profile picture is publicly visible. I wouldn’t use a personal picture for it, just an avatar anyway. Right now, this feature on the desktop client says that it hasn't been implemented on the server yet, or something like that.

Another cool option would be to chose who can see your profile picture. For instance, only show picture to people you have accepted. And be able to decide whether you want to download images public profiles or only use the ones given by you in your phone book would be nice too, as suggested in this post https://github.com/kontalk/desktopclient-java/issues/65

Overall. My main question will be whether or not this feature has been planned or thought out to be implemented in the future, or if it's the current behaviour what is intended to stay.

**Comment by daniele-athome** [comment]
Well, this has been the subject of a debate mainly about privacy and server resources. Avatars would be stored on the server meaning more server resources (we always wanted to be cheap on the server side), and they will be publicly visible - which is a privacy concern that not everyone will understand.
Encrypting avatars in a safe way is not an option (too many recipients involved - e.g. all your buddies).

Another option would be requesting the avatar directly to the user (which will encrypt it for the requestor as a special case), but it's XEP is a bit old and deprecated: http://xmpp.org/extensions/xep-0008.html (only the IQ-request part, which will be replied directly by the client).
Nevertheless, it fits the purpose and I can see a real use for Kontalk. @abika what do you think? I see you've already implemented pubsub-based avatars. It's true that we'll have to use pubsub for public keys in the future (the new OpenPGP xeps), but that's one more metadata to keep in servers.

**Comment by abika** [comment]
It's your server so you can decide if you want to store avatars or not. But consider that using PubSub (XEP-0084) is the current standard and retrieving avatars from other servers with the desktop client works fine.
I have no problem with implementing an additional client-to-client approach, though. 

PubSub has some access model (https://xmpp.org/extensions/xep-0060.html#accessmodels) but I couldn't figure out if and how this is used for user avatars.

**Comment by daniele-athome** [comment]
> But consider that using PubSub (XEP-0084) is the current standard and retrieving avatars from other servers with the desktop client works fine.

That's a nice plus that I'd gladly implement also for retrieval on Android to better integrate with external XMPP services, but for Kontalk avatars loaded from the Android app I'll use a direct client-to-client approach.

>  I have no problem with implementing an additional client-to-client approach, though.

Good! I've opened #826 to address that. I've set it for 4.1.0, so there's time.
