### ISSUE TITLE
Cucumber pictogram

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#838]
Please add cucumber smile.
![cucumber](https://cloud.githubusercontent.com/assets/6697344/19459386/246b61de-94db-11e6-9539-de3c6bb49606.png)

**Comment by daniele-athome** [comment]
I'm not sure I understand what you mean. Is that an emoji?

**Comment by Buranek** [comment]
@daniele-athome yes, emoji.

**Comment by daniele-athome** [comment]
So this is part of the emojis library we are using. I've opened kontalk/emojicon#4.
