### ISSUE TITLE
Kontalk scrolls after copying from list

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#839]
After searching some text and copying message Kontalk scrolls chat down to the bottom.

**Comment by daniele-athome** [comment]
I can't reproduce it on latest master. What version are you using?

**Comment by Buranek** [comment]
@daniele-athome from F-droid.

**Comment by daniele-athome** [comment]
Can you confirm the steps to reproduce please:

1. search for a message within the main screen
2. open a search result
3. long-press a message
4. select "copy text" action

**Comment by Buranek** [comment]
@daniele-athome yes. But the last action is returning to home screen or switching to another app where I want to paste text.

**Comment by daniele-athome** [comment]
Ok so that's actually the same as #840 actually, as mentioned in comment https://github.com/kontalk/androidclient/issues/840#issuecomment-257636288: Kontalk doesn't store the current scroll position on exit. I've opened #853 to fix this and #840.
