### ISSUE TITLE
Disable scrolling to new message option

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#840]
I often receive long messages which takes time to read and contact is writing new. Kontalk scrolls down to new message so there is hard to read previous messages — I need to scroll back again. Please add an option which will disable automatic scrolling to new message.

**Comment by daniele-athome** [comment]
I've just tested it and scroll fix seems to work correctly on my device. What version of the app and of Android are you on?

**Comment by Buranek** [comment]
@daniele-athome Kontalk — latest from F-droid, Android 5.1.

**Comment by OffifialMITX** [comment]
I have something similar: if I get many images and I tap on the first and going back, it automatically scrolls to the end so I have to scroll up to view the next image

**Comment by daniele-athome** [comment]
@OffifialMITX well that's a different behaviour. Kontalk doesn't store last scroll position on exit. I believe @Buranek reported that the message list scrolls down when a new message arrives **while** he's reading past messages, am I correct @Buranek?

**Comment by Buranek** [comment]
@daniele-athome absolutely correct, that's what I'm talking about.

**Comment by daniele-athome** [comment]
Merged into #853.
