### ISSUE TITLE
Bulk message copy

### ISSUE THREAD

**Issue by Fohroer** [kontalk/androidclient#841]
Sometimes I need to copy bunch of messages to clipboard. Please add such ability to Kontalk.

**Comment by TheLastProject** [comment]
Telegram simply places one blank line between each message, prefixing the first message of each user by their name. So an example of multiple copied messages between multiple people on Telegram could look like this:

```
Person One:
Hey

How are you?

Person Two:
I'm fine!

How about you?

Person One:
I'm doing fine too, thanks!
```
