### ISSUE TITLE
Set "submit invitations automatically" by default on

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#843]
I know it isn't a secure suggestion but nobody from my contacts have an idea about encryption and secure communication. This is why I suggest to let inventions be accepted automatically by default. If you don't want to, you can still deactivate it. Or at least let a popup be shown after registration.

**Comment by webratte** [comment]
IMO it's not a really good idea set "submit invitations automatically" by default.

I think it's a better idea to "teach" your friends about secure communication ;-) 

If we use secure messengers and drop the human sense we don't need secure messengers.

Don't forget - it's my personal opinion. Maybe I'm wrong :-)

**Comment by daniele-athome** [comment]
Maybe I didn't understand your question, but accepting chat invitation and accepting a public key fingerprint change is a different matter. In Kontalk design, accepting a chat invitation also marks the public key as trusted so communication can begin immediately after that.
Doing such a decision automatically without user consent is not an option, sorry.

**Comment by OffifialMITX** [comment]
Well, I think, you're right, but maybe a pop up which explains why this option is even there would maybe do it.

**Comment by daniele-athome** [comment]
I'm not sure what you mean. What should I explain exactly?

**Comment by OffifialMITX** [comment]
Well, I mean that some people just don't have an idea about how encryption works so it may be good if there was a short explanation of how you use it and maybe a link for a basic article of how it works.

**Comment by OffifialMITX** [comment]
Noone from my contacts have ever use bencryption before so it ist a bit difficult to explain every time via SMS what they should do.

**Comment by OffifialMITX** [comment]
*used encryption, sorry for that.

**Comment by daniele-athome** [comment]
There is a wiki article here:
https://github.com/kontalk/androidclient/wiki/The-personal-key

It is not linked directly from the app (the Help menu item will bring you to the wiki home page), but I could add a link to that page somewhere, maybe in the identity popup dialog. What do you think?

**Comment by TheLastProject** [comment]
"So it is a bit difficult to explain every time what they should do". Actually I do not think we need help links in this case. If Kontalk's user interface is confusing, we need to make the confusing parts less confusing. Giving people more to read will not make Kontalk easier to use.

**Comment by webratte** [comment]
IMO there is nothing really complicated.
I have only to check is the User who invite me the User I expected. 

And then accept the invitation if I want chat with him/here or don't accept if I don't like it.

I don't know nothing about encryption.

OK if I want be more secure I also can compare the fingerprint.

But this is optional and also not used if we accept invitation automatically.

**Comment by TheLastProject** [comment]
I don't see what's complicated about it either, but @OffifialMITX clearly states that they have to "explain every time via SMS what they should do". It would be much better if we got info on what specific things they need to explain so that the specific UI parts can be made more obvious.

**Comment by daniele-athome** [comment]
Indeed @OffifialMITX. Please go in further detail on what you explain to your friends everytime, we can work on UI/UX of the app.

**Comment by OffifialMITX** [comment]
I don't think that any part of the design is confusing but the people think that it is like in Whatsapp where the phone number is everything needed to start a conversation.

I (almost) always ask if they can deal with Kontalk's design (after they have installed it) and the answer is yes. Of course I say that they have to accept my invitation before we can chat.
After a couple of minutes I ask them why they still don't answer they say that they don't know because I'm already in their contact list.
And then I have to explain again, what they have to do exactly.

Of course, it's not every time exactly like this, but sometimes it's a bit difficult to handle with it.

So my opinion is, there should be either a pop up window after login where it is explained, or a built in tutorial which simulates opening a new chat or a 20s official clip where it is shown. If you want to, I could make such a clip.

**Comment by OffifialMITX** [comment]
> where the phone number is everything needed to start a conversation.

I mean that no submitting from user's side is required.

**Comment by webratte** [comment]
I'm not a Fan of video tutorials.

But I know, if my son (16) has a problem with his computer or his phone he never search for written tutorials. He always search for video tuorials.
The same his friends ;-) 

Maybe we should think about a short Video tutorial.
With subtitles to translate it in different languages.

I belive I have seen Videos in playstore as description for apps.
We could also offer this Video (if @OfficialMITX MAD one) in playstore. It describes a security Feature of Kontalk.

**Comment by daniele-athome** [comment]
> I (almost) always ask if they can deal with Kontalk's design (after they have installed it) and the answer is yes. Of course I say that they have to accept my invitation before we can chat.
After a couple of minutes I ask them why they still don't answer they say that they don't know because I'm already in their contact list.

I believe there is a clear (and pervasive) enough indication of chat invitations: a new conversation is created and when you open it you have those 3 buttons on top (Accept, Identity, Block). If you try to send a message it will be blocked because you've not accepted the invitation yet (a message is showed to explain this). And chat invitations are also notified on the system status bar. If you tell me that people are not seeing all those signals... adding a video tutorial explaining just this seems a bit exaggerated.
Or maybe I didn't get your exact point?

**Comment by OffifialMITX** [comment]
Well I also don't know why others have such problems, maybe it's only because they just aren't really interested.

What I actually meant was not really a tutorial but a quick start animation / clip which shows where you have to press to start a conservation. Here I think about people who don't like discover new app's functionality by themselves but just wont everything to work, in best case without doing anything. 

But I think also that there should be an introduction video, like @webratte mentioned, but not a tutorial but something like an extended version of Kontalk's description with a maximum duration of 1 minute.

If you decide to do it, my suggestion is to do it after / shortly before the official release of 4.0.0 so the group chat option can be mentioned.

You still can count on me to do both. Maybe not the introduction video because i think that it should contain at least an interview of the main developer. I'm probably not able to make it.

**Comment by daniele-athome** [comment]
> What I actually meant was not really a tutorial but a quick start animation / clip which shows where you have to press to start a conservation

Again, here I think that if the UI is not easy enough, we should find room for improvement. When opening Kontalk for the first time (after registering), the main screen shows a quick text on the center telling the user what to do ("to write a new message bla bla") and the floating action button on the bottom right corner is quite self-explainatory for Android users (it's a common UX aspect, I tend to follow Google guidelines just for that reason).

**Comment by OffifialMITX** [comment]
That is actually what I meant when I talked about a pop up window after login ( I didn't write first because you usually login only once).

**Comment by daniele-athome** [comment]
> That is actually what I meant when I talked about a pop up window after login ( I didn't write first because you usually login only once).

The message in the window background appears all times when you don't have any existing conversation, not just the first time.
