### ISSUE TITLE
Use draft to add bugreport to GitHub 

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#845]
like this I have stolen from https://github.com/k9mail/k-9/issues/new ;-)

I belive it's easier for users and devs if there a clear structure.

*****************************************************************************

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
Kontalk version:

Android version:

**Comment by daniele-athome** [comment]
Thanks @webratte!
