### ISSUE TITLE
Kontalk channel inside Kontalk

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#851]
What about a channel inside Kontalk itself to keel up to date for those, who don't use Twitter?

**Comment by TheLastProject** [comment]
I am pretty sure there was an issue for so called "service announcements" somewhere, but I can't find it. It seems like a good idea though.

**Comment by daniele-athome** [comment]
I already implemented a service channel server-side that required minor fixes on the app, it will be available in version 4.0. You will receive important notifications from a special user.

@TheLastProject you might be referring to issue kontalk/tigase-extension#25.

**Comment by TheLastProject** [comment]
That was indeed the issue I was referring to. On a related note, it would be great if you could receive these Kontalk notifications in the user's language, instead of only in English as I assume is probably the case now. That will probably be more complicated but a good thing to consider making possible somehow. I would be willing to translate these notifications into Dutch if it ever gets implemented.

**Comment by daniele-athome** [comment]
That would be somewhat difficult to maintain. I mean those kind of messages are sent by server administrators and are usually sent immediately after an event occured (except for planned maintenance). In this case I think a better option would be using an automatic translation system (on the client side).

**Comment by webratte** [comment]
I don't know if my idea is possibl or usfull.
Still:

I belive most things what Admins have to say are:
-Planed Server downtime
-Online again

And so on.

Maybe you could put some standard sentences (with placeholder for time...)into the location XML for client and the server admin just send a command.

I think human translations most much better then machine translation.

Of course Admins still need a way to send free text in some cases.
In this case can work a machine to translate.

This is just a template to think about solutions ;-)

**Comment by daniele-athome** [comment]
Thanks @webratte, you're right that there could be a few fixed messages that can be translated beforehand. Others messages, as you said, will use machine translation.
