### ISSUE TITLE
[Minor] Basic highlighting

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#852]
This is probably not the most important thing right now, but it would be nice if there have been options for highlighting.

Either like Whatsapp with *x* _x_ and so on, or, what I would prefer, basic HTML Styling, you know, <b>, <i>, <s>, <u>, <sub> and <sup>.

But this is what I'd prefer, I know, it's neither a useful feature nor something most of the users would be happy to learn. It's just something I'd like to have.

**Comment by TheLastProject** [comment]
Seems to be a duplicate of #801

**Comment by daniele-athome** [comment]
> Seems to be a duplicate of #801

It is. Thanks for reporting anyway.
