### ISSUE TITLE
All contacts are marked as blocked once you block someone

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#855]
I have recently blocked one of my contacts and now the message that I've blocked this contact appears on every conversation.

It isn't shown when writing a message but after sending it comes back.

Android 5.1.1, latest built from F-Droid

**Comment by OffifialMITX** [comment]
Only my own contact doesn't show this message.

**Comment by daniele-athome** [comment]
Thanks for reporting. I can't reproduce this on 4.0 at the moment.
Messages to other unblocked users do get through right?

**Comment by OffifialMITX** [comment]
Yes, but it can get complicated if you block multiple contacts.

**Comment by daniele-athome** [comment]
Sure, just wanted to know if it was blocking communication :-)
I'm assuming you didn't take part in the 4.0 alpha testing?

**Comment by OffifialMITX** [comment]
No, I don't even know how to...

**Comment by OffifialMITX** [comment]
Something interesting - I have unblocked that contact, then I had to figure out that on every single contact I had to:

1. Unblock it
2. Press on the chat settings button
3. Close chat settings
4. Go back to the chat overview

Only after that the message isn't shown anymore.

**Comment by daniele-athome** [comment]
I found the cause of the bug. The method that was supposed to mark a user as blocked, in fact it was marking all users blocked :S a workaround for you is to trigger a contact sync (new chat screen > refresh), this should reset the flags to the correct state. Thanks for the help!
