### ISSUE TITLE
Sending and receiving images to/from other XMPP clients

### ISSUE THREAD

**Issue by karlitos** [kontalk/androidclient#861]
### Expected behavior
If i turn the encryption off I am able to send and receive messages to/from other XMPP clients. Tested with _Conversations.im_ and _AstraChat_ on Android. I would expect, that the images will be properly displayed inline in Kontalk and other XMPP messenger.

### Actual behavior
Sending image **FROM Kontalk TO Conversations** client results in image displayed inline in Conversations client.

Sending image **FROM Conversations  TO Kontalk** results in text message containing link to the image.

Sending image **FROM Kontalk TO AstraChat** client results text message containing link to the image.

Sending image **FROM Conversations  TO Kontalk** results in text message containing link to the image. Plus the link is not working.

### Steps to reproduce
1. Turn encryption off in Kontalk
2. Send an image to a account in some 3rd party XMPP messenger
3. Send an image from an account in some 3rd party XMPP messenger

### Environment

Kontalk version: 3.1.10 Google Play and 4.0.0. Alpha 8 Goole Play
Android version: 5.2
Device model: Motto G

### Other

Very interesting is the inconsistent behavior with the Conversations client. Images send FROM Kontalk are displayed fine but messages sent TO Kontalk are displayed as text message with link IN Kontalk.

I am not saying in any way that this is Kontalks fault, but it would be interesting to know why this happens. Sending images between AstraChat and Conversations results always in text messages with a link.

**Comment by daniele-athome** [comment]
Thanks for detailed report @karlitos. I guess this has to do with the way Conversations sends images vs. what Conversations supports for images that are received. I will investigate and get back to you.

**Comment by abika** [comment]
Have to say this is a problem on Kontalk side. Conversations does not send the Kontalk specific `type` attribute in the OOB extension.

Compatibility with the Desktop client is fine. It is not using `type` and `length` at all for incoming messages and instead `Files.probeContentType(path)` for MIME detection (the privilege of having a Desktop platform.)

And Conversations uses just the file extension when I see this right: https://github.com/siacs/Conversations/blob/9d0a33337218fbbd8852239fad374f495b4a4243/src/main/java/eu/siacs/conversations/utils/MimeUtils.java

**Comment by karlitos** [comment]
Thanks for investigating this.

There is also the `MimeTypeMap#getMimeTypeFromExtension()` method, but it is case-sensitive, so _image.JPEG_ will return _null_

Anyhow in the first line you should maybe focus on jp(e)g files which I guess will make 95% of all transferred images.

**Comment by daniele-athome** [comment]
I guess it couldn't hurt to fallback to extension-based MIME (custom) detection, like Conversations does (the code is actually from Android AOSP).

**Comment by daniele-athome** [comment]
I've implemented automatic MIME detection. It should be working with Conversations and other clients too (sorry, I only did manual testing - as in forged `<messages/>` from another XMPP account), but it should be tested with some other servers supporting HTTP upload extension. This will be present on the next release so you'll have a chance to test it.
