### ISSUE TITLE
Crash when clicking back arrow in group member view

### ISSUE THREAD

**Issue by StefanBrand** [kontalk/androidclient#862]
### Expected behavior
No crash

### Actual behavior
Crash

### Steps to reproduce
1. Open a group chat with 4 people, including yourself. One person is not authorized and Kontalk shows fade-in notification prompting user to verify that person in a private chat.
2. Give the group chat a name.
4. Type a draft and then remember that not all people are verified (it's not possible to send the message).
3. Go to the group member view.
4. Click the back arrow in the upper left corner.
5. Kontalk crashes and cannot be restarted, not eben after trying to reinstall it. I fear that I'll have to clear data (clearing cache of the app doesn't do the trick).

### Environment

Kontalk version: Kontalk Alpha8 Basic.

Android version: Android 4.4.2

Device model: Fairphone 1

### Other

I'll try to catch a log. I just received a private message and could open that chat via the notification that was shown in the status bar. Also in the PM view Kontalk crashes when I click the back arrow.

**Comment by StefanBrand** [comment]
I sent you a log. This line looks suspicious to me:

```11-21 18:09:04.176 E/AndroidRuntime( 4870): java.lang.UnsupportedOperationException: Unknown group command: Hello everybody. This is a group chat consisting of [Name1], [Name2], [Name3] and me. Most of us are on Kontalk Alpha 8. Can you confirm that you received this message as a group chat?

As outlined above that message was never sent.

**Comment by daniele-athome** [comment]
```
java.lang.UnsupportedOperationException: Unknown group command: [MESSAGE BODY]
	at org.kontalk.message.GroupCommandComponent.getTextContent(GroupCommandComponent.java:230)
	at org.kontalk.ui.view.ConversationListItem.bind(ConversationListItem.java:218)
	at org.kontalk.ui.adapter.ConversationListAdapter.bindView(ConversationListAdapter.java:67)
	at android.widget.CursorAdapter.getView(CursorAdapter.java:254)
```
