### ISSUE TITLE
Kontalk crashes when accepting untrusted personal key

### ISSUE THREAD

**Issue by karlitos** [kontalk/androidclient#863]
### Expected behavior
The key will be accepted

### Actual behavior
Kontalk crashes

### Steps to reproduce
1. Turn encryption off
2. Start a new chat with a XMPP contact (@elaon.de)
3. Warning message appears
4. Click on Details
5. Click on Accept

### Environment

Kontalk version: 4.0.0-alpha8

Android version: 6.0.1
Device model: Galaxy S7

### Other

It does not happen when you click on **Identity** first an THEN **Accept**

Some screenshots documenting the behavior.

<img src="https://cloud.githubusercontent.com/assets/3693437/20503874/f42735cc-b044-11e6-8ea7-6e0ec0476734.png" width="180">
<img src="https://cloud.githubusercontent.com/assets/3693437/20503875/f42bda3c-b044-11e6-9772-e2e5977ca759.png" width="180">
<img src="https://cloud.githubusercontent.com/assets/3693437/20503876/f42dac2c-b044-11e6-9745-21914c00d170.png" width="180">

**Comment by andreasspeck** [comment]
Just to confirm this with alpha8-basic on Cyanogenmod-12.1 (Android-5.1.1) on HTC Desire S (I know it is an old phone).

I just updated from Kontalk-3.1.10 (F-Droid) to alpha8, exporting the private keys first, uninstalling, and then importing my private keys into the new Kontalk. I had to accept all keys, and as described by @karlitos:
- when you go on details and from the options there choose Accept, Kontalk crashes, It tells you however before that you should check the identity and verify it
- when you first go to Identity and then select Accept, it works fine.

I think you could either enforce that people go to Identity first (do away with the Accept option, and replace it with Verify Identity), or you need to fix the crash. It might not be bad to enforce that people at least have to look at the Identity info first ;-)

**Comment by karlitos** [comment]
> I had to accept all keys

How does it work ? Do you need accept them one by one or can you open the identity details view for all of them Combined ? Accepting multiple keys by clicking Identity -> Accept over an over would be super annoying.

**Comment by daniele-athome** [comment]
Fixed in dda60e8162b90ca1015974bae6df2091c7306efe.

**Comment by daniele-athome** [comment]
> How does it work ? Do you need accept them one by one or can you open the identity details view for all of them Combined ? Accepting multiple keys by clicking Identity -> Accept over an over would be super annoying.

Yes, every single user has to be accepted the first time. You can have automatic invitation accepted from Kontalk settings though. But please note that it will also blindly trust any unknown key (but not key changes).

By the way, key trust settings are saved in the personal key exported archive, so when you import it again you'll have the same keys already trusted.
