### ISSUE TITLE
Sharing to groups

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#864]
It is currently not possible to share content to groups from other apps. Modify the share screen to show existing conversations (and groups) and a *new* button to begin a new one.

**Comment by TheLastProject** [comment]
Telegram simply uses the screen of currently active chats (like the one you see when you open Kontalk) without the new chat button. This means you can't share with any contact unless you've sent them at least one message but I only noticed that now by specifically thinking it through, it doesn't seem to be an issue during normal usage

**Comment by daniele-athome** [comment]
One more reason to add something that Telegram doesn't have :D
Besides, I've seen other IM apps showing this specific feature of creating new conversations on-the-fly.
