### ISSUE TITLE
is Kontalk-4.0.0-alpha8-googleplay.apk download not available any more?

### ISSUE THREAD

**Issue by arielenter** [kontalk/androidclient#867]
Today I was hopping to download and try Kontalk-4.0.0-alpha8-googleplay.apk , but when I go to:

http://astra.casaricci.it/public/Kontalk-4.0.0-alpha8-googleplay.apk or
 http://astra.casaricci.it/public/Kontalk-4.0.0-alpha8-basic.apk

I got 404 - Not Found. Is there other place I can download it from, or should I wait for the to public beta?

Thank you.

**Comment by daniele-athome** [comment]
I'm sorry but there was a serious crash situations so I had to take it down. Beta1 is expected for December 4th so hang on! Or go to https://forum.kontalk.org/t/exporting-the-private-key-without-access-to-the-android-app/47/5?u=daniele_athome (very unofficial and super-secret debug build by me)

**Comment by OffifialMITX** [comment]
Both links still don't work

**Comment by daniele-athome** [comment]
Beta1 was released yesterday: https://forum.kontalk.org/t/kontalk-4-0-0-beta1-group-chats-are-here/80

**Comment by OffifialMITX** [comment]
Can't you put it on the F-Droid repo in a way only people who are searching exactly for this? E.g. by removing the logo and putting a very technical description?

Or even better create a repository for it?

**Comment by daniele-athome** [comment]
It's already like you say: auto upgrade is disabled because it's a beta, therefore you have to manually go to Kontalk info screen in F-Droid and choose 4.0.0-beta1.

As for the repository, I don't think it's a good idea because: 

1. It shall be manually added as a repository 
2. It would have a different signature therefore requiring uninstall/reinstall everytime

**Comment by OffifialMITX** [comment]
I'm using IceCatMobile 38.8.0 but now as you mentioned it doesn't seem to be up to date but still latest built in F-Droid. I'll look for another browser. I've tried Orfox 45.5.1 esr but it doesn't show anything.

What do you mean with "Kontalk info screen in F-Droid"? I only can see the version 3.10.0 or didn't I get it right?

I don't think that both adding the repo and reinstall every time is a very big problem as far as it is still an easier way to keep up to date when a new version comes out.

I don't know much about programming, but shouldn't it be a simple way to grab an app like getChromium and rewrite the code for the Kontalk beta?

One last question, I've read about the beta in the group chat discussion but I couldn't find it so where is it mentioned and can't you put a link in the readme.md?

**Comment by arielenter** [comment]
I had the same problem, but didn't have any problem visiting https://github.com/kontalk/androidclient/releases/tag/v4.0.0-beta1 where the apk really is. Try it out and see if it works for you too.

**Comment by OffifialMITX** [comment]
Thank you very much, I'm really new to github & co. so I just don't know yet how everything works so I guess, @daniele-athome , it shouldn't be put in the readme.md, but what about F-Droid?

P.S. Still thank you a lot, @arielenter .

**Comment by OffifialMITX** [comment]
Well now I see why I haven't notice it before, I usually using my mobile browser and the mobile github version has no links to the releases.

Also, sadly, the new version can't be installed, may it be, becuse I#ve installed it trough F-Droid? I really don't want to uninstall the last version only to find out that it still doesn't work.

**Comment by daniele-athome** [comment]
> Also, sadly, the new version can't be installed, may it be, becuse I#ve installed it trough F-Droid? I really don't want to uninstall the last version only to find out that it still doesn't work.

Exactly. You can't install official updates over the F-Droid ones or vice-versa. You'll have to use either released packages by us or packages by F-Droid. Besides, I don't think it's a good idea to make too many release channels: we provide apks just as a fallback. All of you should be using a package manager, either Google Play or F-Droid, to always guarantee the latest is installed. F-Droid delay is just 24-48 hours anyway.

**Comment by arielenter** [comment]
I just sent an error log. Kontalk seems to crash when I'm added to a group and I can't open the app anymore. I'll paste the log here to just in case is needed:

`12-06 17:53:50.509 E/AndroidRuntime(5292): java.lang.RuntimeException:
Unable to create application org.kontalk.Kontalk:
java.lang.UnsupportedOperationException: Unknown group command:
5e99c925d4768b430cc8ea1397020eb6f20c36df@beta.kontalk.net;create:5e99c925d4768b430cc8ea1397020eb6f20c36df@beta.kontalk.net;41f6f50f9348dc6389c9634cc61912c2c3bd32aa@beta.kontalk.net;36f26397266570f9bfc8059b69d6aa3c86e02220@beta.kontalk.net;
12-06 17:53:50.509 E/AndroidRuntime(5292): Caused by:
java.lang.UnsupportedOperationException: Unknown group command:
5e99c925d4768b430cc8ea1397020eb6f20c36df@beta.kontalk.net;create:5e99c925d4768b430cc8ea1397020eb6f20c36df@beta.kontalk.net;41f6f50f9348dc6389c9634cc61912c2c3bd32aa@beta.kontalk.net;36f26397266570f9bfc8059b69d6aa3c86e02220@beta.kontalk.net;
12-06 17:53:50.509 E/AndroidRuntime(5292):      at
org.kontalk.message.GroupCommandComponent.getTextContent(GroupCommandComponent.java:230)
12-06 17:53:50.509 E/AndroidRuntime(5292):      at
org.kontalk.ui.MessagingNotification.updateMessagesNotification(MessagingNotification.java:310)
12-06 17:53:50.509 E/AndroidRuntime(5292):      at
org.kontalk.Kontalk.onCreate(Kontalk.java:190)
12-06 17:54:12.080 I/ActivityManager(1936): Process org.kontalk (pid
5292) (adj 9) has died.`

I'll try uninstall and install back and see what happens. I'll report back later.

**Comment by daniele-athome** [comment]
I got your log, thank you! I'll analyze and fix it ASAP.
