### ISSUE TITLE
Disable all services and receivers while offline

### ISSUE THREAD

**Issue by Spielmops** [kontalk/androidclient#869]
I would be happy to have a messenger-app that can be disabled, because I don`t want messages for some time or I don't need a messenger for a month.

status now: if I don't want mesasages, I have to cut the internet-connection, but if I need the connection eg. for Firefox, that's impossible. I could temporary force-quit Kontalk, but the next connection-change starts the app. 

If no messages arrive and I do not need Kontalk and want to save power, the same problem arises. My phone is rootet and I can disable the autostarts of Kontalk, but that doesn't last long, the autostart is enabled again, if I use the app.

So what can I do (and I don't want it): uninstall!

So why not introduce a "disable"-function?

Spielmops

**Comment by TheLastProject** [comment]
Is "Go offline" not good enough? It's the first option in the menu on the main screen of the app.

**Comment by Spielmops** [comment]
No, that leaves the power-consumption.

**Comment by daniele-athome** [comment]
Hello! Thanks for reporting. It makes sense to disable everything while offline (the app shouldn't be activated on any network event while offline anyway).

**Comment by daniele-athome** [comment]
For the record: force stopping an app does inhibit any event trigger until the app is manually opened by the user.
