### ISSUE TITLE
Migration to XMPP

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#87]
_From [daniele.athome@gmail.com](https://code.google.com/u/daniele.athome@gmail.com/) on October 03, 2013 13:45:47_

This issue will track the migration process to XMPP.

_Original issue: http://code.google.com/p/kontalk/issues/detail?id=140_

**Comment by daniele-athome** [comment]
Switch to XMPP is completed (currently beta, soon to be public). Closing.

**Comment by moshpirit** [comment]
WOW, that's great news!! but we'll be able to use Kontalk as any other IM client? (sorry if I'm bothering you)

**Comment by daniele-athome** [comment]
@moshpirit no, you will need a Kontalk server on the other side - the phone number based account requires some extensions to be implemented. However it will be soon possible to add other XMPP contacts hosted out of the Kontalk network.
And you will also be able to use any standard XMPP client. (e.g. Pidgin, for which there is also a plugin hosted here in repository `client-adapters`).

**Comment by moshpirit** [comment]
Ok, thank you

**Comment by margori** [comment]
This is a wonderful news. Thank @daniele-athome

**Comment by iNPUTmice** [comment]
> However it will be soon possible to add other XMPP contacts hosted out of the Kontalk network.

So you are going to federate with other XMPP servers (which is great!) but isn't this contradictory to:

> we trust the users having a real phone number, keeping spammers and bad guys out of the network

**Comment by daniele-athome** [comment]
That's referred to internally registered users. Outside users are out of scope and must be added manually by our users.

**Comment by 2SI3NX** [comment]
@daniele-athome thanks for this feature, its great. It works when i share personal key from android to the xmpp user.  But can i ask how does an android kontalk user add xmpp pub key or username?
