### ISSUE TITLE
Sharing dialogue doesn't disappear when sharing two images in a row

### ISSUE THREAD

**Issue by StefanBrand** [kontalk/androidclient#872]
### Expected behavior
After choosing the image, the share dialogue (menu with "Camera", "Gallery", "Location", etc.) disappears.

### Actual behavior
The sharing dialogue stays and can't even be closed with the small upwards arrow. I need to leave the PM and enter it again to make the dialogue disappear.

### Steps to reproduce
1. Open a PM.
2. Share an image from the Gallery. Should work fine.
3. Share a second image from the Gallery. Sharing dialogue does not disappear.

### Environment

Kontalk version: Kontalk 4.0.0 beta1-basic

Android version: KitKat 4.4.2

Device model: Fairphone 1

**Comment by daniele-athome** [comment]
Thanks for reporting. Regression introduced in 294193afa99ecca4c66f4f0a9086cae49b41cf5c (by trying to fix #699).

**Comment by StefanBrand** [comment]
Confirmed, works in [latest beta](https://forum.kontalk.org/t/preview-kontalk-for-android-4-0-0-beta1-preview/75?u=stefan).
