### ISSUE TITLE
unable to accept key

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#873]
### Expected behavior
If the Red banner appears and I click "accept" the key should stay as trusted

### Actual behavior
The red banner appears for one of my contacts. 
I click "Details" and then "accept". The red banner disappears. 

Then I go back to chatlist.
If I go back to this contact the red banner appears again.

### Steps to reproduce
I don't know how you can reproduce because it's only one contact. And one time it works for a couple of days.

### Environment

Kontalk version: 4.0.0beta1 (210)
It was also happes on Alpha8

Android version: 6.0.1

Device model:
Sony M4 Aqua

**Comment by StefanBrand** [comment]
Can you find out the specifics of the other person? E.g. which
 - Kontalk version
 - Android/Custom ROM version
 - device model?

Maybe there are other characteristics that make the user different from your other contacts.

**Comment by webratte** [comment]
After this contact is going online the key stay accepted.
He is using a Huawai Phone. Exact Device and Android I will find out soon.

**Comment by webratte** [comment]
Just sendet a CatLog.
I hope it helps.

**Comment by daniele-athome** [comment]
I got it, thanks!

**Comment by daniele-athome** [comment]
@webratte can you pull this file from your device and send it to me please?

`/data/data/org.kontalk/databases/keys.db`

It's your public keyring, nothing really secret.
I don't remember if you have root access (to access this file you may need it).

**Comment by webratte** [comment]
Sorry, I have no root access.
At the moment it works fine again. I have no idea when this problem is happens and when it works :-(
I'm really sure it works fine when this contact is online (connected to the Kontalk server).
And sometimes after he is disconnected for a while the red banner appears. But not everytime...

**Comment by daniele-athome** [comment]
Thanks anyway, I will do some more tests and investigate on the code a little more and let you know.

**Comment by daniele-athome** [comment]
I found the bug and fixed it. To fix your situation though, besides installing the new version which will probably be Dec 4th, you'll need to accept the key while the user is online (because the issue messed up with key timestamps... long story).

**Comment by webratte** [comment]
Will it also work if I delete the Account an re-import the Key?
So I have not to wait until he is online.

I know I will lost all chats. But thats not a big deal.

**Comment by daniele-athome** [comment]
Yes that should reset your keyring.

**Comment by webratte** [comment]
It seems not fixed yet.
If the User is online the red banner don't appears. So I can't accept it.

I have tried to delete the Account and re-import the Key.
It's still how I said in first Post.

**Comment by daniele-athome** [comment]
Can you please try this? I'd like to test a theory.

* delete your account
* go to app info from system settings, open the Kontalk info screen
* kill the app
* clear data
* import your account again

**Comment by webratte** [comment]
Yes, I will do that later. Probably tomorrow.

**Comment by webratte** [comment]
I just did it. It seems to work.
I will report if it happens again.
