### ISSUE TITLE
Unable to send picture if I turn the Phone

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#878]
### Expected behavior
If I take a Photo it should always sendet.

### Actual behavior
If I turn the Phone while I take the picture it will not sendet.

### Steps to reproduce
1.Use Portrait Mode of your phone
2.click in chat the Office clamp icon
3.choose camera
4.If camera App is started turn the Phone to landscape
5.take the Photo
6.the Photo will not sendet

### Environment

Kontalk version: 4.0.0 beta1 (213) Google Playstore 

Android version: 6.0.1

Device model: Sony M4 Aqua

I'm not at home to create a Log

**Comment by OffifialMITX** [comment]
I've tried to reproduce, works fine on my Android 5.1.1

**Comment by daniele-athome** [comment]
It depends on the camera app you use: system-wide auto-orientation must be on and the camera app you use should not change screen orientation when the phone is turned. I've just reproduced it: as soon as you come back to Kontalk in landscape (and you started in portrait earlier), the activity is restarted and it loses the information of the picture just shot. Thanks for reporting!
