### ISSUE TITLE
[Not as important] Functionality

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#880]
Not actually a bug or a fault of Kontalk, but setting the maximum of background tasks to 1 in the developer settings will cause the "share with" menu non-functional.

Every time you try to share anything not via the builtin share menu Kontalk instantly shows a message which says that it doesen't seem like the contact is registrated.

Setting the value back to standart removes the problem again, so it doesn't really matter.

**Comment by OffifialMITX** [comment]
I'm so sorry, it causes the "share with" menu <b>to be</b> non-functional.

**Comment by daniele-athome** [comment]
I'm not really sure I'm trying to reproduce this right. I've tried both ways, having set 1 background process in developer settings first:

* open my gallery app
* share -> Kontalk
* choose a contact

And:

* open an existing conversation
* select Gallery from the attachments panel
* choose an image from my gallery

Both methods work. Can you describe your action sequence please?

**Comment by OffifialMITX** [comment]
Oh, I'm sorry, that was my fault. I've tried to recreate it either and then noticed that I've also clicked on the check box "Delete tasks immediately" (I'm not sure it's the correct translation but it should be right above). Here is what I've done [(video)](https://drive.google.com/open?id=0B8HcTODSY2XzWGcwdDdXOE9hQ1U) [Uploaded on Google drive].
I'll send it to devteam@kontalk.org because I don't want to force you to go to Google]

**Comment by daniele-athome** [comment]
That developer option is quite dangerous and can make some apps not work correctly. Especially when handling activity results. It should be turned on only while debugging applications.
