### ISSUE TITLE
Advanced key exchange

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#881]
After I've read #879 I had an idea (actually even before, but I forgot it) related to another issue which I couldn't find anymore.

Anyway, it would be awsome if you could (if connected to the same network) generate a random and strong encryption key for the private key and print as a QR code. When scanned, Kontalk Android-client sends automatically the encrypted file directly to the desktop client or another Android device.

Same if using bluetooth or AdHoc (or maybe even NFC). It could be also be even easier if when e.g. paired with bluetooth you go to <b>settings > privacy > import private key > via bluetooth</b> (or something else) on the reciver and <b>export private key > via bluetooth</b> on the transmitter. Then both clients do the rest automatically.

When using usb, I suggest to make the same thing with the QR code, then export it to a specific path, then the desktop client reads it and then deletes it autonatically.

Also it would be a nice feuture if you could chose your contacts being exported either.

**Comment by daniele-athome** [comment]
Thanks for the idea, we thought about that too in #122, both QR-code and network-based (e.g. Bluetooth) :-)
