### ISSUE TITLE
Only for the owner it should be possible to add members 

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#890]
### Expected behavior
Only for the owner it should be possible to add members 

### Actual behavior
It seems every member can add other members but not remove

### Steps to reproduce
1. greate a group with 2 or 3 members
2. a not owner member can still add new members.
3.

### Environment

Kontalk version: playstore 4.0.0 beta3 (215)

Android version: 6.0.1

Device model: Sony M4 Aqua 

### Logs

If you have a system log related to the issue please send it via email at
devteam (at) kontalk.org. Please do not attach it or publish it anywhere because
it may contain sensitive information. If you have root access, you can use Catlog
(available on both Google Play and F-Droid) to produce it. Alternatively, if you
have the Android SDK installed on your computer, connect your device and execute:

```
adb logcat -d | grep `adb shell ps | grep org.kontalk | cut -c10-15` >kontalk-log.txt
```

and send us the text file.

### Other

If there is a relevant forum discussion, please link to it here.

**Comment by daniele-athome** [comment]
Thanks for reporting!
