### ISSUE TITLE
remove the "add user" item in chatview

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#891]
Now we have the floating action button to create a group.

And

Add users via group info.

Both really intuitiv.

I think the way to add users via chat view is not intuitiv. Users may be confused.

I was confused and I think we don't need two ways to add users to a already exist group.

**Comment by daniele-athome** [comment]
I don't understand, why should it be confusing? I believe is a nice shortcut, avoiding more taps.

**Comment by daniele-athome** [comment]
Oh wait you're talking about the "Add users" menu item in single-user chats right? I also believe that is a major feature that should exist in an IM app.

**Comment by webratte** [comment]
Yes that's what I mean. 
OK, maybe your right.

But in this case If I tap add user it should be possible to add this user to a already exist group.

**Comment by daniele-athome** [comment]
Ok that's confusing :-)
The fact is the label is "Add user**s**", plural, so I believe it can't be confused with the feature you're describing (am I getting your point right?)

**Comment by webratte** [comment]
In german there is no different between user and useres (german: Nutzer and Nutzer) You know :-) 

And so it looks like I could add THIS user to a group. Not like I can add other usere to this user to create a new group.

What about to rename the item to "create group" or "start group".
OK, not perfect too. But more understanable to me.

BTW. This way I can only create 3 persons groups AFAIK?!

**Comment by daniele-athome** [comment]
> In german there is no different between user and useres (german: Nutzer and Nutzer) You know :-)

Can't you use a word that has plural instead? People? 😇

> What about to rename the item to "create group" or "start group".
OK, not perfect too. But more understanable to me.

It might be a solution, yes.

> BTW. This way I can only create 3 persons groups AFAIK?!

That's kind of a bug, sorry :-) I'll fix it soon.

**Comment by webratte** [comment]
People sounds not really good in this case.
I will think about a better translation.

If I don't find no better translation I will translate it as "new group" or "create group" 

And I think we should talk to other translaters.
Maybe this could be a problem in other languages too.

**Comment by OffifialMITX** [comment]
How about member/s? In german there's also a plural for it.

Am 9. Dezember 2016 23:00:37 MEZ, schrieb webratte <notifications@github.com>:
>People sounds not really good in this case.
>I will think about a better translation.
>
>If I don't find no better translation I will translate it as "new
>group" or "create group" 
>
>And I think we should talk to other translaters.
>Maybe this could be a problem in other languages too.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/891#issuecomment-266135120

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by daniele-athome** [comment]
@webratte is right, German might not be the only language affected by this. Probably something similar to "Start group" or "Create group" would be better. While still using the "Add users" label in the group info screen (that should be clear enough).

**Comment by TheLastProject** [comment]
Honestly, if I see an "Add Member" button in a one-on-one chat I assume it will turn that one-on-one chat and share history with the new member, because in Telegram you have access to part of the history when you join a group chat. Does it replace the current conversation or does it start a new one? In the last case I'd really think we should go with something more like "Start new group chat with..." or so.

**Comment by webratte** [comment]
OK, this could be a solution.
But still it sounds a little bit strange. 
Because I can add members to a already existing group. But not really to a user.

It's hard to explain what I mean (my bad english). 

If we tap this item we create a new group. 
Why not call it "create a group"?

**Comment by webratte** [comment]
Oops,  my Post was aanswerto @OffifialMITX. 
Your was faster:-)
