### ISSUE TITLE
Beta4: Cannot chat with verified people in group

### ISSUE THREAD

**Issue by StefanBrand** [kontalk/androidclient#894]
### Expected behavior
I can chat with a group since everyone is verified.

### Actual behavior
I can only chat with people in private chats, but not in groups (although everyone is verified). Clicking on a group member gives the identity popup, stating "verified", but also presenting me the options "accept | decline | ignore".

### Steps to reproduce
1. Start a chat with 4 people (including yourself).
2. Try to write a message.

### Environment

Kontalk version: beta4-basic.apk

Android version: 4.4.2
Device model: Fairphone 1

### Logs

I'll send you a log.

PS.: There is no *grep* in Windows...

### Other

The others are on beta3 still.
Like in #874 the people appear as verified ( ✅ ). However, when clicking on them, the aforementioned popup comes up.

**Comment by daniele-athome** [comment]
Thanks for the log.
It seems you are not subscribed to one of the members, therefore it is not sending the message. The issue is that the app is not warning you about that.
In the meantime, please check that you can do a private chat with all members.

I'll check for reasons why the app didn't warn you about it.

**Comment by StefanBrand** [comment]
No I can't. One person hasn't accepted me. In the group member view, however, either all appear accepted (green check mark), but all pop ups show the "accept-decline-ignore" dialogue.
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 12. Dezember 2016 10:22:26 MEZ schrieb Daniele Ricci <notifications@github.com>:
>Thanks for the log.
>It seems you are not subscribed to one of the members, therefore it is
>not sending the message. The issue is that the app is not warning you
>about that.
>In the meantime, please check that you can do a private chat with all
>members.
>
>I'll check for reasons why the app didn't warn you about it.

**Comment by daniele-athome** [comment]
Well that's the bug then. The green check only reports about the key but not the actual "chat acceptance" status.

**Comment by OffifialMITX** [comment]
Why can't there be a function to "review" the keys. That could be useful if you accidently press the wrong button trying to accept someone. Also since I am using the beta but some of my contacts still use the 3.1.10, (I've regenerated my key) I can wtite to them but messages from them can't be decrypted untill <b>they</b> recreate their key.

Am 12. Dezember 2016 11:24:44 MEZ, schrieb Daniele Ricci <notifications@github.com>:
>Well that's the bug then. The green check only reports about the key
>but not the actual "chat acceptance" status.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/894#issuecomment-266392624

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by daniele-athome** [comment]
> Why can't there be a function to "review" the keys. That could be useful if you accidently press the wrong button trying to accept someone.

For group chat this feature exists (the group info screen lists all members with key trust status and allows to trust/untrust a member), but not yet for single contacts - to be done soon.

> Also since I am using the beta but some of my contacts still use the 3.1.10, (I've regenerated my key) I can wtite to them but messages from them can't be decrypted untill <b>they</b> recreate their key.

Why would they need to recreate their key to write to you? Message encryption is compatible between versions 3 and 4. The only thing that changes is the group chat protocol.

**Comment by OffifialMITX** [comment]
I have no idea about the reason but i did this 2 times and it didn't work until they recreated their key. I know how irrational this sounds.

Am 12. Dezember 2016 16:02:05 MEZ, schrieb Daniele Ricci <notifications@github.com>:
>> Why can't there be a function to "review" the keys. That could be
>useful if you accidently press the wrong button trying to accept
>someone.
>
>For group chat this feature exists (the group info screen lists all
>members with key trust status and allows to trust/untrust a member),
>but not yet for single contacts - to be done soon.
>
>> Also since I am using the beta but some of my contacts still use the
>3.1.10, (I've regenerated my key) I can wtite to them but messages from
>them can't be decrypted untill <b>they</b> recreate their key.
>
>Why would they need to recreate their key to write to you? Message
>encryption is compatible between versions 3 and 4. The only thing that
>changes is the group chat protocol.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/894#issuecomment-266452838

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by OffifialMITX** [comment]
Just worked a 3rd time.

Am 12. Dezember 2016 16:02:05 MEZ, schrieb Daniele Ricci <notifications@github.com>:
>> Why can't there be a function to "review" the keys. That could be
>useful if you accidently press the wrong button trying to accept
>someone.
>
>For group chat this feature exists (the group info screen lists all
>members with key trust status and allows to trust/untrust a member),
>but not yet for single contacts - to be done soon.
>
>> Also since I am using the beta but some of my contacts still use the
>3.1.10, (I've regenerated my key) I can wtite to them but messages from
>them can't be decrypted untill <b>they</b> recreate their key.
>
>Why would they need to recreate their key to write to you? Message
>encryption is compatible between versions 3 and 4. The only thing that
>changes is the group chat protocol.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/894#issuecomment-266452838

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by daniele-athome** [comment]
I've opened #928 for better understanding of the issue. Thanks again for reporting.
