### ISSUE TITLE
Beta4: Profile picture disappears in the "add group member"-view

### ISSUE THREAD

**Issue by StefanBrand** [kontalk/androidclient#895]
### Expected behavior
The neat little ✅ appears next to the profile picture.

### Actual behavior
When I click on a person to add, their profile picture disappears. It reappears when I deselect the person.

### Steps to reproduce
1. Start a group chat.
2. Click on a person.

### Environment

Kontalk version: beta4-basic.apk

Android version: 4.4.3

Device model: Fairphone 1

**Comment by daniele-athome** [comment]
A checkbox should appear. @acappelli vectors should work out of the box with appcompat on pre-lollipop, right? Can you check please?

**Comment by acappelli** [comment]
@daniele-athome yes vector should work on pre-lollilop device.. 
@StefanBrand  can you send us a screenshot please ?

**Comment by acappelli** [comment]
I've tryed on Android 4.4.2 and the vector was loaded.

![device-2016-12-12-104917](https://cloud.githubusercontent.com/assets/1911447/21094755/ae676ace-c058-11e6-8bec-c07d6047c620.png)

**Comment by StefanBrand** [comment]
Here it is. I hope you can distinguish between actual bug and my anonymisation... 😇
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 12. Dezember 2016 10:30:20 MEZ schrieb Andrea Cappelli <notifications@github.com>:
>@daniele-athome yes vector should work on pre-lollilop device.. 
>@StefanBrand  can you send us a screenshot please ?

**Comment by daniele-athome** [comment]
I'm sorry I don't think the screenshot made it.

**Comment by StefanBrand** [comment]
I updated my post above , but "unfortunately" email replies don't support Markdown... :P 
![screenshot_2016-12-12-11-16-19](https://cloud.githubusercontent.com/assets/8948865/21096695/3e574746-c061-11e6-8ec4-1331c6eed3cc.png)

**Comment by acappelli** [comment]
@StefanBrand can you install this apk and send us a screenshot?? 
https://we.tl/pE9QlqZcci
Thank in advance!

**Comment by StefanBrand** [comment]
Works well apparently:

![screenshot_2016-12-12-13-06-19](https://cloud.githubusercontent.com/assets/8948865/21098928/ed3345c6-c06b-11e6-8e12-fa7a58717a11.png)

**Comment by daniele-athome** [comment]
Fixed in b1b1daae535ce59618fd1986f1bd3cd0d93e9791.
