### ISSUE TITLE
Beta4: Can't delete a group chat

### ISSUE THREAD

**Issue by StefanBrand** [kontalk/androidclient#896]
### Expected behavior
I can delete a group chat without leaving it.

### Actual behavior
I can only delete a group chat when I check "also leave the group".

### Steps to reproduce
1. Start a group chat (4 ppl. incl. yourself).
2. Go to the overview of all chats.
3. Long press the group chat previously created.
4. Click the garbage can.
5. Don't check "also leave the group". Click OK.
6. Group is not deleted.

### Environment

Kontalk version: beta4-basic.apk

Android version: KitKat 4.4.2 without Google Apps

Device model: Fairphone 1

### Other

I'll try to catch a log, if you can't reproduce it.

**Comment by daniele-athome** [comment]
Wait, that's intended behaviour actually: it deletes chat history inside the group, but since you didn't check "also leave groups" it didn't delete the conversation entry (because deleting that would mean leaving the group).

**Comment by abika** [comment]
I guess its a label issue that leads to misunderstanding: If "leave group" is not checked it should display "Delete all messages in this chat"; and if its not checked, "Delete this chat" instead.

**Comment by daniele-athome** [comment]
I've opened #898.
