### ISSUE TITLE
wrong thumbnail orientation in portrait mode

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#899]
### Expected behavior
Orientation of thumbnails should always the same like the photo 

### Actual behavior
Thumbnails of (only) portrait orientated photos is turnd 90°
Landscape mode worked.

### Steps to reproduce
1. Take a photo in portrait mode
2. Send this photo
3. The thumbnail is turned 90°. The orientation of the sended photo is correct. 

### Environment

Kontalk version: Google Play 4.0.0beta4 (216)

Android version: 6.0.1 

Device model: Sony M4 Aqua 

### Logs

I'm sure you don't need a Log.
But if you need one, please let me know.

**Comment by OffifialMITX** [comment]
Can't reproduce on Android 5.1.1 Neffos C5L.

Am 13. Dezember 2016 17:28:54 MEZ, schrieb webratte <notifications@github.com>:
>### Expected behavior
>Orientation of thubnails should always the same like the photo 
>
>### Actual behavior
>Thumbnails of (only) portrait oriantated photos is turnd 90°
>Landscape Mode worked.
>
>### Steps to reproduce
>1. Take a photo I portrait mode
>2. Send this photo
>3. The thumbnail is turned 90° The oriantation of the sended photo is
>correct. 
>
>### Environment
>
>Kontalk version: Google Play 4.0.0beta4 (216)
>
>Android version: 6.0.1 
>
>Device model: Sony M4 Aqua 
>
>### Logs
>
>I'm sure you don't need a Log.
>But if you need one, please let me know.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/899

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by OffifialMITX** [comment]
Have you tried using another camera app?

Am 13. Dezember 2016 17:28:54 MEZ, schrieb webratte <notifications@github.com>:
>### Expected behavior
>Orientation of thubnails should always the same like the photo 
>
>### Actual behavior
>Thumbnails of (only) portrait oriantated photos is turnd 90°
>Landscape Mode worked.
>
>### Steps to reproduce
>1. Take a photo I portrait mode
>2. Send this photo
>3. The thumbnail is turned 90° The oriantation of the sended photo is
>correct. 
>
>### Environment
>
>Kontalk version: Google Play 4.0.0beta4 (216)
>
>Android version: 6.0.1 
>
>Device model: Sony M4 Aqua 
>
>### Logs
>
>I'm sure you don't need a Log.
>But if you need one, please let me know.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/899

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by OffifialMITX** [comment]
*tried to use, sorry folks.

Am 13. Dezember 2016 17:28:54 MEZ, schrieb webratte <notifications@github.com>:
>### Expected behavior
>Orientation of thubnails should always the same like the photo 
>
>### Actual behavior
>Thumbnails of (only) portrait oriantated photos is turnd 90°
>Landscape Mode worked.
>
>### Steps to reproduce
>1. Take a photo I portrait mode
>2. Send this photo
>3. The thumbnail is turned 90° The oriantation of the sended photo is
>correct. 
>
>### Environment
>
>Kontalk version: Google Play 4.0.0beta4 (216)
>
>Android version: 6.0.1 
>
>Device model: Sony M4 Aqua 
>
>### Logs
>
>I'm sure you don't need a Log.
>But if you need one, please let me know.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/899

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by webratte** [comment]
Since @OffifialMITX can't reproduce it on his phone, I think a log can be helpfully.

I will create one and send it to you

**Comment by daniele-athome** [comment]
Thanks @webratte, I got the log. What camera app did you use?

**Comment by webratte** [comment]
I use the standard camera App of my Sony Xperia M4 Aqua.

**Comment by daniele-athome** [comment]
@webratte I tried with 5 different camera apps and can't reproduce the issue. Can you email me the original picture shot with the camera please? Or make another one, it's same, as long as it's the original file that is causing the issue shot by the Sony Camera app).

**Comment by webratte** [comment]
Just sendet.
I hope it helps. Please let me know if I can do something else.

**Comment by daniele-athome** [comment]
Works on my device. I believe it's an OEM thing. By doing some research I also found out that some devices report always orientation normal (0 degrees) so it's impossible for Kontalk to determine the correct orientation.
I'll switch to [the new ExifInterface provided by the support library](https://android-developers.googleblog.com/2016/12/introducing-the-exifinterface-support-library.html), you will then be able to try this again in beta5.

**Comment by webratte** [comment]
OK, I will report immediately after release of Beta 5

**Comment by webratte** [comment]
Fixed in current Beta 👍
Thank you
