### ISSUE TITLE
Every minute check without Google Play

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#902]
### Expected behavior
An option to check for new messages more often (now the less is 5 minutes but I need every minute check)/

### Environment

Kontalk version: F-Droid stable

Android version: 5.1

Device model: Oukitel U7 PRO

**Comment by daniele-athome** [comment]
Disconnecting and connecting again is an expensive process in terms of energy and traffic. If you need more frequent checking, your best bet is to never disconnect: believe me, you will consume little to no more energy.

**Comment by Buranek** [comment]
OK.
