### ISSUE TITLE
Fails to send quad images

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#903]
### Expected behavior
Sending images with png or jpg/jpeg format with resolution 512x512 or higher (1024x1024) with the same aspect ratio.

### Actual behavior
Tries to send image, even puts to it's pictures folder but gives an error.

### Steps to reproduce
1. Download any 512x512 image
2. Try to send someone
3. You'll get an error

### Environment

Kontalk version: F-Droid Stable

Android version: 5.1

Device model: Oukitel U7 PRO

**Comment by daniele-athome** [comment]
Thanks for reporting! I can't reproduce it, would you mind sending a log of the error to our devteam address please?

**Comment by Buranek** [comment]
If you'll tell me how to capture it without adb. Or normal Catlog log will be good for you?

**Comment by daniele-athome** [comment]
Of course! If you have root access.

**Comment by Buranek** [comment]
Sent.

**Comment by daniele-athome** [comment]
Got the log, thanks! It's hard to reproduce in some cases, but I've found the relevant code and I'm fixing it.

**Comment by Buranek** [comment]
Sweet!
