### ISSUE TITLE
Difference preferences for group and single chat balloon theme

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#906]
### Expected behavior
In the group chat the cantact icons should be always visible

### Actual behavior
The iPhone and both classic themes don't show tne icons

### Steps to reproduce
1. Create a group chat with at least 2 other patricipants
2. Both other patricipants have to write something
3. Swich to the iPhone, classic or the old classic theme

### Environment

Kontalk version: 4.0.0 Beta4, F-Droid

Android version: 5.1.1

Device model: Neffos C5L

### Other

Perheaps you should be able to select themes for the group an normal chat separately

**Comment by daniele-athome** [comment]
> Perheaps you should be able to select themes for the group an normal chat separately

Thanks for reporting and totally right.
