### ISSUE TITLE
share with groups

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#907]
### Expected behavior
You should be able to share files into the group chat

### Actual behavior
You aren't able to share files into the group chat

### Steps to reproduce
1. Create/join a group
2. Go to any file browser / gallery and share via kontalk
3. You are not able to select a group

### Environment

Kontalk version: 4.0.0 beta4

Android version: 5.1.1

Device model: Neffos C5L

**Comment by webratte** [comment]
Duplicate of 
https://github.com/kontalk/androidclient/issues/864
