### ISSUE TITLE
Crash: no encryption methods specified

### ISSUE THREAD

**Issue by StefanBrand** [kontalk/androidclient#908]
### Expected behavior
No crash.

### Actual behavior
Within seconds of starting the app Kontalk crashes.

### Steps to reproduce
1. Start Kontalk.
2. Count to 2 or 3.
3. Kontalk crashes

### Environment

Kontalk version: beta4-basic.apk

Android version: Lollipop 5.1

Device model: Fairphone 2

### Logs

I'll send it immediately after creating this issue.

### Other

Happens to two Fairphone 2 users (I only have a log of one of them), but not to the third. All of them are using the same beta4-basic.apk.

**Comment by daniele-athome** [comment]
Thanks for reporting! This is the actual cause of #901 which I thought I had fixed - apparently not.
There is a pending message causing the issue in some way. Do you remember the message details? As in was it a group chat? Are some of the members in the group not verified/allowed yet?

**Comment by StefanBrand** [comment]
I have asked my friend for more details. Will get back to you, when I got them.

If I remember correctly, this started around the time, #894 appeared.

https://github.com/kontalk/androidclient/issues/894

The thing is that the person that hadn't accepted us then, doesn't experience crashes now. The other two FP2s, who had accepted everyone, have crashes and I with my FP1 don't have crashes.


-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 20. Dezember 2016 09:39:23 MEZ schrieb Daniele Ricci <notifications@github.com>:
>Thanks for reporting! This is the actual cause of #901 which I thought
>I had fixed - apparently not.
>There is a pending message causing the issue in some way. Do you
>remember the message details? As in was it a group chat? Are some of
>the members in the group not verified/allowed yet?

**Comment by daniele-athome** [comment]
@StefanBrand I've analyzed the matter more deeply, I believe there is a particular situation on your internal messages database that is causing this issue. I'm going crazy trying to reproduce it but I just can't find that exact case. Would you mind sending me your messages.db file inside `/data/data/org.kontalk/databases`? via email?
If you feel uncomfortable with that (completely understandable), I'll need an exact sequence of all group command messages (the group events, the blue little rectangles that appear in your group thread when something happens, such as subject changes, which users were added/removed, so on), along with the number of group members when the group was created. This should give me a fair picture of your group status without actually looking at your database (hoping that I'm going into the right direction). Feel free to mail the devteam or me directly.

**Comment by daniele-athome** [comment]
I believe I've found the cause of this issue and I should have fixed it. @StefanBrand for now (if you didn't get it yet) your friend's database is not necessary. You can try it again in next beta coming very soon. If the app is still crashing a workaround is to disconnect from the network (so Kontalk won't try to connect), delete the faulty messages (you should have messages pending in an empty group) and connect again.

**Comment by StefanBrand** [comment]
Actually I just saw that there is one group, which had messages marked 
with an X (not sent), but the others had responded to them. The latest 
"message" in that group was: Group topic changed. In the chat list that 
group chat was also marked with an X.

Am 28.12.2016 um 22:13 schrieb Daniele Ricci:

**Comment by daniele-athome** [comment]
@StefanBrand that's from your side, which doesn't crash if I understand correctly. And the missing authorization to one of the users was handled correctly for the most part. The other members were affected differently by this.

**Comment by StefanBrand** [comment]
Indeed, that's from my side. I don't see, however, how the others should 
delete unsent messages, if their Kontalk crashes within 2 or 3 seconds. 
I thought, I should delete messages.

I hope the next beta release fixes the crashes for them. :)

Am 28.12.2016 um 22:23 schrieb Daniele Ricci:

**Comment by daniele-athome** [comment]
> how the others should delete unsent messages, if their Kontalk crashes within 2 or 3 seconds.

How I said, make them disconnect from network so Kontalk won't connect and won't crash. Then they'll have all the time to open Kontalk and delete the messages.
