### ISSUE TITLE
Paperclip not showing anything in small screens

### ISSUE THREAD

**Issue by Megver83** [kontalk/androidclient#909]
### Expected behavior
Touch the paperclip and see the common "Galley", "Audio", "Video", etc. share icons.

### Actual behavior
I touch the paperclip and no icons appear, only a white color.
![kontalk bug](https://cloud.githubusercontent.com/assets/22277674/21401126/f5e0fc54-c7aa-11e6-94e1-cd4d2c9049b9.png)

### Steps to reproduce
1. Open Kontalk.
2. Select a chat.
3. Touch the paperclip next to the contact name.

### Environment

Kontalk version: 3.1.10, Fdroid build.

Android version: Android Lollipop 5.1.1, CyanogenMod 12.1

Device model: Samsung Galaxy Pocket Neo GT-S5310

### Other

I've seen this behavior only in small screens. Galaxy Pocket Neo's is 3", resolution: 240x320.

**Comment by OffifialMITX** [comment]
That's the resolution the old nokia cell phones like the 2700 had ;-)
Sorry, I just had to say this.

Am 21. Dezember 2016 19:34:28 MEZ, schrieb Megver83 <notifications@github.com>:
>### Expected behavior
>Touch the paperclip and see the common "Galley", "Audio", "Video", etc.
>share icons.
>
>### Actual behavior
>I touch the paperclip and no icons appear, only a white color.
>![kontalk
>bug](https://cloud.githubusercontent.com/assets/22277674/21401126/f5e0fc54-c7aa-11e6-94e1-cd4d2c9049b9.png)
>
>
>### Steps to reproduce
>1. Open Kontalk.
>2. Select a chat.
>3. Touch the paperclip next to the contact name.
>
>### Environment
>
>Kontalk version: 3.1.10
>
>Android version: Android Lollipop 5.1.1, CyanogenMod 12.1
>
>Device model: Samsung Galaxy Pocket Neo GT-S5310
>
>### Other
>
>I've seen this behavior only in small screens. Galaxy Pocket Neo's is
>3", resolution: 240x320.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/909

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by daniele-athome** [comment]
This should be fixed in the latest 4.0 beta, available on F-Droid too. Please upgrade and try again (I just did a successful test on an 240x320 emulator).

**Comment by gigi-tello** [comment]
I'm having the same problem with Kontalk 4.0.0-beta5 in 2 different devices, but it works in landscape orientation.

The devices are:
HTC Wildfire S - 3.2'' 320x480 screen, android 2.3.3.
LG Optimus L3 II - 3.2'' 240x320 screen, android 4.1.2.

The screenshots are from the HTC phone.

Thank you for the hard work with Kontalk!

![2017-01-03_19 19 13](https://cloud.githubusercontent.com/assets/18199466/21625345/0274729a-d1ea-11e6-8ad4-c828dae638c9.jpg)
![2017-01-03_19 19 23](https://cloud.githubusercontent.com/assets/18199466/21625346/02768512-d1ea-11e6-8c76-f8dbecbf11b7.jpg)

**Comment by gigi-tello** [comment]
Here is a system log of the Android 2 phone. It was made with Catlog, filtered with "kontalk". In the first part the phone is in vertical orientation and the second part is in landscape.

I hope it helps!

[kontalk-2017-01-05-09-06-18.txt](https://github.com/kontalk/androidclient/files/692493/kontalk-2017-01-05-09-06-18.txt)

**Comment by daniele-athome** [comment]
@gigi-tello I'm sorry but a "kontalk" filter won't do in this case. And since this might be a system-related issue in some way I'd like to also see logs from the system.
Please send the whole system log to devteam (at) kontalk.org, thank you.
