### ISSUE TITLE
Enter key can be sent as a message

### ISSUE THREAD

**Issue by Megver83** [kontalk/androidclient#910]
### Expected behavior
Use the Intro key as Enter. When using Enter to write a new line, I don't want Kontalk to send it as a message, because there is no text

### Actual behavior
I press the Enter key in a chat (without letters or a message) and a white message can be sent. This is the same screenshot as the one in [here](https://github.com/kontalk/androidclient/issues/909).
![kontalk bug](https://cloud.githubusercontent.com/assets/22277674/21401126/f5e0fc54-c7aa-11e6-94e1-cd4d2c9049b9.png)

### Steps to reproduce
1. Set up the Intro key as Enter key.
2. Select a chat
3. Put Enter in an message (without letters) and send it.

### Environment

Kontalk version: 3.1.1.0 - 4.0.0-beta4, Fdroid build.

Android version: Android Lollipop 5.1.1, CyanogenMod 12.1 and Android JellyBean 4.2.2, Replicant 4.2

Device model: Samsung Galaxy Pocket Neo GT-S5310 and Samsung Galaxy S3 GT-I9300

### Other

I don't think this is hard to fix, so I hope on the next release this disappears. This issue does not happen in WhatsApp, for the record.

**Comment by OffifialMITX** [comment]
Basicly what I've mentioned in #847 , I don't think there's no technical difference between a space and an enter, am I right, @daniele_athome ?

**Comment by daniele-athome** [comment]
Strictly speaking, a message with a newline **is** a message...

@OffifialMITX yes, same thing.

**Comment by Megver83** [comment]
> Strictly speaking, a message with a newline is a message...
> 
> @OffifialMITX yes, same thing.

Yes, but with no useful info. Why would someone want to send an enter as a message?

**Comment by OffifialMITX** [comment]
Maybe not directly, but on the other hand, does a message like "**p**" or "**XXxxXxxxXx**" have a useful info? Or maybe there should be a filter which **only** allows to send messages if they contain at least one full word and a point?

**Comment by Megver83** [comment]
>Maybe not directly, but on the other hand, does a message like "p" or "XXxxXxxxXx" have a useful >info?
Yes, it can be a password o a code for sth.
But I insist, an enter is totally usefulness and ridiculous. At least in the settings adding an option to enable/disable the enter key considered as message could be a solution (instead of using it as intro).

**Comment by OffifialMITX** [comment]
Well, maybe not adding any feature in the settings (if you are able to tweak everything you won't tweak anything), but adding a pop up warning for cases 
like this one like "Your message's content doesen't seem to be valid, send anyway?", what do you think, @daniele_athome ?

Am 23. Dezember 2016 18:02:13 MEZ, schrieb Megver83 <notifications@github.com>:
>>Maybe not directly, but on the other hand, does a message like "p" or
>"XXxxXxxxXx" have a useful >info?
>Yes, it can be a password o a code for sth.
>But I insist, an enter is totally usefulness and ridiculous. At least
>in the settings adding an option to enable/disable the enter key
>considered as message could be a solution (instead of using it as
>intro). 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/910#issuecomment-269018346

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by daniele-athome** [comment]
I don't think a warning message would be useful in this case (if not invasive), we shall either allow them or not.
I'm sorry but I really can't see the problem of keeping such a feature as it is. A blank message is a message and I can't see any reason for not allowing them besides *ridiculousness* and *sending a blank message by mistake* (which are not enough to say "so let's disallow them").

**Comment by TheLastProject** [comment]
On that note, a valid reason for a blank message could be to ping a friend. When we start to arbitrarily disallow things we may break workflows of people that work for them.

**Comment by OffifialMITX** [comment]
Besides, you can send SMS messages without <b>ANY</b> content.

Am 24. Dezember 2016 15:11:45 MEZ, schrieb Daniele Ricci <notifications@github.com>:
>I don't think a warning message would be useful in this case (if not
>invasive), we shall either allow them or not.
>I'm sorry but I really can't see the problem of keeping such a feature
>as it is. A blank message is a message and I can't see any reason for
>not allowing them besides *ridiculousness* and *sending a blank message
>by mistake* (which are not enough to say "so let's disallow them").
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/910#issuecomment-269085846

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by Megver83** [comment]
OK, so while no one else complains about, there sholudn't be any problem
