### ISSUE TITLE
Crash: user leaves group

### ISSUE THREAD

**Issue by 115ek** [kontalk/androidclient#911]
### Expected behavior
No crash.

### Actual behavior
Kontalk crashes after clicking the group.

### Steps to reproduce
1.create group with at least 2 members
2.admin/owner leaves the group
3.entering the chat again crashes Kontalk (for owner and member)

### Environment

Kontalk version: build from scratch, basic flavor @ f3c5664edf8071d249abf85df883d6f9e88b058a

Android version: CyanogenMod 14.1

Device model: iyokan / Sony Ericsson Xperia Pro

localization: german

### Logs

relevant parts:

> 12-21 21:13:07.273 18755 18755 E AndroidRuntime: FATAL EXCEPTION: main
12-21 21:13:07.273 18755 18755 E AndroidRuntime: Process: org.kontalk, PID: 18755
12-21 21:13:07.273 18755 18755 E AndroidRuntime: java.util.UnknownFormatConversionException: Conversion = ')'
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2730)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2759)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2591)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at java.util.Formatter.parse(Formatter.java:2524)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2472)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2426)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at java.lang.String.format(String.java:2670)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at android.content.res.Resources.getString(Resources.java:406)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at org.kontalk.ui.view.GroupContentView.bind(GroupContentView.java:83)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at org.kontalk.ui.view.GroupContentView.bind(GroupContentView.java:38)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at org.kontalk.ui.view.MessageContentViewFactory.createContent(MessageContentViewFactory.java:71)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at org.kontalk.ui.view.EventMessageTheme.processComponents(EventMessageTheme.java:83)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at org.kontalk.ui.view.MessageListItem.bind(MessageListItem.java:165)
12-21 21:13:07.273 18755 18755 E AndroidRuntime: 	at org.kontalk.ui.adapter.MessageListAdapter.bindView(MessageListAdapter.java:87)

**Comment by daniele-athome** [comment]
Thanks for reporting. This is a translation error - I need to remind myself to write string unit tests!!
Just fixed in 2915ec41c9cb497daa57527c4632aa64f7b13bc8.

**Comment by 115ek** [comment]
Hey! So fast! I just wanted to send my PR ;)

**Comment by TheLastProject** [comment]
Actually, @daniele-athome needs to accept that too, he only fixed Catalan, not German.

**Comment by TheLastProject** [comment]
Nevermind, I just updated it on Weblate for German myself :)

**Comment by 115ek** [comment]
I searched 3 hours for it :D but nevermind, I've learned a lot about getting things from a logfile and debug mysterious errors...
Next time I'll be faster ;)

**Comment by webratte** [comment]
@TheLastProject Bad german translations are my part.
But I will forgive you that you do my work ;-) 

Thank you :+1:
