### ISSUE TITLE
String unit tests

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#912]
Too many times rogue translations made the app not working correctly or even crash. Write some unit tests to automatically verify all strings within a certain degree of reliability, possibly before 4.0 release.

**Comment by OffifialMITX** [comment]
I'm sorry, what are "rogue translations" supposed to be?

Am 21. Dezember 2016 23:28:17 MEZ, schrieb Daniele Ricci <notifications@github.com>:
>Too many times rogue translations made the app not working correctly or
>even crash. Write some unit tests to automatically verify all strings
>within a certain degree of reliability, possibly before 4.0 release.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/912

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by TheLastProject** [comment]
Bad translations that cause the app to crash.

Like "Are you sure you want to delete your chat with %s" being translated to "Are you sure you want to delete your chat with % s". Because the app can't find the %s it wants to replace with another word then it will crash instead.

**Comment by OffifialMITX** [comment]
Shouldn't it be easy to detect strings like that one? Anyway thanks for the explanation.

Am 21. Dezember 2016 23:41:49 MEZ, schrieb Sylvia van Os <notifications@github.com>:
>Bad translations that cause the app to crash.
>
>Like "Are you sure you want to delete your chat with %s" being
>translated to "Are you sure you want to delete your chat with % s".
>Because the app can't find the %s it wants to replace with another word
>then it will crash instead.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/912#issuecomment-268662919

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by daniele-athome** [comment]
Maybe I can address this by just using lint. I'll do some research.

**Comment by daniele-athome** [comment]
Checks can be done using lint so I'm now closing this. However, manual periodic checks must be done manually because there is a problem with Travis CI having some old version of the Android SDK or something like that (some checks are reported erronously)

**Comment by webratte** [comment]
And I think we translators have to be more carefully to not change placeholders like "%s" and so on.
