### ISSUE TITLE
Warn user when creating a group that all users must know each other

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#915]
Since it is not so obvious, present a dialog with a "do not show again" check box stating that all members must know each other (as in subscribed to each other) in order for the group to work.

**Comment by bastoGrande** [comment]
A warning always feels to me like a bad workaround. How could this be more obvious to the common people who have no idea of it and especially not of encryption?

But I can't think of something else, too. Unfortunately.. I was thinking of fixing this issue way ahead. 
You can't change something when the admin is adding group members and if the members don't know each other, than it's not the problem of the admin, it's the problem of the members. 

Maybe when entering the group as a member and there is one member that I don't know, give me a choose to either accept or deny the key of the unknown member? But if you have a group of 10 unknown member, this will be a pain in the ass... And then there is still the other side of it, what happens to the member, that was already in the group and doesn't know the new member as well.

Mhm, anyone an idea? Or would be just the best to go for the workaround/warning?

**Comment by OffifialMITX** [comment]
What about something like a contact request? (Manually/automatically/both)?

Am 28. Dezember 2016 23:37:07 MEZ, schrieb bastoGrande <notifications@github.com>:
>A warning always feels to me like a bad workaround. How could this be
>more obvious to the common people who have no idea of it and especially
>not of encryption?
>
>But I can't think of something else, too. Unfortunately.. I was
>thinking of fixing this issue way ahead. 
>You can't change something when the admin is adding group members and
>if the members don't know each other, than it's not the problem of the
>admin, it's the problem of the members. 
>
>Maybe when entering the group as a member and there is one member that
>I don't know, give me a choose to either accept or deny the key of the
>unknown member? But if you have a group of 10 unknown member, this will
>be a pain in the ass... And then there is still the other side of it,
>what happens to the member, that was already in the group and doesn't
>know the new member as well.
>
>Mhm, anyone an idea? Or would be just the best to go for the
>workaround/warning?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/915#issuecomment-269552373

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by daniele-athome** [comment]
I want to say that this issue is a just a reminder for the quick (and dirty, I know) workaround that I'll implement just because it's quick and 4.0 deadline is approaching (actually we are already in the release period). There will a more complex approach later, with a more elaborate group creation process involving this issue of knowing each other.
