### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#916]
2 Strings weren't translated.

**Comment by OffifialMITX** [comment]
https://gist.github.com/3c3af32649a21781e915dfbebfcb1723

**Comment by daniele-athome** [comment]
Thanks @OffifialMITX, but we use a portal for that: https://translate.kontalk.org
Please create an account and submit your translations there, the workflow into the source code tree is automatic.

**Comment by webratte** [comment]
German is already translated 100%. The XML file of @OfficialMITX seams to be outdated.
That's why we always should use weblate ;-) 

Am 29. Dezember 2016 14:29:15 MEZ schrieb Daniele Ricci <notifications@github.com>:
