### ISSUE TITLE
I don't even know how to describe it

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#918]
I'll just say what happened:

Becaus one of my apps stopped working properly, I've rebooted my phone into the safe mode, then accidentely I opened F-Droid which spammed me with errors so I've rebooted it again into the safe mode.

After it (the app still didn't work as it should) I've rebooted it (I think it was) twice and then I've opened Kontalk.

I was in the login menu and couldn't load my exported key (I'm pretty sure I typed the right one). But that's not all.

After I was logged in I tried to load my contacts and only my own name I've typed in and one other contact appeared.

I tried to update the contact list and now, several hours later, it still isn't done.

Every contact is shown only in it'd hash@beta.kontalk.net form (I'll upload screenshots later)

Only the one contact I had in the list has it's comment (status).

Version:
4.0.0 beta4 from F-Droid on Android 5.1.1 API 22 (no root)

Steps to reproduce:
1. Install Kontalk
2. Have some contacts and one group
3. Reboot the device to safe mode
4. Open F-Droid (it should crash)
5. Redo 3.
6. Reboot normally
7. Open Kontalk (you'll get to the login menu)
8. Stpp the app via settings
9. Clear cache
10. Start it again
11. Redo 8.
12. Clear app data
13. Start it
14. Create a new account
15. Try to update the contact list

Ask me if you have questions and I wish a happy new year for everybody who reads this.

**Comment by daniele-athome** [comment]
Why don't you also start to randomly delete system files while you're at it?
(sorry man just messing with you :P I'll try to help you but this could be borderline system debugging)

A catlog would be nice for a start. I could try something in an emulator, next year :-)

Happy new year!

**Comment by OffifialMITX** [comment]
I can't promise i wouldn't if I could XD, no problem.

> *"Programming today is a race between software engeneers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning"* - Rich Cook

**Comment by daniele-athome** [comment]
@OffifialMITX please remember the catlog whenever you can.

**Comment by OffifialMITX** [comment]
I'm so sorry, it seems like it wasn't Kontalk's fault because my phone started to stop working correctly short time before that issue (the reason why I even started the secure mode) and short time after it it became almost unusable so I was forced to reset the phone.

I will try to reproduce it after the new screenshots are done.

Am 4. Januar 2017 22:48:07 MEZ, schrieb Daniele Ricci <notifications@github.com>:
>@OffifialMITX please remember the catlog whenever you can.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/918#issuecomment-270496534

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.
