### ISSUE TITLE
Can't decrypt

### ISSUE THREAD

**Issue by lupa18** [kontalk/androidclient#923]
### Expected behavior
I should receive and read amessage

### Actual behavior
A text: (encrypted) appears on every message from a user (I only have that user as contact)

### Steps to reproduce
1. Install kontalk importing original key
2. Try to chat with my friend
3. Also deleting original conversation and creating a new one, same problem

### Environment

Kontalk version: Beta 5 (installed from link posted here)

Android version: Cyanogenmod 13.0

Device model: Xiaomi Mi4

### Other

Screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/463429/21628531/fc4b2e76-d1fe-11e6-89d0-f2934072c037.png)

**Comment by daniele-athome** [comment]
This is happening because your friend hasn't accepted your new key yet, so he/she is still encrypting using your old key. Try to tell your friend to refresh his/her Kontalk contact list (I'm assuming he/she is using 4.0 beta5 as well, if not, version 3.1.10 had a bug that needed to the user manually refresh the contact list in some cases).

**Comment by lupa18** [comment]
Hello Daile, 
I'm searching for an option such as "Update contacts" but I couldn't find it :(

**Comment by webratte** [comment]
Hi,
click "new chat". In contact list click the "three dot Menü=>refresh" or something like that. I have the german UI and don't know the correct english words used.

**Comment by lupa18** [comment]
I also did that :(

**Comment by webratte** [comment]
Can you only not decrypt "older" messages (before refreshed contact list)? 

Or also messages wich sendet after you and your friend have refreshed your contact list?

**Comment by daniele-athome** [comment]
That has to be done on your friend's device (just to be absolutely sure).

**Comment by lupa18** [comment]
we both refreshed contact lists and doesn't work
sorry, but now I uninstalled it and trying to install from f-droid ... when I achieve that I will post more on this issue

**Comment by lupa18** [comment]
Now working. 
I reinstalled generating new keys using beta6.1 and now is working
