### ISSUE TITLE
Can receive messages from blocked XMPP user

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#925]
### Expected behavior
A blocked user should not be able to send messages

### Actual behavior
Messages sent by a blocked user on XMPP (non-Kontalk) are received anyway

### Steps to reproduce
1. Give your @beta.kontalk.net account name to an user on normal XMPP
2. Accept their request to add them
3. Block them

### Environment

Kontalk version: (please also specify origin, e.g. F-Droid or Google Play)
4.0-beta5 from F-Droid
Android version: (please also specify custom ROM name if applicable)
CyanogenMod 14.1 (Android 7.1.1)
Device model:
Motorola Moto E 2015 LTE (surnia)

### Logs
Unfortunately cannot currently get a log file

### Other
The other user is on jabber.systemli.org, I believe using Pidgin.

**Comment by daniele-athome** [comment]
Thanks for reporting. It might be a server issue, I'll get on it.

**Comment by daniele-athome** [comment]
It was a server configuration issue. Blocking wasn't working at all. Please try again now.

**Comment by daniele-athome** [comment]
Please note that you need to block the user again now.
