### ISSUE TITLE
Groups are gone after deleting data or new installation

### ISSUE THREAD

**Issue by 115ek** [kontalk/androidclient#926]
### Expected behavior

- after new installation of Kontalk and importing keyfile afterwards, all earlier attended or created groups should be visible in chat-overview 
### Actual behavior
- after new installation of Kontalk and importing keyfile afterwards,  groups are not visible in chat-overview
- same problem when deleting data of Kontalk in android settings
- difficult to re-enter group (owner has to delete and re-invite you)   

### Steps to reproduce
1. join group / create group --> group is visible in overview
2. delete data in android settings
3. start Kontalk
4. group is not visible anymore (how to re-enter?)

### Environment

Kontalk version: build from scratch, basic flavor @ df4963b3df946129fa144929c80464b1cc8bc828

Android version: CyanogenMod 14.1

Device model: iyokan / Sony Ericsson Xperia Pro

localization: german

**Comment by daniele-athome** [comment]
I'm sorry at the moment is not possible because neither chats nor groups are retained. It is expected for one of the next versions, after 4.0.0.

**Comment by tetris4** [comment]
@daniele-athome perhaps it would make sense to keep this open and assign it a 4.x milestone, for tracking reasons and avoiding duplication. 
This could be also done for other issues that are planned for the future.

**Comment by daniele-athome** [comment]
Well, this is actually a duplicate of #104, that's why I rejected it. I changed the labels to reflect the correct status.
