### ISSUE TITLE
Wrong implementation of email intent

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#934]
### Expected behavior
Mail adress should insert in the "To" field in my mail app

### Actual behavior
I have to find an insert the correct adress to send a log

### Steps to reproduce
1. enable internal logging
2. click send log
3. chose your mail app
4. a new mail will started but without a receiver address

### Environment

Kontalk version: 4.0.0 Beta 6

Android version: 6.0.1

**Comment by daniele-athome** [comment]
Here we begin with crappy implementations :-)
You have a Sony Xperia right? What email program are you using?

**Comment by webratte** [comment]
Yes, Xperia M4 Aqua with k9mail.

I thought it's a easy thing (like in HTML) to add it to a special field or something like this.

**Comment by daniele-athome** [comment]
The fact is I did implemented it and it works on both emulators and my device :-)
I'll investigate on possible bugs and workarounds.

**Comment by webratte** [comment]
Ups, I thought you simply forgot it 😉

**Comment by daniele-athome** [comment]
Ok I believe I found the culprit :-)

**Comment by webratte** [comment]
If not, I could send a Log. There is a easy way implemented to do that in Kontalk 😜
