### ISSUE TITLE
Crash by try to share a link via Browser 

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#935]
### Expected behavior
It should be possible to share a link via Firefox browser

### Actual behavior
Kontalk crashed if I try that

### Steps to reproduce
1. Open a website in Firefox (or other Browser?) 
2. Click the share sign
3. Choose Kontalk 
4. Choose a contact
5. Kontalk will closed

### Environment

Kontalk version: 4.0.0 beta6 Play store version 

Android version: 6.0.1 

Device model: Sony Xperia M4 Aqua 

### Logs

In a few minutes I will send a log

**Comment by webratte** [comment]
Sharing inside Kontalk also dosn't work.

**Comment by daniele-athome** [comment]
Unfortunately this is a regression from 29f1bdf307a6c48d888c43ed109b4bab6be409e9. I'll have to release a new beta tomorrow just for this fix. Thanks for reporting.
