### ISSUE TITLE
Emoji library changes by rotating screen

### ISSUE THREAD

**Issue by 115ek** [kontalk/androidclient#936]
### Expected behaviour
all emojis should be displayed in the same way (either iOS, or android or custom...) in portrait and landscape mode (when typed in editTextBox and not sent yet)

### Actual behaviour
-in portrait mode the emojis are shown in iOS style
-in landscape mode they are shown in default android style
(typed in editTextBox, not sent)

### Steps to reproduce
1.portrait mode: insert emoji, don't send
2.change screen rotation to landscape
3.open keyboard

### Environment
Kontalk version: build from scratch, basic flavor @ 653f26189cbe31e4e53cd00fa3b06e0e63a2f3f9

Android version: CyanogenMod 14.1

Device model: iyokan / Sony Ericsson Xperia Pro

localization: german
![portrait](https://cloud.githubusercontent.com/assets/11771774/22196480/aa31cff6-e14d-11e6-9274-ae5524e170ee.png)
![landscape](https://cloud.githubusercontent.com/assets/11771774/22196485/af0804a0-e14d-11e6-9af7-1de777e86783.png)

**Comment by TheLastProject** [comment]
I cannot reproduce this on 4.0.0-beta5 on CyanogenMod 14.1 on my Motorola Moto E 2015 LTE (surnia). Are you sure that in the second screenshot you're not using the keyboard's emoji button instead of Kontalk's emoji button?

**Comment by 115ek** [comment]
I used the Kontalk emoji button (emojicon library) to insert the smiley once, then rotated the device and opened the keyboard in landscape mode. I have also tested with an Android 4.1.1 device and official Kontalk 4.0.0 beta 6 basic release.

![landscape_4 1 1](https://cloud.githubusercontent.com/assets/11771774/22203416/41998f86-e16d-11e6-81f8-e286b0b3f42e.png)

**Comment by daniele-athome** [comment]
Despite having disabled the system behaviour leading to that input mode, some input methods (read: AOSP keyboard) insist in making the input window their own way and I'm not sure I can control it from the application. I'll investigate.

**Comment by daniele-athome** [comment]
Found it. However this will disable the fullscreen landscape view it may affect smaller screens.

https://developer.android.com/reference/android/view/inputmethod/EditorInfo.html#IME_FLAG_NO_EXTRACT_UI

However, most IM apps seem to be doing the same, so...
