### ISSUE TITLE
quick reply

### ISSUE THREAD

**Issue by keshto** [kontalk/androidclient#948]
using the fdroid version when a message is received there are "Read" and "Call" quick actions. It would be nice to see a quick reply like most modern messaging apps.

**Comment by webratte** [comment]
Hi,
it seems your not the only one.
I think it's a duplicate of https://github.com/kontalk/androidclient/issues/629 and https://github.com/kontalk/androidclient/issues/630 😉

**Comment by keshto** [comment]
yes it is a duplicate. sorry should have searched first.
