### ISSUE TITLE
take chatlogs to a new phone

### ISSUE THREAD

**Issue by freddii** [kontalk/androidclient#950]
I got a new phone and like to take the chatlogs from my old phone to the new one. 
Is there an easy way to backup the chat history and import it to another device?

**Comment by daniele-athome** [comment]
Currently no easy way of doing it, sorry. You need root access because you have to backup this file:

```
/data/data/org.kontalk/databases/messages.db
```

And then restore it in the same path on the other device after you've installed it but before starting it.

**Comment by tetris4** [comment]
For future reference, there are open reports for this enhancement: #17 and #618.
