### ISSUE TITLE
Why are there different menus?

### ISSUE THREAD

**Issue by 115ek** [kontalk/androidclient#960]
### Expected behavior
the menu button or the three points in the right upper corner should open the menu

### Actual behavior
the menu button or the three points in the right upper corner are opening the menu - but two different ones (same menu points but different layout)

### Steps to reproduce
1.click three buttons in the right upper corner
2.click menu button (I have hardware keys...) but there are also soft keys on an other device to open the menu
--> get two different menus

### Environment

Kontalk version: 4.0.0 F-Droid

Android version: 7.1.1 & 4.1.1

Device model: Sony Ericsson Xperia Pro & Alcatel OT-997D

Screenshots are made with OT-997D

**Menu opened by app**
![app_button](https://cloud.githubusercontent.com/assets/11771774/23104964/dbb81888-f6d7-11e6-99b5-101d41f53f30.png)

**Menu opened by OS button (in this case softkey)**
![os_button](https://cloud.githubusercontent.com/assets/11771774/23104966/e14da0f6-f6d7-11e6-89ab-a79b3489008a.png)

**Comment by tetris4** [comment]
Fwiw, I have checked 5 other apps (riot, lightning, slide, noise, forecastie) and the behavior is exactly the same as in Kontalk. So my guess is that this is an Android related thing.

**Comment by daniele-athome** [comment]
Actually, the overflow toolbar item [should not appear on devices with hardware keys](https://developer.android.com/design/patterns/compatibility.html), so this is probably a support library issue. Weird that this issue (if it is an issue) hasn't been reported or fixed.

**Comment by OffifialMITX** [comment]
It does appear on my device with hw keys.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by daniele-athome** [comment]
> It does appear on my device with hw keys.

As I was saying, it is probably a support library issue :-)
