### ISSUE TITLE
key re generation is not shared to friends, new key cannot get accepted by friends

### ISSUE THREAD

**Issue by cavebeat** [kontalk/androidclient#969]
### Expected behavior
After a key-recreation my friends can not accept my new key. 

### Actual behavior
I have reinstalled my phone's OS and have not saved/backuped my Kontalk keys. After installing Kontalk again i can send a message to my friends which is encrypted but is shown as not trusted. My friends send me a messages which is encrypted and i can not decrypt it. it's encrypted to an older key of mine. 
My friends are shown the message to check identiy, block or accept the new key. but the accept button does not work or help. They still only know my old key-pair. and can not update to my new key. 
It's not possible to check the key which they already have from me. i can only show them my fingerprint, but there is no possibility to check which fingerprint(pubkey) they use to decrypt a message to me. 

### Steps to reproduce
1. create a new key on your kontalk
2. receive encrypted messages with no chance to decrypt them from friends
3. try to TOFU and accept the new keypair and fail

### Environment
Kontalk version: 4.0 from F-Droid on CyanogenMod13.0 6.0.1 Samsung Galaxy S2 (my)
Kontalk version 4.0 from Google Play store on Stock Rom Samsung Galaxy S3(Friend 1)
Kontalk version 4.0 from F-Droid on OxygenOS OnePlusOne 1

### Other
Forum and issues are checked, but couldn't find a relevant topic.

**Comment by daniele-athome** [comment]
Sorry for the late reply. This issue should have been fixed with upcoming version 4.0.1. Feel free to open it again if necessary. Thank you!

**Comment by tomterl** [comment]
I encounter this ATM with two devices running 4.0.3 - my old phone died, so I have a new key-pair; getting my new key worked fine for my kids phones, but not my wife's -- accepting the new key does not work; the fingerprint​ shown does not match the one shown on my phone, that's strange and maybe what's wrong.

**Comment by daniele-athome** [comment]
The issue should have been fixed on latest version 4.0.4 which is currently in beta on Google play only. Could you try that? 
A quick workaround is to refresh your contact list.

**Comment by tomterl** [comment]
Contact list refresh does not work - I think the device is 
'kontalk-haunted' ;-). I'll add both devices to the beta-programm and 
report back here. This might take me a while...

**Comment by webratte** [comment]
Don't forget:

The people who not get your new key have also to refresh the contact list.
