### ISSUE TITLE
New text strings

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#970]
In new Kontalk 4 there are new text strings that are untranslated. Please bring them to Weblate, so I can update the Russian translation.

**Comment by daniele-athome** [comment]
I've found only 3:

- "Users added:" (group chats)
- "Users removed:" (group chats)
- "Decryption failed" (for notifications)

What are the ones you found?

**Comment by Buranek** [comment]
"Please remember that every member in the group must know each other in order to chat."

**Comment by daniele-athome** [comment]
It is present on strings.xml:

```
    <string name="create_group_disclaimer">Please remember that every member in the group must know each other in order to chat.</string>
```
