### ISSUE TITLE
Normal JIDs

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#971]
**Feature request**
I want to communicate with normal Jabber contacts with Kontalk. The only problem is that Kontalk JID is a hash, not username. Is it possible to add normal logins as mirrors, so I can give my normal JID to person?
Example: username@kontalk.org

**Comment by Buranek** [comment]
@webratte yes, I know. But it's extremely long.

**Comment by webratte** [comment]
I'm sure, XMPP users can copy and Paste 😜

**Comment by daniele-athome** [comment]
It's not possible to use JID aliases for this purpose, the only way to add a Kontalk user is to use the full JID. However we were thinking of using a "translation service" for phone numbers, i.e. you give the server a phone number, the server returns the full Kontalk JID (see kontalk/tigase-extension#62). However, the other XMPP client would need support for XEP-0100.
