### ISSUE TITLE
Profil UI

### ISSUE THREAD

**Issue by DoM1niC** [kontalk/androidclient#974]
Hey Bro, 
Kontalk works amazing, I create a own server with your Server (Tigase) and all works great with some tricky tricks like HTTP Upload Stuff... ;) 

My idea is to make a profil instead of adressbook Like....

1. Profil picture
2. Status
3. Fingerprint QR Code
4. Personal notification's.
5. Menu forward to adressbook

**Comment by daniele-athome** [comment]
I'm not sure what you're talking about, you're talking about a contact screen, much like the one mentioned in #456 right? We were thinking of doing something like that for a future release.
