### ISSUE TITLE
Names aren't updating correctly

### ISSUE THREAD

**Issue by Fohroer** [kontalk/androidclient#979]
### Expected behavior
Renaming contact in list will give a new name to it after updating roster in Kontalk.

### Actual behavior
Renaming contact in list will give a new name only if you have added a contact in Contacts (maybe if deleted too)after updating roster in Kontalk.

### Steps to reproduce
1. Change contact name
2. Update roster in Kontalk
3. You will see the same contact name but if you click to view info you will see his/her new name in Contacts overlay.

### Environment

Kontalk version: lastest from F-droid.

Android version: 5.1

Device model: Oukitel U7 PRO

**Comment by OffifialMITX** [comment]
Works on my 5.1, but sometimes only after a restart.

**Comment by daniele-athome** [comment]
Indeed it might be a caching issue, although IIRC I made sure the cache was evicted in these situations.
Can you try killing the app to see if it works after an app restart?

**Comment by Buranek** [comment]
@daniele-athome even after phone reboot there were no changes!

**Comment by daniele-athome** [comment]
Sorry for the delay, I'm back now (had trouble with internet access). Any update on this? You can try deleting app's data, it will purge all user information in Kontalk. It will also delete key trust information though, but it'll be enough to re-approve your buddies' keys.

**Comment by Fohroer** [comment]
@daniele-athome Mmm, deleting history, keys and contact list. Do you really think that this sounds good?
After reboot I have performed an update again — and it's succeed. Anyway, problem had to be, so I reported you.

**Comment by daniele-athome** [comment]
> @daniele-athome Mmm, deleting history, keys and contact list. Do you really think that this sounds good?

Of course this an extreme action to be taken as a temporary workaround. As I said, this should be fixed in 4.0.1 anyway.
I'm glad it works again :-)
