### ISSUE TITLE
Account information occasionally lost GT-I9301I Android 4.4.2

### ISSUE THREAD

**Issue by strk** [kontalk/androidclient#991]
I cannot tell which series of events trigger this but I occasionally find myself locked out of my account on an android 4.4.2 phone (GT-I9301I). I've often reported this on IRC but never filed a ticket, so now here it is after it happened again.

After a few times I've learn to keep my keys backup around so now at least it doesn't hurt too much :)

**Comment by daniele-athome** [comment]
Hi, what do you mean locked out? The account is deleted and you're brought to the registration screen or do you get the "authentication error" notification?

**Comment by strk** [comment]
I'm brought to the registration screen

**Comment by susobaco** [comment]
I think that also happened to a friend, suddenly, when opening kontalk, had to re-register, we had to accept a new certificate, and expel it and re-add it to the group. For now, it only happened once.

**Comment by daniele-athome** [comment]
This can happen when Kontalk is moved to the external memory. Is this your case?

**Comment by strk** [comment]
Not my case, unless the system can do this without me noticing

**Comment by susobaco** [comment]
Neither is my case.

**Comment by strk** [comment]
I just noticed Twidere account was also lost, dunno if the two events are somehow related

**Comment by daniele-athome** [comment]
That is the only case when this could happen, otherwise Android is deleting the account probably because of some bug or some hidden security feature which I can't handle anyway, sorry.
